### ISSUE TITLE
Probe Size tooltip - incorrect display and incorrect formula

### ISSUE THREAD

**Issue by sup3rb** [pyfa-org/Pyfa#1026]
## Bug Report
Probe size tooltip doesn't change as sensor strength of fit changes.  Also, the comment in code seems to indicate PYFA is using a pre-nerf version of the probing formula.

### Expected behavior:
Probe size should vary as sensor strength of fit changes (and follow the correct ratio formula; which is floored at 1.08, contrary to the comment in def probeSize(self).  

For reference, see 
https://forums.eveonline.com/default.aspx?g=posts&t=183135
https://www.reddit.com/r/Eve/comments/31ke3d/is_unprobable_still_a_thing/cq2icic/

BTW, many people in game aren't aware of this old nerf and think unprobeable is still a thing. 

### Actual behavior:
Probe size tooltips remains unchanged as sensor strength of fit changes.

### Detailed steps to reproduce:
1.  Pull up any fit
2.  Hover over signature, see "probe size" tooltip
3.  Add or remove an active sensor booster
4.  Hover over signature, see "probe size" tooltip - it has not changed

### Fits involved in EFT format (Edit > To Clipboard > EFT):
any/all

### Release or development git branch? Please note the release version or commit hash:
gui/builtinStatsViews/targetingMiscViewFull.py 
eos/saveddata/fit.py 

(I think, not certain)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
Fits at the 1.08 sensor/sig limit are probeable by perfect skilled toons with implants in scanning ships.  

I guess the displayed tooltip assumes a perfect prober in a covops frigate?  With or without implants?

Not sure how this should be represented in PYFA.

**Comment by blitzmann** [comment]
Hmm, seems to only update if the sig radius changes, but doesn't update if the sensor strength changes. I'll take a look into that and also the 1.08 claim. Thanks for the report!

**Comment by blitzmann** [comment]
I've fixed the issue with it not updating in our dev branch. The reason behind it is simple: the stats that you see are cached, and when a fit is changed we check to see if the stats we're looking at has changed. In this situation, the probe size tooltip was added while checking the sig radius cache (so if sig radius didn't change, this wouldn't update properly)

I simply moved the tooltip assignment outside of the cache checking code.

As for the incorrect cap, I've gone ahead and changed it to 1.08. There was testing done a few years ago with the probe changes that apparently showed otherwise, but this seems to be the common value that the community uses, and until recent testing can confirm a different value, I've changed it here.

Thanks!

**Comment by BartMassey** [comment]
svRagnarok of Signal Cartel has led a bunch of tests in the past month. My reading of his resulting forum posts and spreadsheets is that any Probe Size < 1.087 seems to be cut off at 1.087, which corresponds to Probe Strength around 78.6: pretty easy probing for a reasonably-equipped and skilled prober. So you may want to mail svRagnarok in-game to confirm, or leave the cap where it is, or just get rid of it.
