### ISSUE TITLE
AppVeyor - Automated Windows Testing

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#1084]
Looks like a slick solution for running tests and builds on Windows.

Demo on using it for Python:
https://github.com/ogrisel/python-appveyor-demo

**Comment by blitzmann** [comment]
Looks interesting. Tests are already run on Travis, so this might be useful for builds if we ever start doing actual builds and not the shit we currently do with skels... at the same time, it feels like overkill? If we start doing legit builds, those are easily done at the time of a new release by running setup.py. So what benefits would this service give us?

**Comment by Ebag333** [comment]
> Tests are already run on Travis, so this might be useful for builds if we ever start doing actual builds and not the shit we currently do with skels... at the same time, it feels like overkill? 

Travis only tests on Ubuntu though.  How many times have we ran into the "works fine on Windows, runs like shit on Linux?" :)

And since most of our users are likely Windows, it makes more sense to test there than Travis.

Also, yes, builds.

>If we start doing legit builds, those are easily done at the time of a new release by running setup.py.

Assuming we do that and not do actual legitimate builds.

>So what benefits would this service give us?

Testing in a Windows environment in an automated fashion (currently only Linux).  Being able to trigger builds, so creation of the executable is more easily done.  Means we can have live builds, and people could grab beta versions of dev, and stuff like that!

**Comment by blitzmann** [comment]
> How many times have we ran into the "works fine on Windows, runs like shit on Linux?"

Usually issues like that are on the GUI side of things, which we can't test anyway (to my knowledge, at least without a hell of a lot of effort). There's very little low-mid level issues that affect only one platform. Locales being really the only one that sticks out in my mind. Most of the test that we eventually will have would be, I assume, fitting calculations and service functionality, which should fucntion the same regardless of platform.

> Being able to trigger builds, so creation of the executable is more easily done.

I mean, the current "build" system (for me anyway) is one python command to build them all. If we move to actual builds, then it's still click "Run" on the setup profile in pycharm.

Granted, having a build server that keeps up with dev branch would be nifty. I actually used to run a an automated nightly build for pyfa that people could access via my webserver. But honestly, there was so little use out of it. I don't think the demand is really there for up to the minute development builds.

**Comment by Ebag333** [comment]
And now there's an example where Linux and Windows are behaving differently for a `service`. So it's not just GUI stuff. 

See #1086

**Comment by blitzmann** [comment]
If you want to play around with it, that's cool. But I'm not gonna be shelling out $$$ for FOSS.

You noted that the automated builds keep up with master. That is pretty neat, but Travis does it too, and is one of the reasons why I'm still considering keeping our old build method since it's currently done on Linux (for clarification, I still have not yet taken the time to evaluate pyinstaller, so take that comment with a grain of salt)

As for #1086 I'm leaning towards something is being overlooked rather than an inherit difference due to operating system. This is pure python code, no wx, which should run the same regardless. If sqlalchemy is saving a record twice on Linux and once on Windows, that would be a major flaw in sqlalchemy.

**Comment by Ebag333** [comment]
It's free sooooooo.....

>You noted that the automated builds keep up with master. That is pretty neat, but Travis does it too

Bingo. If we can get automated builds working, the only one missing is OSx. ;)

**Comment by blitzmann** [comment]
>It's free sooooooo.....

Right, forgot it's free for FOSS projects. 

Again, if it's something you're interested in, have a look. 

> Bingo. If we can get automated builds working, the only one missing is OSx. ;)

Travis supposedly does OS X as well, though I haven't looked further into. I don't know if it would support what we want to since pyfa is a GUI application, but if we can build from the terminal and can get the necessary dependencies installed correctly, shouldn't be a problem (theoretically)

**Comment by Ebag333** [comment]
Neat feature.  Multiple versions of Python!
https://puu.sh/v8dY3/8b0fef5fa0.png

**Comment by blitzmann** [comment]
closing as this was merged in yesterday
