### ISSUE TITLE
1.28.1 not properly announcing missing requests module

### ISSUE THREAD

**Issue by FeldTheorie** [pyfa-org/Pyfa#1089]
### Expected behavior:
User is notified about missing requests module, including required version information.

### Actual behaviour:
When trying to start pyfa.py it fails silently without a message being given. However pyfa.py -d reveals:

Traceback (most recent call last):
  File "./pyfa.py", line 290, in <module>
    from gui.mainFrame import MainFrame
  File "/home/martin/Downloads/pyfa/gui/mainFrame.py", line 46, in <module>
    from gui.mainMenuBar import MainMenuBar
  File "/home/martin/Downloads/pyfa/gui/mainMenuBar.py", line 33, in <module>
    from service.crest import Crest
  File "/home/martin/Downloads/pyfa/service/crest.py", line 15, in <module>
    from service.pycrest.eve import EVE
  File "/home/martin/Downloads/pyfa/service/pycrest/eve.py", line 8, in <module>
    import requests
ImportError: No module named requests

**Comment by Ebag333** [comment]
What OS are you running? 

We have some requirements files now, for folks running from source.

**Comment by FeldTheorie** [comment]
Damn, I thought I had included this, sry. OS is KDE neon (running on an Ubuntu LTS 16.04 base).

My issue is that all other dependencies let pyfa fail noisily but this one didn't throw any errors.

**Comment by Ebag333** [comment]
To be honest, we only noisily catch a few. There are a dozen or so we don't catch.  The ones we catch are the ones that are absolutely critical to running Pyfa, everything else we just let quietly fail.

I'm a bit torn about how to handle this.  It'd be nice to warn users that they're missing reqs when running from source, but on the other hand lots of people might never open graphs, or CREST, and just don't care that those components use a particular module they don't have.

@blitzmann what are your thoughts on this?  We could loop through our requirements and pop up a warning if any are missing (a non-terminating message box, so Pyfa keeps running).  Too intrusive?

@FeldTheorie I'm leaning toward _not_ popping up an intrusive box, but printing to console a warning.  What are your thoughts on this?

**Comment by blitzmann** [comment]
Requests is a required package at the moment, hence the error. It's listed as part of the requirements for pyfa.

The only thing that uses it is crest stuff for now (simply because pycrest came with the dependency), but that may change down the road to include more things. It's a handy package to have, and easy to install. I'm inclined to have a hard requirement for it. Otherwise we could do the shit that we currently do for os x deprecated package and conditionally enable the crest stuff if the user has requests. Since we already do it for that platform, it would be trivial to do it in this case. But I'm hoping to move away from those hacks eventually and I feel it's just easier for use to assume it's required for pyfa and have the user download it as a dependency.

We don't need to loop through requirements, that over-engineering the problem. A simple conditional to see if user has package would suffice.

**Comment by Ebag333** [comment]
>The only thing that uses it is crest stuff for now 
>I'm inclined to have a hard requirement for it. Otherwise we could do the shit that we currently do for os x deprecated package and conditionally enable the crest stuff if the user has requests. 
>I feel it's just easier for use to assume it's required for pyfa and have the user download it as a dependency.

Well, the way I see it is this.

1) If we move forward with the current setup in #1048 , then the user is going to get a unhandled exception message box and Pyfa will quit.  Not really the optimal scenario, but see #5.
2) We can wrap our imports in try/excepts. Ugh.  That causes us to have to add a ton of code and makes it messier.  Plus handling the exception (matplotlib is a good example of why we should avoid this).
3) Loop through our requirements, warn the user.  That's super easy to do (like 5 lines of code).  Problem is, we'd have to import all our requirements in `pyfa.py`, which means slowing down startup significantly and loading a bunch of stuff that potentially never gets used.
4) Put hard requirements ala sqlAlchemy and wxPython in `pyfa.py`.  Again, means loading things we're often not using.
5) We have a frickin' `requirements.txt` now.  Requests is already in it.  If someone is running from source and they don't install everything out of the requirements file, it's on their own head.

>We don't need to loop through requirements, that over-engineering the problem. A simple conditional to see if user has package would suffice.

It's not a "simple conditional" because we don't load it in `pyfa.py`.

We can do it for sqlAlchemy, wx, and logbook because they're all imported in `pyfa.py`.  Those are also the only three that are strictly required to launch Python.

**Comment by Ebag333** [comment]
>Loop through our requirements, warn the user. That's super easy to do (like 5 lines of code). Problem is, we'd have to import all our requirements in pyfa.py, which means slowing down startup significantly and loading a bunch of stuff that potentially never gets used.

Figured out a way to do this.

It's not _perfect_.  It can flag modules as possibly being missing when they aren't (`PyYAML` and `python-dateutil` are two, because we don't import them by those names, but we have to have those names in our requirements.txt file....ugh. Keep the same name people.

We can either just explicitly skip those two, or do some other special handling for them.

It's easy, though, and dynamic, so if (when) we add more requirements down the road it won't require a code change to validate.

**Comment by blitzmann** [comment]
Done with 1.29 :)
