### ISSUE TITLE
Crash on delete fittings

### ISSUE THREAD

**Issue by ToyZorus** [pyfa-org/Pyfa#1161]
OS version: 	Linux-4.9.0-1-amd64-x86_64-with-debian-9.0
Python: 	2.7.13
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.15
Logbook: 	1.0.0
pyfa version: 1.29.1 Stable - YC119.5 1.0
pyfa root: /opt/Pyfa-1.29.1
save path: /home/XXXX/.pyfa
fs encoding: UTF-8

EXCEPTION: 'NoneType' object has no attribute 'projectedFits'

  File "/opt/Pyfa-1.29.1/gui/sfBrowserItem.py", line 347, in OnLeaveWindow
    self.Refresh()
  File "/opt/Pyfa-1.29.1/gui/shipBrowser.py", line 2006, in Refresh
    fit = sFit.getFit(activeFit)
  File "/opt/Pyfa-1.29.1/service/fit.py", line 254, in getFit
    for fitP in fit.projectedFits:

**Comment by blitzmann** [comment]
Hi there,

Can you describe what you were doing when you tried to delete the fitting? Was the fit open when you tried to delete it?

**Comment by Ebag333** [comment]
This (along with most of the others) is probably from where we don't have a fit object and just assume it's there.  Simple `if None` check fixes it.  There are literally dozens of these scattered all over the code.

**Comment by blitzmann** [comment]
> This (along with most of the others) is probably from where we don't have a fit object and just assume it's there. Simple if None check fixes it. There are literally dozens of these scattered all over the code.

Yep, I'm aware it's due to the `sFit.getFit()` call, since it assumes the fit you're trying to get exists. A simple `is None` would indeed fix it. However, that doesn't address why this error is happening in the Refresh(), as I have a conditional there to not run if the `FitItem` has been deleted, which happens when the user deletes the fit https://github.com/pyfa-org/Pyfa/blob/9f5e14fe2d8210475db8b16a0e9a4a0c2d9dc3bf/gui/shipBrowser.py#L2004

May have to go with the known fix though, as the cause of this eludes me.
