### ISSUE TITLE
Using the search window triggers an error dialog

### ISSUE THREAD

**Issue by BartMassey** [pyfa-org/Pyfa#1184]
## Bug Report

Typing in the search window on 1.29.2 triggers an error dialog on every character.

### Expected behavior:

I get to search for a ship.

### Actual behavior:

Error dialog pops up for each initially typed character. Then Pyfa hangs.

### Detailed steps to reproduce:

Start Pyfa. Start to type "imicus".

### Fits involved in EFT format (Edit > To Clipboard > EFT):

N/A

### Release or development git branch? Please note the release version or commit hash:

1.29.2

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Debian Jesse + unstable

### Other relevant information:

```
OS version: 	Linux-4.9.0-2-amd64-x86_64-with-debian-9.0
Python: 	2.7.13
wxPython: 	3.0.2.0
SQLAlchemy: 	0.9.4
Logbook: 	1.0.0
pyfa version: 1.29.2 Stable - YC119.5 1.0
pyfa root: /usr/local/apps/pyfa-1.29.2
save path: /home/bart/.pyfa
fs encoding: UTF-8

EXCEPTION: 

  File "/usr/local/apps/pyfa-1.29.2/gui/shipBrowser.py", line 940, in searchStage
    ShipItem(self.lpane, ship.ID, (ship.name, shipTrait, len(sFit.getFitsWithShip(ship.ID))),
  File "/usr/local/apps/pyfa-1.29.2/service/fit.py", line 94, in getFitsWithShip
    fits = eos.db.getFitsWithShip(shipID)
  File "/usr/local/apps/pyfa-1.29.2/eos/db/saveddata/queries.py", line 239, in getFitsWithShip
    fits = removeInvalid(saveddata_session.query(Fit).options(*eager).filter(filter).all())
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2292, in all
    return list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 72, in instances
    rows = [process[0](row, None) for row in fetch]
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 455, in _instance
    state.manager.dispatch.load(state, context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/event/attr.py", line 257, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/events.py", line 196, in wrap
    return fn(state.obj(), *arg, **kw)
  File "/usr/local/apps/pyfa-1.29.2/eos/events.py", line 77, in apply_rel_listeners
    listen(rel, 'append', rel_listener)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/event/api.py", line 61, in listen
    _event_key(target, identifier, fn).listen(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/event/registry.py", line 180, in listen
    self.dispatch_target.dispatch._listen(self, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/events.py", line 1631, in _listen
    event_key.base_listen(propagate=propagate)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/event/registry.py", line 219, in base_listen
    for_modify(target.dispatch).append(self, propagate)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/event/attr.py", line 324, in append
    event_key.append_to_list(self, self.listeners)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/event/registry.py", line 230, in append_to_list
    _stored_in_collection(self, owner)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/event/registry.py", line 71, in _stored_in_collection
    assert dispatch_reg[owner_ref] == listen_ref
```

**Comment by BartMassey** [comment]
Browsing down to Imicus and trying to open my Imicus fits apparently triggers the same bug.

**Comment by BartMassey** [comment]
On the other hand, with a fresh PyFA fittings directory, everything seems to work fine. So perhaps some database conversion issue?

**Comment by BartMassey** [comment]
Backing up my fits to XML using 1.28.1 and then restoring with a fresh 1.29.2 resolved the problem. Still probably needs looking into. I've saved my old .pyfa dir (of course): let me know if you want me to zipball it and put it somewhere.

**Comment by Ebag333** [comment]
There was another user who's DB I just fixed. After migration 22, it seems 23 failed. Because the DB version doesn't update until after all the migrations are done, it rolls back to where it started (in that particular case, version 5).

There's also no validation before migrations are run, so it's possible that re-running a migration causes problems.

I'd be curious to see your DB, and see if it looks similar to the one I was looking at, if you want to email it to me: ebagola@gmail.com

**Comment by BartMassey** [comment]
Sent. Thanks.

**Comment by blitzmann** [comment]
> There's also no validation before migrations are run, so it's possible that re-running a migration causes problems.

Re-running a migration shouldn't cause issue - that's why there are try/catches in it. Those are basically checks to see if the migration has been applied and, if not, run the migration. Additionally, I specifically test this myself every now and then by setting my database to 0 and having it go through the motions. What _is_ possible however is breaking due to downgrading, especially for columns that require info. For example, the new create and modified columns - if user updates to latest and those columns are created and the code expect data from them, but user downgrades to an earlier release without that code, then upgrades again... that could potentially be an issue since it could cause NULLs. Never really found a good way to handle that scenario. But re-running migrations or going from 0-latest shouldn't break anything.

@BartMassey Glad to hear you got this working by regenerating the database. As for the error, it's odd. It doesn't list the exception, which is wierd, but I've seen that for a few things... Can you reproduce this consistently with your old `.pyfa` directory? can you also send me the files of your old `.pyfa` directory to sable.blitzmann@gmail.com? I would like to take a peak and see if there's anything funky in the database or logs. Thanks!

**Comment by blitzmann** [comment]
@Ebag333 you are absolutely correct. Doesn't happen when it's a new database, but when it's an older database that hasn't been updated in a long time (so, like, setting it to version 1), it breaks. Should be an easy fix... don't know a good way to handle it long term though without having to remember to check previous migrations and see if new things are affected. Any thoughts?

Additionally, I don't think it has anything to do with the issue @BartMassey described, so that's still up in the air.

**Comment by BartMassey** [comment]
Unfortunately, my fresh 1.29.2 install is now exhibiting the same bug that the migrated 1.28.1 did. I've reverted to 1.28.2 and my old database for now. @blitzmann, @Ebag333 I'll send you both sets of databases, but as you say I don't think it's just a database migration issue. My suspicion is that I have a too-old version of some Python supporting package. Is it straightforward to check on startup that you're getting sufficient versions of everything?

**Comment by blitzmann** [comment]
@BartMassey I tested and could reproduce on Linux using sqlalchemy 0.9.4 (haven't tried on Windows yet, but I assume it would be the same issue). Try updating to >=1.0 and let me know (pyfa has a soft min requirement of 1.0.5, see README).

I'll take a closer peak at it tomorrow, however this may just be a situation where an update is required. As I said in my other comment, it looks like it's getting caught up in the new sqlalchemy events I added to support the Recent Fits feature. I develop on 1.0.5, and while events were added in 0.8, there may very well be differences in how they work in between versions. Let me know if the update works for you :)

**Comment by BartMassey** [comment]
Yep, that's got it. I apparently installed `sqlalchemy` 0.9.4 via `pip` a while back, and it was shadowing my distro version 1.1.6. So totally my bad. With 1.1.6 it seems to work perfectly.

Could Pyfa check package versions as it comes up and pop an error dialog then?

Thanks much for figuring this out. I had tried updating `sqlalchemy`, but of course hadn't noticed that Pyfa was still using that ancient version.

**Comment by blitzmann** [comment]
> Could Pyfa check package versions as it comes up and pop an error dialog then?

pyfa does have something in place for that, but the version isn't set correctly for sqlalchemy due to osx-deprecated still using 0.6 i believe (so, the absolute minimum version is 0.6 or something). We still have some folks that use it because the other mac version doesn't work well on later OS X version (or something, I don't specifically remember). The sqlalchemy event stuff isn't turned on in the deprecated version, so they don't run into this issue. I hope to change the whole os x issue soon, but for now it's what we've got.

I looked at it a bit more today, and there's not much I can recommend other than updating sqlalchemy, which you've done and said it work. So mission accomplished :D Glad we got it working for ya :)

**Comment by BartMassey** [comment]
Thanks for looking into it. Maybe you could turn off the sqlalchemy stuff anytime it is below the required version?

**Comment by blitzmann** [comment]
> Thanks for looking into it. Maybe you could turn off the sqlalchemy stuff anytime it is below the required version?

I already turn it off if the build is mac deprecated as that is the only build to use an outdated version. However, I didn't consider source users also potentially being behind as well. I plan to focus on the mac builds soon to get them up to snuff, and then up the sqlalchemy version. In the meantime, I potentially could check the sqlalchemy version on everything except the mac deprecated build and spawn a warning for anything under 1.0. I'll look into doing that :)

**Comment by BartMassey** [comment]
Thanks!
