### ISSUE TITLE
Copying Fit, Deleting, then Creating New Fit for Same Hull Keeps Mods From Copied Fit

### ISSUE THREAD

**Issue by HindenPeter** [pyfa-org/Pyfa#1207]
## Bug Report
Copied a Vargur fit, didn't change the name and immediately deleted it. Created a new blank fit for the same hull, which erroneously shows mods from the copied-then-deleted fit. EXCEPTION: Module(ID=4349, name=Pithum C-Type Adaptive Invulnerability Field) at 0x824dd70 is not in list

### Expected behavior:
New fit created without mods.

### Actual behavior:
New fit is created with mods showing, but are not actually there.

### Detailed steps to reproduce:
1: Have a fit.
2: Copy fit.
3: Immediately delete the fit without changing anything.
4: Create new fit for the same hull using the "New fitting" button.
5: Attempt to remove module that was contained in the previous, deleted fit.
6: Pyfa throws the exception outlined above, and pyfa becomes unusable.
7: Restart pyfa; new fit will just be named "[hull] fit" instead of the name given by the user.
8: Attempting to copy the fit that was previously copied now causes pyfa to lock completely. Restarting pyfa appears to fix this issue.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Vargur, C5?]

Capacitor Flux Coil II
Capacitor Flux Coil II
Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer
Republic Fleet Gyrostabilizer

Pithum C-Type Adaptive Invulnerability Field
Adaptive Invulnerability Field II
Gist X-Type X-Large Shield Booster
Pith X-Type Shield Boost Amplifier
Republic Fleet Large Cap Battery
Republic Fleet Large Cap Battery

Bastion Module I
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

Large Capacitor Control Circuit II
Large Capacitor Control Circuit II

### Release or development git branch? Please note the release version or commit hash:
1.29.3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10 x64

### Other relevant information:
This may be related to issue #1208

**Comment by blitzmann** [comment]
Huh, interesting. I wasn't able to reproduce 100% of the time, but this did pop up on fit delete:

```
OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.29.4 git - YC119.5 1.0
pyfa root: C:\Users\Ryan\Sync\Git\blitzmann\Pyfa
save path: C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\saveddata
fs encoding: mbcs

EXCEPTION: A conflicting state is already present in the identity map for key (<class 'eos.saveddata.module.Module'>, (183381,))

  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\gui\sfBrowserItem.py", line 317, in OnLeftUp
    btn.DoCallback()
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\gui\sfBrowserItem.py", line 50, in DoCallback
    self.callback()
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\gui\shipBrowser.py", line 1802, in deleteBtnCB
    self.deleteFit()
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\gui\shipBrowser.py", line 1819, in deleteFit
    sFit.deleteFit(self.fitID)
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\service\fit.py", line 188, in deleteFit
    eos.db.saveddata_session.delete(fit)
  File "C:\Users\Ryan\Sync\WinPython-32bit-2.7.10.1\python-2.7.10\lib\site-packages\sqlalchemy\orm\session.py", line 1635, in delete
    self._delete_impl(st_)
  File "C:\Users\Ryan\Sync\WinPython-32bit-2.7.10.1\python-2.7.10\lib\site-packages\sqlalchemy\orm\session.py", line 1857, in _delete_impl
    self.identity_map.add(state)
  File "C:\Users\Ryan\Sync\WinPython-32bit-2.7.10.1\python-2.7.10\lib\site-packages\sqlalchemy\orm\identity.py", line 132, in add
    % (key, ))
```

And then trying to remove a module causes a SQLAlchemy session error (since previous error caused an exception and no rollback was issued)

Are you able to reproduce these consistently? Can you post the complete output of the error? Thanks!

**Comment by blitzmann** [comment]
k, I've been able to reproduce semi-consistently. I think this is what is happening:

When we copy a new fit in the database, it's assigned a new ID (usually the MAX + 1, lets say 450). When we delete the copy, the fit ID (450) is deleted and the max Fit ID is now 449. But, when we create a new fit, it's given the ID of 450 again, instead of 451 like other sane RDBMS.

The problem, I believe, stems from the fact that when we first copied the fit, the fit object is created. Deleting the fit deletes it from the database, but it's still potentially floating around in memory. When we create the second fit object, it's given the same fit ID as the old thing, and thus some of the old things may reference it (which is why creating a copy, deleting it, and then creating an fit with that hull shows the deleted fits modules...). Actually, this bug seems to happen in any circumstance of deleting the most recently created fit, then creating a new fit (deleting the vargur fit and then opening a Retribution creates a new vargur - same as the one deleted).

I'm still gonna dig into this to learn more about it, however I think #961 describes a possible option. The only problem with it is it's somewhat dangerous due to it being a large change tot he user database, so it needs to be triple check for functionality to avoid database corruption.

**Comment by blitzmann** [comment]
Actually... oops.

https://github.com/pyfa-org/Pyfa/commit/45c3533501af3d3b51fe95335bbbc576f607f0d5#diff-aba60a343427091a39efc5967f24ba36R188

Seems it was caused by this addition in 1.29.3. `remove()` removes the object from our local database cache, and then deletes it, whereas doing a simple session delete deletes it from the database and doesn't touch the cache. This is why fitID, along with the old fit object, is floating around.

I was testing some things out and forgot to revert this statement back. Will make a commit shortly that should fix it, and post an updated build here :)

**Comment by HindenPeter** [comment]
You literally posted that right as I was about to hit "Comment" with a paste of the error log... so here it is anyway, haha:
`OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.29.3 Stable - YC119.5 1.0
pyfa root: C:\Program Files (x86)\pyfa
save path: C:\Users\brayd\.pyfa
fs encoding: mbcs

EXCEPTION: Instance '<Module at 0x7b123f0>' has been deleted.  Use the make_transient() function to send this object back to the transient state.

  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinViews\fittingView.py", line 118, in OnData
    self.dropFn(x, y, data)
  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinViews\fittingView.py", line 204, in handleListDrag
    self.swapItems(x, y, int(data[1]))
  File "C:\Program Files (x86)\pyfa\library.zip\gui\builtinViews\fittingView.py", line 450, in swapItems
    sFit.swapModules(self.mainFrame.getActiveFit(), srcIdx, mod2.modPosition)
  File "C:\Program Files (x86)\pyfa\library.zip\service\fit.py", line 685, in swapModules
    fit.modules.insert(dst, srcMod)
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\orm\collections.py", line 1088, in insert
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\orm\collections.py", line 1044, in __set
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\orm\collections.py", line 716, in fire_append_event
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\orm\attributes.py", line 936, in fire_append_event
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 46, in append
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\orm\session.py", line 1589, in _save_or_update_state
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\orm\session.py", line 1846, in _save_or_update_impl
  File "C:\python-2.7.10\lib\site-packages\sqlalchemy\orm\session.py", line 1832, in _update_impl
`

**Comment by blitzmann** [comment]
@HindenPeter please download and test this out to see if you notice any funkiness:

https://ci.appveyor.com/project/blitzmann/pyfa/build/master-151/artifacts

If all is well, I'll release (another) point release in a few days time. :P

**Comment by HindenPeter** [comment]
Looks good from here!
