### ISSUE TITLE
Drone damage calculated wrong on VNI fits.

### ISSUE THREAD

**Issue by cat-evergreen** [pyfa-org/Pyfa#1215]
## Bug Report
Pyfa shows drone damage to be too low on VNI fits.

### Expected behavior:
VNI fitting should show about the same DPS in Pyfa as it should in the ingame fitting simulator.

### Actual behavior:
VNI shows only about 60% of the DPS.

### Detailed steps to reproduce:
1. Create the fit below  for a VNI:

2. DPS shows 481 DPS with All V character.

3. Import the fit into the ingame fitting simulator.

4. DPS shows about 670 DPS (with my not all V character)

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Vexor Navy Issue, 100mn]

Damage Control II
Drone Damage Amplifier II
Drone Damage Amplifier II
Drone Damage Amplifier II
Drone Damage Amplifier II
Omnidirectional Tracking Enhancer II

Large Shield Extender II
Large Shield Extender II
100MN Afterburner II
EM Ward Amplifier II

Drone Link Augmentor I
[Empty High slot]
[Empty High slot]
[Empty High slot]

Medium Anti-EM Screen Reinforcer II
Medium Anti-Thermal Screen Reinforcer II
Medium Anti-Thermal Screen Reinforcer II

Praetor II x5

### Release or development git branch? Please note the release version or commit hash:
1.29.3 Stable (Release branch)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by blitzmann** [comment]
Thanks for the report. Haven't looked into it yet, however want to comment on one thing:

> VNI fitting should show about the same DPS in Pyfa as it should in the ingame fitting simulator.

I don't like to rely on the in-game fitting screen or fitting simulator. There are known differences between the way CCP does things and the way every other third party fitting program does things. Just FYI that there could be known differences. That being said, such a large discrepancy is odd.

Can you do me a favor and start offlining modules in both eve and pyfa to try to figure out where the incorrect states happen? It'll help narrow it down some :)

**Comment by Ebag333** [comment]
Praetor base damage modifier is 1.68.

Ship/Skill bonuses are:
Heavy drone operation 25%
Drone interfacing 50%
Amarr Drone Spec 10%
Gallente Cruiser (hull bonus) 50%

That puts the total at 5.2 in Pyfa.  None of those have stacking penalties, so that's an easy calc, doing it by hand gives me 5.1975.

Checking the damage output (what you see in Pyfa), the volley (for one drone) is 333, and I manually calculate it at 332.64.  So far so good.  (If you calculate in the speed, it also matches.)

Now to add drone damage amps.  Here the math starts getting a little fuzzy because I'll be using rounded off values for stacking penalties.

1x DDA is a 20.5% bonus, so our volley number should be 400.8312.  Pyfa shows 401.

Second DDA is 20.5% * 86.9%, so our volley number should be 472.237274124.  Pyfa shows 472.

Third DDA is 20.5% * 57.1%, volley should be 527.5150082465848, Pyfa shows 527.

Fourth DDA is 20.5% * 28.3%, volley should be 558.1187914500104, Pyfa shows 558.

So the maths check out for pyfa.

After going back and rereading your post, I suspect I see why:

>DPS shows 481 DPS with All V character.
>Import the fit into the ingame fitting simulator.
>DPS shows about 670 DPS (with my not all V character)

481 isn't the right number for DPS.  With 5 drones, the DPS is 698 with an All V char.

So why are you getting a different number?  You have a target resist profile set.  If I apply the Blood Raider resist profile I get.....481.

In this case, both Pyfa and in game are correct.  In game is showing the raw DPS without the damage profile applied.  Pyfa is showing the actual DPS, after you apply the resists.

Solution: Right click the `Firepower` pane and set to `No Profile`.

**Comment by blitzmann** [comment]
@Ebag333 excellent write up, I forgot about target resists possibly factoring in - would definitely explain everything :)

@cat-evergreen if you can confirm setting target resist profile to No Profile fixes the issue, that would be great. Feel free to provide any more detail or questions if needed. :)

**Comment by cat-evergreen** [comment]
I can confirm that it was a problem with the selected resist profile.  

I was unsure if a resist profile was set, because the text (Effective), that is added to the pane header, is not very informative. I tried right-clicking to check for a resist profile, but I probably just right clicked the pane header instead of the pane body and therefore didn't find an option to set a resist profile.
The fact that the EHP pane header always has the (Effective) text makes it even harder to distinguish between raw Firepower and resisted Firepower.
Maybe a target resist profile display, similar to the incoming damage display in the EHP pane, could be added to make it more visible what kind of Firepower is shown.

**Comment by Ebag333** [comment]
I agree that it's not very good UI.  First, it's hidden, so most people have no idea that profiles exist (for damage or resist).  Second, there's no obvious indicator for resists.

It's been on my bucket list for a while now to add a button (so it's more obvious) for resists, and the same damage profile as what you see on damage for resists.

**Comment by blitzmann** [comment]
> The fact that the EHP pane header always has the (Effective) text makes it even harder to distinguish between raw Firepower and resisted Firepower.

Bit it doesn't always have the `(Effective)` label. That should only happen when there is a profile set. If you have "No Profile" set and it's still showing up, let me know as that could be a bug...

> Maybe a target resist profile display, similar to the incoming damage display in the EHP pane, could be added to make it more visible what kind of Firepower is shown.

It's been discussed, see #217. I had the same idea of adding the same type of thing under firepower that the resists have, however at the time I was very against anything that increased pyfa's minimum vertical size considering we're pushing up against the limits for 1366x768 screen resolutions, which is still something like 20% of users last I checked (it's popular for some older or lower-end laptops). Additionally, this information is only really useful if a target resist has been set, and wastes space otherwise. The mining panel also doesn't use it, and there's issues with resizing it IIRC. Alternative is the tooltip, which I totally forgot to implement. Should probably be there regardless lol.

I'll have to reconsider this now that we have the minimum and full pane options. I've been meaning to look into getting the panels to change and resize on demand, so maybe I can kill two birds with one stone. :D

As this isn't a bug, gonna close this issue. :)
