### ISSUE TITLE
Error when importing fittings from EVE-exported file

### ISSUE THREAD

**Issue by msrex** [pyfa-org/Pyfa#1231]
![pyfa-import-error](https://user-images.githubusercontent.com/2625328/27015589-79fa5786-4edf-11e7-9cef-efb3170c82cb.png)
## Bug Report
When importing all corporate fits from file created with EVE Fitting Export. See attached screenshot.

The export was done today, and the file contains 194 fittings.

It would be really great if I were told which entry contains the error (or at least which was the last processed one) so I can verify in the file itself whether / where the issue lies.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

File with fittings is attached.

### Release or development git branch? Please note the release version or commit hash:
pyfa 1.29.4

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
Tried pyfa -d in a command prompt but saw no output in terminal window.

[corp-fits-11JUN2017.xml.gz](https://github.com/pyfa-org/Pyfa/files/1066834/corp-fits-11JUN2017.xml.gz)

**Comment by Ebag333** [comment]
It does pause on the fit that it had issues with, see:
https://puu.sh/whCZw/9e510d0af2.png

So that at least gives you an idea of what the issue might be.

Seems that it's because it's a `Nefantar Thrasher`.

That's an easy enough fix (literally one line fix).  Pyfa just isn't aware that it's a skinned ship.  I'll have a fix for that soon (tm).

**Comment by Ebag333** [comment]
Fixed: https://github.com/Pyfa-fit/Pyfa-fit/pull/127

**Comment by blitzmann** [comment]
Thanks @Ebag333 :) I've included the fix you provided (minus the Miasmos changes - they are technically different hulls with different values for some of the attributes, and the `Miasmos Quafe Ultra Edition` is something pyfa has in it's limited issue collection). 

To elaborate for @msrex, CCP used to develop completely different ship hulls before they had proper "skinning" support, which would more or less be a copy of the original hull. Our solution from a few years ago was to map skinned ship to original hull. It seems that there are quite a few other ships that we initially forgot about, or possibly ones that were added later (the ones ebag added).

These old hulls are being phased out it seems (no longer published), and with the skinning support that EVE has now, hopefully we don't run into this issue again. Additionally, I've made it so that if we can't find the ship in the pyfa database for some reason, we skip it and continue on with the import. :)
