### ISSUE TITLE
Bug: Variations Of Command Processor produces wrong information

### ISSUE THREAD

**Issue by GatlerDos** [pyfa-org/Pyfa#1232]
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

## Bug Report
An unexpected behaviour occurs when viewing variations of Small/Medium/Large/Capital Command Processor I.

### Expected behavior:
Should display only the Command Processor I as its the only rig of its type.

### Actual behavior:
Displays a huge list of wrong sized and seemingly random rigs.

### Detailed steps to reproduce:
Put a Command Processor I on any capable ship and view variations.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Claymore, Public Claymore]

Shadow Serpentis Damage Control
Caldari Navy Power Diagnostic System
Caldari Navy Power Diagnostic System
Caldari Navy Power Diagnostic System

Corelum B-Type 50MN Microwarpdrive
Pithum A-Type Adaptive Invulnerability Field
Pithum B-Type Adaptive Invulnerability Field
Thukker Large Shield Extender
Thukker Large Shield Extender
Republic Fleet Target Painter

Shield Command Burst II, Active Shielding Charge
Shield Command Burst II, Shield Harmonizing Charge
Shield Command Burst II, Shield Extension Charge
Skirmish Command Burst II, Rapid Deployment Charge
Medium Remote Hull Repairer I
Heavy Missile Launcher II, Inferno Fury Heavy Missile
Heavy Missile Launcher II, Inferno Fury Heavy Missile

Medium Command Processor I
Medium Command Processor I

'Augmented' Hammerhead x5
'Augmented' Hobgoblin x5

Nanite Repair Paste x1000

### Release or development git branch? Please note the release version or commit hash:
Release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7

### Other relevant information:
Have a nice day

**Comment by blitzmann** [comment]
Thanks for bug report, and sorry for the delayed response. 

This issue was introduced when support for drone, fighter, and implant variations was added. These things don't technically have "variations" as defined in the database. The way it was developed was basically "If this item doesn't have variations, then try to get all items in the same group". This allowed us to develop a variations list with items that didn't have variations (such as drones).

The problem presents itself for the command rig because it also doesn't have any variants. There is no tech II version of it. Thus, it falls back to selecting all items with the same group as it (which is a lot of unwanted rigs).

The fix is simple enough - only do the group thing if the item in question is in the Drone, Fighter, or Implant category. Seems to work well after doing that. :)
