### ISSUE TITLE
Bug Report: Fit name with Unicode can't display correctly in keys on the graph window

### ISSUE THREAD

**Issue by cyb13** [pyfa-org/Pyfa#1240]
### Expected behavior:
Unicode in fit name display in graph window.

### Actual behavior:
Unicode characters displays as [THIS](http://i.imgur.com/AwponZo.png)

### Detailed steps to reproduce:
1. setup a fit named with Unicode
2. click window->graphs
3. Unicode characters display wrong

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Maelstrom, goons配置]

Damage Control II
Gyrostabilizer II
Gyrostabilizer II
Tracking Enhancer II
Power Diagnostic System II

Adaptive Invulnerability Field II
Adaptive Invulnerability Field II
EM Ward Field II
Large Shield Extender II
Large Shield Extender II
500MN Quad LiF Restrained Microwarpdrive

1400mm Howitzer Artillery II
1400mm Howitzer Artillery II
1400mm Howitzer Artillery II
1400mm Howitzer Artillery II
1400mm Howitzer Artillery II
1400mm Howitzer Artillery II
1400mm Howitzer Artillery II
1400mm Howitzer Artillery II

Large Anti-Thermal Screen Reinforcer I
Large Core Defense Field Extender I
Large Core Defense Field Extender I

### Release or development git branch? Please note the release version or commit hash:
PYFA Version 1.29.4

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by Ebag333** [comment]
Fixed in my fork:
https://github.com/Pyfa-fit/Pyfa-fit/pull/88

**Comment by cyb13** [comment]
@Ebag333 Thank you for your reply.

Actually I mean the key on the graph. To be more accurate, I changed the name of this issue.

**Comment by blitzmann** [comment]
The stack traces are already fixed in upstream from a few months back thanks to ebags work. 

@cyb13 As for the label in the graph... that is a matplotlib issue, not really a pyfa one. Something about the font matplotlib uses not supporting unicode (possible). It's unfortunate, but I haven't seen a way to fix it with my quick 10 minute Google search, and tbh it's a pretty low priority. Gonna close this for now as a `wontfix`, but I appreciate bringing it to my attention. If this starts affecting more users more often, I can take a deeper look.
