### ISSUE TITLE
Visual issue with character seleciton

### ISSUE THREAD

**Issue by malleusmintaka** [pyfa-org/Pyfa#1263]
## Bug Report
When having two or more fits open, selecting a character will make this character appear as the active character on every fit, while the actually selected character for the fit will apply its skills.

### Expected behavior:
Character selected for the fitting gets shown and it skills are applied

### Actual behavior:
Character selected on different fit gets shown, while skills of correct character are applied

### Detailed steps to reproduce:
Open (at least) two fits.
On fit 1, select character A. 
On fit 2, select character B.
Go back to fit 1, character B will appear as the selected character, although only the skills of character A are applied to the fit.
Click on character and select character B again to apply his skills to the fit.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
None, can reproduce 

### Release or development git branch? Please note the release version or commit hash:
1.30.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

**Comment by secondfry** [comment]
It's actually even worse. Activate 'Use global character', select some character and then navigate to another fit.

**Pyfa will use old character related to fit yet say that it uses global character.**

![Demonstration](https://i.imgur.com/TQmcoRd.gif)
https://i.imgur.com/TQmcoRd.gifv

**Comment by blitzmann** [comment]
Just to be clear, this only relates to the global character option, correct? It works fine when that option is not selected?

Additionally, if you go back and switch the character, it does seem to reset.

Thanks for the bug report - will look into it :)

**Comment by malleusmintaka** [comment]
correct, only when global character is selected

**Comment by blitzmann** [comment]
So this turned out to be pretty simple. A few months back I implement a form of caching on fits so that when you switch to a fit it didn't re-calculate if it didn't need to (ie: another fit didn't modify it's stats). However, I never reset that calculation flag when the global character and the fitting character were mismatched (so a fit that was calculated under All 5 we never recalculated after switching to All 0 from another fit).

592f9a2298d2a should work to fix this, I'll test it out a bit more tomorrow. I also realized that global character (probably) doesn't work for projected and command fits through another fit - we only set the character on the "prime" fit and don't propagate through. Will have to take a bigger look at that later since it won't be as easy of a fix.
