### ISSUE TITLE
Showing Normal section of modules when other empty

### ISSUE THREAD

**Issue by SubjectXXX** [pyfa-org/Pyfa#1306]
## Bug Report
Not really a bug, but improvement.

When I have selected Faction/Complex/Officer section in market tab on a module, If I select different module from market tab and that module doesnt have Faction/Complex/Officer variant, it shows blank box for selecting different variants of module instead of switching back to Normal section which always has a variant of a module.

**Comment by blitzmann** [comment]
This used to be the case a while ago, then someone submitted a pull request to remember the user's meta group selection. unfortunately it has this side effect. Shouldn't be too difficult to say "if not normal and number or items == 0 then set to normal", but I'd have to take a look at the code. Either that or make the remember a user setting in preferences

**Comment by SubjectXXX** [comment]
Well, remembering last selected group is fine and I would keep it that way, just adding this fallback if list is empty. If he clicks other module that had meta tab populated, I would retain that automatic selection of tab, even if the normal was selected one click before. In other words, normal should be selected programatically without changing remembered last selected meta tab.

**Comment by blitzmann** [comment]
It's been a while since any activity on this issue. I don't think this would be too terribly difficult to fix or implemented, but it would take some time to research and delve into the black abyss that is the market browser code. Tagging this as `help wanted` as I believe it's low-hanging enough for someone interested to pick up on it if they can get around to it before I do. 😄

**Comment by thauser** [comment]
Which is the PR that was merged that remembers the group selection?

**Comment by blitzmann** [comment]
Uh... I think nit was #913

**Comment by burnsypet** [comment]
I had a play around with the meta buttons code this afternoon and I can resolve this. Just want to check what the desired solution should be.

For example, if I move from a category with 'Officer' enabled and selected to a category that does not have Officer enabled, currently no categories will be selected. In this scenario I can make it so that:

- The first enabled category in the buttons is enabled (left to right, so it would probably always be 'Normal' unless 'Normal' is disabled eg. faction ammo only has 'Faction')

Or

- All enabled categories are selected

**Comment by DarkFenX** [comment]
I am implementing fix for this in market_metagroups branch. See #1868 for discussion.

**Comment by DarkFenX** [comment]
Closing as duplicate
