### ISSUE TITLE
pricing pane was not updating.

### ISSUE THREAD

**Issue by JeremyCooper** [pyfa-org/Pyfa#1307]
None of the price readouts were updating, all simply stayed at 0 isk. I tried poking around in the preference pane (which was cut off short, see #1183), but changing price information location had no effect. Neither did opposite clicking on the price readout and clearing the price cache.

Was able to get price data only after switching, in the preferences menu, from evecentral to eve-marketdata THEN opposite clicking the price readout and clearing the cache.

####
Arch Linux 64bit, openbox window environment
Installed through the aur pyfa package.

**Comment by blitzmann** [comment]
Hey there,

So, AFAIK, eve-central has been down for a while due to a server move. I'm not sure when / if it's going to come back up, and am monitoring it's status to determine if I should just remove it. Because of this, users were getting price = 0 for pretty much everything. This is why I added eve-marketdata as a source.

As for the prices still not updating after switching, they wont. pyfa caches prices for a period of 24 hours (IIRC), so if you get a bad response from the server and the price ends up being 0, it won't refresh until 24 hours have passes (or, like you found out, resetting the price cache to force reset and fetch prices). Might be a good idea to clear the cache whenever the price source changes, I'll look into that. :)

**Comment by Tolbin** [comment]
I can't get prices to update. I set eve-marketdata as source in options and reset the price cache but still stuck on updating prices. Looking at saveddata.db/prices all the prices are "0" and failed column is "{null}". Tried manually truncating the prices table but same issue still.

**Comment by blitzmann** [comment]
> I can't get prices to update. I set eve-marketdata as source in options and reset the price cache but still stuck on updating prices. Looking at saveddata.db/prices all the prices are "0" and failed column is "{null}". Tried manually truncating the prices table but same issue still.

If you switch to eve-marketdata and reset price cache, it should work (should work even if you have eve-central, as 1.34 introduced fallback mechanism to try to find a source that works shoud the preferred fail)

Try again, if it's still not working, I would look at things such as firewalls (especially if you're on a work computer / behind a corporate VPN)

**Comment by Tolbin** [comment]
Yeah not sure what's happening. Maybe a problem with the handshake? Seems to try eve-marketdata.com and then fallback to eve-central.com

https://imgur.com/a/E3xmL

**Comment by blitzmann** [comment]
Handshake failure? Can you access the API directly through the browser? 

https://eve-marketdata.com/api/item_prices.xml?type_ids=16267

The cert is valid for me. If you're having an issue, I would check on another computer on another network and see if you're still having issue. Handshake failures can happen within certain fire-walled networks, especially if they are inspecting SSL traffic.

Otherwise, I have no idea why this might be happening.

**Comment by Tolbin** [comment]
Turned out to be a problem with the libgnutls version I was using. Updated it and now prices work fine. Sorry for the bother and thanks for the assistance.

**Comment by blitzmann** [comment]
Huh, interesting. Glad you were able to get it working! Hopefully if someone with the same issue searches for this your solution will pop up :D

**Comment by aflyhorse** [comment]
Hi developer,
It seems eve-central might not able to come back again.
https://evemarketer.com has a set of compatible API for eve-central at https://api.evemarketer.com/ec/, is it possible to add it as an alternative?
Cheers,

**Comment by blitzmann** [comment]
Closing this. eve-central is dead, pyfa can now use either eve-marketdata (which seems like it's having it's own troubles keeping afloat), and evemarketer (@as per @aflyhorse's suggestion).

I also need to evaluate if we should just simply switch over to EVE's ESI market endpoints. But that's a discussion for another thread.
