### ISSUE TITLE
Throws error upon creating or opening Victor or Virtuoso fit

### ISSUE THREAD

**Issue by x3n0ph0n** [pyfa-org/Pyfa#1310]
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

## Bug Report
OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.32.0 Stable    - YC119.9 1.3
pyfa root: D:\Sturf\pyfa
save path: C:\Users\david\.pyfa
fs encoding: mbcs

EXCEPTION: unsupported operand type(s) for -: 'int' and 'NoneType'

  File "D:\Sturf\pyfa\library.zip\gui\statsPane.py", line 75, in fitChanged
    view.refreshPanel(fit)
  File "D:\Sturf\pyfa\library.zip\gui\builtinStatsViews\resistancesViewFull.py", line 183, in refreshPanel
    resonance = (1 - fit.ship.getModifiedItemAttr(resonance)) * 100

OS version: 	Windows-8-6.2.9200
Python: 	2.7.10
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.0.0
pyfa version: 1.32.0 Stable    - YC119.9 1.3
pyfa root: D:\Sturf\pyfa
save path: C:\Users\david\.pyfa
fs encoding: mbcs

EXCEPTION: unsupported operand type(s) for -: 'int' and 'NoneType'

  File "D:\Sturf\pyfa\library.zip\gui\statsPane.py", line 75, in fitChanged
    view.refreshPanel(fit)
  File "D:\Sturf\pyfa\library.zip\gui\builtinStatsViews\resistancesViewFull.py", line 183, in refreshPanel
    resonance = (1 - fit.ship.getModifiedItemAttr(resonance)) * 100

### Expected behavior:
Create or open Victor or Virtuoso fit

### Actual behavior:
Give error message

### Detailed steps to reproduce:
1. Go to Force Recon or Stealth Bomber section of Fittings window
2. Click create fit on Victor or Virtuoso
3. Hit accept or enter

### Release or development git branch? Please note the release version or commit hash:
Release version 1.32.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by blitzmann** [comment]
Hey there, thanks for letting me know about this.

Are these ships even in the game yet? The reason I ask is because I get pyfa's data directly from the game, and it seems that these ships are missing many attributes that are normally attached to hulls (for example, resists, which is what this error is complaining about)

![image](https://user-images.githubusercontent.com/3904767/31301012-06987150-aac5-11e7-89f2-6e84cf77e945.png)

If they are not in the game, there is not much I can do at the moment. If CCP has releases the stats somewhere on the forums, you could always modify an existing (complete) hull to match the attributes using Attribute Overrides, but the effects (eg, ship bonuses) won't be editable.

**Comment by blitzmann** [comment]
Closing this as I will keep up with it in #1323
