### ISSUE TITLE
Signature Resolution on Turrents

### ISSUE THREAD

**Issue by TxTBone** [pyfa-org/Pyfa#1314]
# Submit a bug report bug report or feature request

Here you can inform pyfa developers of potential bugs or suggest features / improvements to the project. Please check
to make sure that the bug hasn't been reported or feature requested before submitting. If you have general questions
about the project and want to reach out to the developers personally, please check out out our [Slack]
(https://pyfainvite.azurewebsites.net/).

---

## Bug Report
Signature Resolution data for turrets is all 40000, regardless of size/type.  Have not checked for drones.
I checked issues and did not find anything when searching signature resolution.

### Expected behavior:
Signature resolution numerically increases for larger turret weapons (worse resolution typically a higher value).

### Actual behavior:
All resolution data seems to be constant at 40000.

### Other relevant information:
You folks are FANTASTIC - the tool is WONDERFUL!!!  Thank you for all your hard work.

**Comment by blitzmann** [comment]
That is very odd... I wonder if CCP changed these around? that data is usually directly from CCPs data. Will have to double check.

Thanks for the report!

**Comment by blitzmann** [comment]
So, quick check on SISI shows that sig res is, in fact, 40,000 for all weapons.

Additionally, doing a cursory search on google jogged my memory on how this all works. Signature Radius used to be different for all turrets, but then CCP reworked it for performance gains. I can't find any hard information on the change, but from what I remember it worked something like this: instead of doing a calculation that involved a guns sig res and tracking speed, CCP simplified it to one variable. When they did this, they modified all the sig radius to 40k, but then adjusted the tracking speed so that the result was asthmatically the same.

For example, a Dual Anode Light Particle Stream used to have a sig res of 40 and a tracking speed of 0.117 rad/sec. It now has a sig res of 40k and a tracking speed of 117 (I think it's millirad/sec now). So basically, instead of CCP having to get two attributes from the gun to make the calculation, they have a constant (40,000) and adjusted the tracking to match (in this case, sig res went up x1000, and so did tracking to compensate). The end result is the same, but they save in computing resources.

Hope that clears it up. Signature Resolution on turrets hasn't been a thing since circa 2016. :)

**Comment by TxTBone** [comment]
Thanks for your investigating this!  I apologize for my ignorance in CCP's
calculations.  I will pass this along.

Keep up the GREAT work!!!
