### ISSUE TITLE
energyWarfareResistance applied twice

### ISSUE THREAD

**Issue by ibudnikov** [pyfa-org/Pyfa#1315]
## Bug Report
energyWarfareResistance parameter calculated correctly, but applied twice.
One place is eos/saveddata/fit.py, line 1197. Have no idea, where is other.
### Expected behavior:
Capacitor "-" should be 46.1
### Actual behavior:
Capacitor "-" is 23.2
### Detailed steps to reproduce:
energyWarfareResistance of one battery is 25%. Ship's energyWarfareResistance: 1-0.75*(1-0.25*0.869)*(1-0.25*0.571)=49.6 %. That value is calculated correctly.
Apply 1 Capital Energy Neutralizer II against this fit. Capital Energy Neutralizer drains 4400/48=91.7 GJ/s, and after the resist it should be 91.7 * 0.503 = 46.1. 
But looks like resist applied twice: 91.7 * 0.503 * 0.503=23.2 is shown.
### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Revelation, Revelation]

[Empty Low slot]
Imperial Navy Capacitor Power Relay
Imperial Navy Capacitor Power Relay
Imperial Navy Capacitor Power Relay
Centum B-Type Energized Adaptive Nano Membrane
Centum B-Type Energized Adaptive Nano Membrane
Centum B-Type Energized Adaptive Nano Membrane
Centum B-Type Energized Adaptive Nano Membrane

Capital Cap Battery II
Capital Cap Battery II
Capital Cap Battery II
Imperial Navy Cap Recharger

Siege Module II
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

Capital Capacitor Control Circuit II
Capital Capacitor Control Circuit II
Capital Capacitor Control Circuit I

Projected:
Capital Energy Neutralizer II
### Release or development git branch? Please note the release version or commit hash:
Latest release (1.32)
### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 8.1

**Comment by burnsypet** [comment]
Looking at this now, there's definitely something going on here.

When entering eos.saveddata.fit.addDrain the capNeed has already been modified by the resistance and reduced from 4400 to 2114, but it is then multiplied by the resistance again reducing it to 1114 which is the amount used in the calculation and displayed on the capacitor view. 

This seems to have happened because the energyNeutralizerFalloff effect has been applied first, which also has the effect of modifying the amount by the resistance. Having a resistance calculation in here is probably redundant now that there is a separate effect for it, and the same problem is present in energynosferatufalloff. Will make a pull request tomorrow but if you want to fix it locally just comment out lines 16+17 of eos/effects/energyneutralizerfalloff.py

**Comment by ibudnikov** [comment]
Thanks very much.
