### ISSUE TITLE
Caiman & Komodo not applying Gallente Dread/Titan skill bonus

### ISSUE THREAD

**Issue by Wigster30** [pyfa-org/Pyfa#1320]
# Submit a bug report bug report or feature request

Hi,

The newly introduced Caiman Dreadnought doesn't take into account the Gallente Dread skill level when applying the damage bonus to XL Cruise, XL Torps & Torps

https://puu.sh/y7D1V/38c930d2c9.png

**Comment by Wigster30** [comment]
Also,

The damage bonus to the Komodo Titan isn't applying the Gall Titan skill either.

**Comment by Jakamo** [comment]
I'm getting the same bug where Komodo damage bonuses are not applied properly. Currently getting significantly less damage than a Levi with identical fit & no fibos.

**Comment by burnsypet** [comment]
As far as I know all the ship/module data is held in a database that comes along with your build of Pyfa and is generated when the build is made. I'm not really sure how the database is produced but it looks like something went wrong with the new Guristas caps... the FAX doesn't even seem to have a Gallente skill requirement.

I think this is one for @blitzmann

**Comment by Wigster30** [comment]
The FAX ingame doesn't have the gall carrier as a req, yet the other new gurista caps do have the relevant Gall cap skill as a req.

**Comment by blitzmann** [comment]
Hey all,

Remember when checking to see if something is applied to a charged module (specifically missile-based), check the Affected By tab on the charge itself. That is usually with where the modification is applied, not to the launcher. Just a helpful tip :)

It's funny because this is related to the cause of these bugs - the effects are using `filteredItemBoost` instead of `filteredChargeBoost`, basically trying to modify the module instead of the charge. Effect files are usually generated by a script that I run, which is about 80% accurate (made up statistic), and I do a once over. But things like this slip by and sometimes require a manual intervention to fix.

There also seems to be an EVE-related bug for the Komodo. it has two effects for the Gallente Damage Bonus: `shipBonusTitanG2AllDamageBonus`, and `shipBonusTitanG1KinThermDamageBonus`

`shipBonusTitanG1KinThermDamageBonus` seems to be applying the 50% bonus to Kin and Thermal damage, as it should. However, `shipBonusTitanG2AllDamageBonus` is defined as applying the 40% bonus to Therm, Exp, and EM, meaning that *thermal may be getting both bonuses*. I can't confirm that this is true in the game, but that's how the effects are defined currently. I'll be reaching out to CCP about this potentially serious issue.

**Comment by blitzmann** [comment]
Also, in the meantime until I hear back from CCP, I'm going to go and define the effects as they are and just fix the pyfa-related bugs. It's currently building, but once it's done an updated windows build can be found here that includes these fixes:

https://ci.appveyor.com/project/blitzmann/pyfa/build/133bugfixes-301/artifacts
