### ISSUE TITLE
[Feature] Alpha Clone skill level enhancements.

### ISSUE THREAD

**Issue by BartMassey** [pyfa-org/Pyfa#1350]
Use case: I'm building a fit for some random-race Alpha clone. I'd like to be able to evaluate the fit against the clone's skills (a) just after the tutorial, (b) with max Alpha but no Omega-trained skills, (c) with max Alpha + Omega-trained skills.

I don't understand the post-December 2017 Alpha stuff. Are the racial skills even different anymore?

I've read Issue #863 — Have verified I can make a copy of the All Vs character and then set it to Alpha Clone to get a max Alpha. Not sure whether this is case (b) or (c) above, though? (Also, why should I have to make a copy? Shall I file a separate issue for this?) Sadly, that leaves (some) two out of three of the use cases above uncovered.

Let me know how you might want to proceed on this. If it involves just manually creating some new character sheets, I can do the research and provide them.

**Comment by blitzmann** [comment]
Sorry for the late reply, this got lost with the holidays lol

There's a lot of questions in this, so hopefully I can address each one.

> Are the racial skills even different anymore?

As I understand it, no, the skills are all the same no no matter the characters race, hence why pyfa now only has "Alpha" clone instead of "Amarr Alpha", etc..

> Not sure whether this is case (b) or (c) above, though? 

Copying All 5 and applying an alpha state would be the same as (c). However, there is no real difference between b and c - if you have a maxed character but it's in "Alpha" state (c), it would be functionally the same as (b).

> Also, why should I have to make a copy? Shall I file a separate issue for this?

Simply because that is the easiest way of obtaining a character in pyfa that is a maxed "Alpha" character. I could add a button that says "Create Alpha character" and just give it the skills of an alpha, but that comes with it's own drawbacks (such as if the alpha skill list changes - currently that is automatically applied to existing characters and no intervention is required by pyfa users. If you had a literal character saved with literal alpha skills, that wouldn't be updated and they could potentially have incorrect alpha skills)

It's best to think of Alphas as a skill cap on an existing character, rather than their own separate character
. I understand that for the purposes of fit doctrine management this can be a bit more of a pain, but for the majority of users they just need to apply the Alpha skill cap by selecting it in the drop down.


> I'd like to be able to evaluate the fit against the clone's skills (a) just after the tutorial,

This has been discussed before - adding newbie character sheets per race. It's always been my opinion that this should be handled by something like EVEmon, since a dedicated skill management program is much more capable and up to date with that kind of stuff. Simply create newbie character and export theior skill sheet to import into pyfa. That being said, I understand that EVEmon may or may not be dead, so there may be a problem with that.

Nevertheless, I still don't like the idea of having default newbie characters. The majority of pyfa users would not need it (only those looking to help train newbies or those that manage corp fittings and the like), and it would be a nightmare to keep the definitions of those sheets up to date if they should change (default characters live in the user database, which is trickier to touch between updates). You may argue that those definitions can live in the eve database, and thus get updated whenever we make a build (which is another problem - I don't think there is an official data source to get which skills are applied to new characters), but then that would be implemented in a system much like the alpha clones - some sort of override / skill replacement (you would create a character, and tell pyfa to apply this built in character sheet to it). It can get messy that way.

I see the appeal in having newbie skill sheets though. I would rather have the list set up in pyfa, exported, and then those sheets stored on the GitHub wiki for others to be able to get to and import themselves if they have need of it. 

As always, open to ideas on any of this :)

**Comment by BartMassey** [comment]
Thanks much for the detailed reply! Your positions all make fine sense. I *would* like to have a canonical source for Pyfa-formatted character sheets for standard configurations, and I would love it even more if somebody not me kept them up to date :-) . That said, whatever works…

I've been using the All-0s character as a stand-in for new characters when fitting. It *kind of* works, but it's not ideal.

I'll try to figure out what I can do. Again, thanks.

**Comment by blitzmann** [comment]
> I would like to have a canonical source for Pyfa-formatted character sheets for standard configurations

As said, unfortunately I don't think CCP provides this in their static dumps (and even looking through the client data dumps that pyfa runs off of, I don't see that information). But if someone gets together a list of skills and skill levels each race starts with, I could absolutely put that on the wiki and link to it from somewhere on the character editor.

if you can get that list of skills for me for each race, I can mock up a few sheets that can be imported :)

**Comment by blitzmann** [comment]
https://github.com/pyfa-org/Pyfa/wiki/Starting-Character-Skills

Just went through and created new characters on a test account to import into pyfa, and get the latest values. Can't guarantee that it will remain up to date, but there it is :)

Gonna close this issue

**Comment by blitzmann** [comment]
> I'm not playing EvE anymore

Story of my life! haven't played for three years, actually just now dabbling back in a little bit because a coworker is trying to get into it.

Thank you for the kind words, take care in your future endeavors!
