### ISSUE TITLE
Power Bonus for Micro Auxiliary Power Core not scaled in Module Attributes

### ISSUE THREAD

**Issue by BartMassey** [pyfa-org/Pyfa#1357]
### Bug Report

When viewing Module Stats > Attributes for a Micro Auxiliary Power Core, the Current Power Bonus is shown to be the same as the Base Power Bonus, regardless of the current character's Power Grid Management Skill.

I *think* this is not the intended behavior?

### Expected behavior:

Displayed Current Power Bonus is 1.25x Base Power Bonus for a character with Power Grid Management V.

### Actual behavior:

Displayed Current Power Bonus is the same as Base Power Bonus.

### Detailed steps to reproduce:

Fit a Punisher with a Micro Auxiliary Power Core II. Set Character to All Vs. Open Module Stats > Attributes on the Micro Auxiliary Power Core II.

### Release or development git branch? Please note the release version or commit hash:

pyfa 1.34.0 Stable

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Debian Linux Stretch

### Other relevant information:

N/A

**Comment by blitzmann** [comment]
Hey Bart. The `Power Grid Management` skill only affects the hull's power output, not the various modules that can modify it, thus the Micro Aux Power Core is not affected and remains at it's base value.

Hope that helps :)

**Comment by BartMassey** [comment]
Thanks for the quick response!

Not sure if I follow the logic here. Pyfa shows turning on a Micro Auxiliary Power Core II on an otherwise empty Punisher takes the grid available to an all-Vs character from 83.75 MW to 98.75 MW, a difference of 15 MW. If I look at the stats, the module tells me it is giving a Power Bonus of 12 MW current. I think the extra 3 MW has to be credited to applying the stats bonus of 25% to the 12 MW module, no? Or do I misunderstand how the Current values are computed in general?

**Comment by blitzmann** [comment]
Ah, thanks for the clarification. I had to dig a bit deeper to get a better answer for you, there's a bit more going on here.

For reference:
Base Punisher power: 67 MW
Skill +25%
MAPC II +12 MW

The Skill is applied as a `boost` (percentage) modifier, whereas the MAPC is applied as an `increase` modifier, meaning it's a simple addition to the current value. `increase` modifications can be either `pre` or `post`, meaning that they get applied before or after other modifications (the vast majority of increase modifiers are `pre`). So in this situation, the increase happens before other calcs:

```(67MW + 12MW) + 25% = 98.75```

It does not work like this:

```(67MW + 25%) + 12MW = 95.75```

That is where the additional 3MW comes from. It's an artifact of the `increase` being done before the `boost` modification, inflating the final value, not because the MAPC is being modified by the skill. It is a bit confusing because these nuances in the calcs aren't very intuitive.

Hope that helps better, please feel free to reply with more information if something still seems off :)

**Comment by BartMassey** [comment]
I would truly *love* to have the chain of calculations that led to a particular value. I find myself doing these kinds of calculations all the time in my own software and using Pyfa to check them, which is awesome, but it would be even better if Pyfa just told me what to write. :-)

It would also be nice to have a quick way to see what order the stacking penalties are being applied in, and what they apply to, as long as I'm dreaming.

I guess I figure that due to the distributive law of multiplication, it would be ok to have a pre-increase tracked as a percentage increase: (65 + 12) * 1.25  = 65 * 1.25 + 12 * 1.25. But as I think about it it would probably be hard to keep track of because of the order of operations.

Again, thanks for the clarifications!

**Comment by skyride** [comment]
@BartMassey you can always use pyfa's fitting engine Eos to do the calculations if it's python applications you're building. :)

https://github.com/pyfa-org/eos

**Comment by blitzmann** [comment]
Just an fyi, thats not the same eos pyfa uses. It's an engine that was
being developed by kadesh for a pyfa rewrite. Im not sure of the status of
it, but last i l ew it was still missing some functionalities like
ganglinks, new fighter mechanics, etc. It's not production ready methinks.

**Comment by blitzmann** [comment]
Closing this as it was clarified, new issue created for researching feasibility of the discussed feature. :D

**Comment by BartMassey** [comment]
Thanks!
