### ISSUE TITLE
[Feature] Close All Fits

### ISSUE THREAD

**Issue by BartMassey** [pyfa-org/Pyfa#1359]
I adore the "Open Fits In New Window" configuration option. It would be nice to be able to close the 15 fits I've piled up over several sessions in one click instead of individually, though.

Maybe this is already available, but I can't seem to find it.

Thanks as always for your work on Pyfa!

**Comment by blitzmann** [comment]
This is a good idea. The only question is where to put it. I've tried to avoid context menus on the tabs, but it might be time to look into that. :)

**Comment by BartMassey** [comment]
You could put a "-" next to the "+" control in the tab panel. Kind of error-prone, though. :-) Maybe clear over on the right side of the tab panel.

**Comment by blitzmann** [comment]
Could do that, but that clutters up an area already prone to cluttering. 

If anything a context menu seems to be the way forward - there's a few other functions I can do with that (close all of this hull, send fit to active projected/command, etc). The challenge is that the tabs code should be kept clean of any pyfa-specific things (like our context menu implementation), because it's one of those things that was designed to be able to be used in different projects (I know of two other projects that use chrome tabs from pyfa specifically that have nothing to do with pyfa). So I'll have to looks to see if there is a way I can register a context menu with tabs and keep is separated. :)

**Comment by burnsypet** [comment]
![image](https://user-images.githubusercontent.com/6990224/35328596-c922fab2-00f4-11e8-924c-7208ecc9eba4.png)

I've been able to implement this as a context menu just by inserting the code directly into chromeTabs.py but like you mention it clutters it up a bit. Will experiment with keeping it seperate but I'm not sure I know enough about the framework to make it happen.

**Comment by blitzmann** [comment]
@burnsypet excellent! If you can figure out how to separate it, that would be ideal (might be able to register some sort of callback to the notebook / tab container), but I agree it's not a trivial task. If we can't figure that piece out, then I'm good with this solution in the interim - feel free to submit a PR against the development branch!

**Comment by BartMassey** [comment]
Nice! Thanks huge for working on this.

**Comment by blitzmann** [comment]
Please, @burnsypet, you're my only hope (to avoid looking into this myself 😛)

**Comment by DarkFenX** [comment]
Ctrl-Alt-W or File menu item does this for a few releases.
