### ISSUE TITLE
CREST connection from behind proxy gives SSL error

### ISSUE THREAD

**Issue by mstrkingdom** [pyfa-org/Pyfa#1364]
## Bug Report
Attempting to connect with CREST from behind a proxy results in SSL CERTIFICATE_VERIFY_FAILED error.

### Expected behavior:
API connection made

### Actual behavior:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

### Detailed steps to reproduce:
Launch pyfa
From the CREST menu, select "Login to EVE"
In the new browser window, login with EVE credentials if needed
Click 'Authorize' button

### Release or development git branch? Please note the release version or commit hash:
pyfa 1.34.0 Stable

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
Behind a corporate proxy at work.  I believe the fix is to set `session.verify = False` in the requests session in the `APIConnection `class.  Because that can potentially be unsafe, I tinkered around with adding a checkbox in the network settings to enable/disable the verify but it was a pretty basic effort as I'm unfamiliar with the pyfa environment/architecture.

**Comment by blitzmann** [comment]
Yeah, this is most likely due to SSL inspection on corporate networks. Not much we can do except to ignore cert checking as you suggest. If you have a fix by adding that checkbox, feel free to submit a PR for it! 

I would warn though that the CREST stuff is going away in a few months, so if it's specific to CREST / XML API connections it may need to be re-implemented with the new stuff depending on how that works out (which I'm working on - have a decent idea on the replacement, but need to flesh out a few more things before I continue development on it).

**Comment by blitzmann** [comment]
I'm going to close this as it's not something busted in pyfa, and the overall EVE integration will have to be analyzed once we switch over to ESI which is currently in the design phase. :)

Again, PR is always welcome if you want to submit one, but it may be moot with new mechanisms coming in the following months
