### ISSUE TITLE
Feature Request: Add Capacitor Delta to Stats Pane

### ISSUE THREAD

**Issue by alexanderdarino** [pyfa-org/Pyfa#1370]
In the Capacitor section, the Cap production/consumption info can be moved a bit to the left to a middle column so that a new right column can be added to show the capacitor delta (production minus consumption). Alternatively, the Capacitor Delta can be shown beneath the capacitor consumption. Mental math is great and all, but any precious seconds we can reclaim in our lives make it all the more worthwhile.

![image](https://user-images.githubusercontent.com/671964/35768863-526af5d0-08d0-11e8-9876-62686eb07bba.png)

**Comment by blitzmann** [comment]
I can get behind this :)

**Comment by burnsypet** [comment]
Have added this in my local version:

![image](https://user-images.githubusercontent.com/6990224/36254163-e638517a-1241-11e8-8f0d-d54e8541a8e9.png)

Can't really find any suitable image in the package at the moment so might have to add a new one.

**Comment by blitzmann** [comment]
Excellent work @burnsypet!

It looks a but cluttered though... Just throwing some thoughts out:

* Instead of having an image for it, why not simply have it in parenthesis and remove some redundancies (instead if `[image] + 4.24 GJ/s` do simply `Δ+4.24`)(and yes, we can support displaying unicode characters)
* We can also hide some of the current information. For example, keep the delta stat on the panel, and hide the absolute + / - in a tooltip for the delta. I don't know if I like this too much, as it changes the default that every one used to, but I have to ask - is it really necessary on a regular basis to know the + / - of cap?
    * Or, you can hide the delta in a tooltip for the current UI. I like this even less

Thoughts on any of the above? I absolutely think we should have the delta, it's just a matter of how to display it with the limited space we have.

**Comment by Ebag333** [comment]
This was done back in 2016.

https://github.com/pyfa-org/Pyfa/pull/812#issuecomment-261167847

**Comment by blitzmann** [comment]
Ah, I forgot the delta was to be included with that PR. I still want to evaluate it believe it or not, especially now that pyfa is migrating to pyinstaller which will make it much easier to include those extra dependencies (the old mac client was a real bitch about this, I don't remember specifically what the issue was, but I could not get it to run with that PR)

@burnsypet any news / comments on my previous comment?

**Comment by blitzmann** [comment]
@burnsypet sorry, forgot about this! Hmm, seeing them side by side like that makes it tough to determine which one is better. The second one, part of my suggestion, doesn't look nearly as good as I would have thought lol. Honestly I think I could like the third option where the absolute values are in a tooltip. I don't know of a reason why folks might need that information right off that bat, and if they do need it, it can be easily accessed.

@DarkFenX , you've got a lot more experience with theorycrafting than I do and have a better beat on what information may be more useful, any suggestions?

**Comment by DarkFenX** [comment]
Readout was changed, see #1997
