### ISSUE TITLE
Agency Boosters not having any effect on stats

### ISSUE THREAD

**Issue by jlatour88** [pyfa-org/Pyfa#1379]
## Bug Report
Agency booster drugs have no effect on stats

### Expected behavior:
boost of Armor & Shield rep amount, power, ect

### Actual behavior:
Does not add any boost or any seen effect

### Detailed steps to reproduce:
open any fit, add agency booster, online and offline to find no stats are changing

### Release or development git branch? Please note the release version or commit hash:
1.34.0 Stable

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
reproduced from another member on version 1.33.2 Stable using the old name agency tank booster as well

**Comment by blitzmann** [comment]
They all seem to work for me. Can you give me a fitting, the exact booster you're trying to use, and the expected value vs the value pyfa shows?

As an example, you can see that my small shield booster here is getting it's 3% boost from the TB3 booster

![image](https://user-images.githubusercontent.com/3904767/36065858-9d65394e-0e6e-11e8-8900-9934758d8ee1.png)

**Comment by jlatour88** [comment]
Im using a concord capital Shield booster. and id rather not share this fit for obv reasons

**Comment by jlatour88** [comment]
hmm it doesnt seem to have an effect on capital mods on sisi however there is no mention of it not working for cap sized mods on the description. iv sent a ticket to CCP to find out if this is intentional or not. il reply when i have an answer

**Comment by blitzmann** [comment]
If the full fit is protect, I would recommend a stripped down version that simply shows the problem at hand. Just for future reference. That being said, knowing it's a capital module is a clue, since they are targeted differently than other shield boosters.

Have you tested this booster in game / SISI to ensure that capital modules are actually affected by this booster? Taking a look at the effect itself, it doesn't seem like those are applied to capital modules. Whether or not this is intended is a question for CCP, sometimes they forget to turn things like this on for capital modules.

**Comment by blitzmann** [comment]
Seems you beat me to it. :)

I can also ask CCP Larrikin to check for me

**Comment by jlatour88** [comment]
I did test on sisi and it doesnt work on sisi either. So maybe an oversight from ccp about forgetting to update the description because im hearing it used to work. But still will wait for CCP to give me a definitive answer if its a bug or intentional.

**Comment by blitzmann** [comment]
I'm going to flag this as working as intended. I haven't heard back from CCP yet either, but if you get a response to your bug report, feel free to reopen / create a new issue :)
