### ISSUE TITLE
New Standup modules don't seem to be implemented

### ISSUE THREAD

**Issue by lunedis** [pyfa-org/Pyfa#1387]
## Bug Report
The new patch had lots of changes to Standup modules, most of which don't seem to be implemented.

Standup Capacitor Power Relay I and II cannot be fitted. (nothing happens when trying)
Standup Cap Battery I and II cannot be fitted. (nothing happens when trying)
Standup Layered Armor Plating I and II cannot be fitted. (nothing happens when trying)

Changing the script of a Standup Focused Warp Disruptor does not change range.

Burst Projectors cannot be activated (would be helpful to determine capacitor usage)

Standup Focused Warp Disruptor and Stasis Webifier show too high capacitor usage (reactivation delay is not considered).

Fitting a "Standup L-Set Target Acquisition Array" does not increase targeting range on Fortizar.

RoF and capacitor bonus of e.g. Fortizar not implemented.

### Release or development git branch? Please note the release version or commit hash:
YC120.2 1.1 - v1.35.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7

**Comment by blitzmann** [comment]
> The new patch had lots of changes to Standup modules

Yeah, so this is apparently the memo that I missed. :( My diff script doesn't seem to have picked up the changes, or maybe I just fumbled the diff script.  ¯\_(ツ)_/¯

Going through now to figure out what needs to be done and the extent of the changes. Thanks for the report!

**Comment by blitzmann** [comment]
@lunedis https://ci.appveyor.com/project/blitzmann/pyfa/build/bug/citadels-397/artifacts Please take a look at this build and see if you can poke holes in it. if everything seems okay, I'll be set to do a point release tomorrow

**Comment by lunedis** [comment]
Quick look:

Adding a Standup Cyclops I to a Fortizar: 

```
OS version: 	Windows-7-6.1.7601-SP1
Python: 	2.7.14
wxPython: 	3.0.2.0
SQLAlchemy: 	1.0.5
Logbook: 	1.2.1
pyfa version: 1.35.0 Stable - YC120.2 1.1
pyfa root: C:\Users\Kalu.Kalu-PC\Documents\EVE\pyfa-test
save path: .
fs encoding: mbcs

EXCEPTION: 'NoneType' object has no attribute 'attributes'

  File "C:\projects\pyfa\gui\builtinAdditionPanes\fighterView.py", line 272, in addItem
  File "C:\projects\pyfa\service\fit.py", line 780, in addFighter
  File "<string>", line 4, in __init__
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\state.py", line 306, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "C:\Python27\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\state.py", line 303, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "C:\projects\pyfa\eos\saveddata\fighter.py", line 54, in __init__
  File "C:\projects\pyfa\eos\saveddata\fighter.py", line 96, in build
```

Also selecting the scrambling script in the Standup Focused Warp Disruptor does not change tackle range in pyfa atm.

Standup Focused Warp Disruptor and Standup Stasis Webifier show their cap usage as Activation Cost / Duration. They both have a 60s reactivation delay though. Would be helpful to adjust that so you can predict actual cap usage easier.

**Comment by blitzmann** [comment]
Hrm... the Standup Cyclops doesn't seem to have any attributes in the database... My data getter script is still probably broken then. :(

Will take a look at that pronto. I'll also take a look at the other things as well.

> They both have a 60s reactivation delay though. Would be helpful to adjust that so you can predict actual cap usage easier.

Is there another module that you can think of that takes reactivation delay into consideration when it comes to cap used? I think we do, but I want to double check so as to make sure we don't use two different standards

**Comment by lunedis** [comment]
A quick search through the SDE gave this:
The following module / groups have the attribute "moduleReactivationDelay":
- Cloaking Devices
- Defender Launcher
- Bomb Laucher
- Micro Jump Drives
- Micro Jump Field Generator
- Assault Damage Control
- Pulse Activated Nexus Invulnerability Core
- Assault Damage Controls
- Standup Stasis Webifiers
- Standup Warp Scramblers

For all of those modules (at least those that use cap and can be activated in pyfa), reactivation delay is _not_ considered, and displayed cap usage is considerable higher than possible ingame.

**Comment by blitzmann** [comment]
I've figured out the issue with some fighters. Seems that CCP simply zero'd out some attributes that those standup ones don't use. which caused problems for the following situations:

* `fighterAbilityKamikazeResistanceID`: Value is supposed to be an attribute ID. Usually when this happens, pyfa fetches the attribute that it links to so that the UI can display the attribute name. In this case, it was `0`, and there is no attribute ID of `0`
* `fighterAbilityLaunchBombType`: This normally links to the typeID that represents the bomb for the fighters (the charge carries the actual damage stats). In this case it was `0`, so so we were trying to fetch a type that didn't exist.

CCP does these little shortcuts every now and then when trying to get a feature out the door, and sometimes causes headaches because, in normal situations, if the item has an attributes, we assume that attribute means somethings. 

That being said, I've got a fix out for both those issues (incorrect charge ID and attribute ID).

As for the cap stuff, I think I will leave it as is for now, but I agree that it should eventually be considered (if it's not already, see https://github.com/pyfa-org/Pyfa/blob/636ee1de23398bb440e7d5b9c554b28354b7a1b7/eos/saveddata/fit.py#L1213 where it looks like it might be considered already - need to look into this more). Looking at that list of module groups, it would seem that reactivation delay hasn't really been used for much up to this point so I wouldn't be surprised if it was never implemented correctly. If not, it would take a bit of time to sort through and figure out a good, central solution for all that going forward.

For completeness, these are all modules that use cap and have a reactivation delay (as defined by the `moduleReactivationDelay` attribute, there may be others that represent this?):

```
select * from invtypes t
JOIN dgmtypeattribs ta ON ta.typeid = t.typeid
join dgmattribs a ON a.attributeid = ta.attributeid
where a.attributeName = 'moduleReactivationDelay' and ta.value != 0.0
and t.typeid in (
	select t.typeid from invtypes t
	JOIN dgmtypeattribs ta ON ta.typeid = t.typeid
	join dgmattribs a ON a.attributeid = ta.attributeid
	where a.attributeName = 'capacitorNeed' and ta.value != 0.0
)
```

```
"Large Micro Jump Drive"
"Medium Micro Jump Drive"
"Standup Stasis Webifier I"
"Standup Focused Warp Disruptor I"
"Micro Jump Field Generator"
"Defender Launcher I"
"Assault Damage Control I"
"EFFA Compact Assault Damage Control"
"FFR Enduring Assault Damage Control"
"Assault Damage Control II"
"Shadow Serpentis Assault Damage Control"
"Standup Focused Warp Disruptor II"
"Standup Stasis Webifier II"
```
