### ISSUE TITLE
Windows Defender prevented the launch of app

### ISSUE THREAD

**Issue by evrial** [pyfa-org/Pyfa#1404]
Just letting know pyfa can't be installed.
Latest pyfa release win32 exe.
Latest Windows 10 Pro updated.

**Comment by blitzmann** [comment]
You can install it. Windows defender will warn you that it can't verify the application, you just need to click the "More" button / link (or whatever it says) and click "Install anyway" (again, whatever it says). It's kind of hidden away since I believe the only button they give you is a "Okay" button, and the "install anyway" button is hidden behind another link.

Pretty much all small open source software has to deal with false positives and warnings from anti-virus. Unfortunately, I can't afford $200 / yr to get a digital cert to sign the executable to prevent it being flagged. ¯\_(ツ)_/¯

**Comment by blitzmann** [comment]
https://www.itsupportguides.com/knowledge-base/windows-10/windows-defender-smartscreen-prevented-an-unrecognized-app-error/

**Comment by evrial** [comment]
Ok thanks for clarification, closing.
