### ISSUE TITLE
Cap Stability calculations are WAY off in the 2.0 beta

### ISSUE THREAD

**Issue by BaconCatBug** [pyfa-org/Pyfa#1405]
## Bug Report
Insanely Inaccurate Capacitor Stability reports

### Expected behavior:
Accurate reports :P

### Actual behavior:
Incorrect reports

### Detailed steps to reproduce:
Use the same fit on different versions.
1.35: http://prntscr.com/igd22g < This is corroborated by the In game Fitting tool.
2.0.0b3: http://prntscr.com/igd27y

All guns have Thorium loaded.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Dominix, Brotato Mk3 Large]

Omnidirectional Tracking Enhancer II
Magnetic Field Stabilizer II
Magnetic Field Stabilizer II
Drone Damage Amplifier II
Drone Damage Amplifier II
Drone Damage Amplifier II
Drone Damage Amplifier II

Large Shield Booster II
Omnidirectional Tracking Link II
EM Ward Field II
Thermal Dissipation Field II
Thermal Dissipation Field II

Drone Link Augmentor II
425mm Railgun II, Thorium Charge L
425mm Railgun II, Thorium Charge L
425mm Railgun II, Thorium Charge L
425mm Railgun II, Thorium Charge L
425mm Railgun II, Thorium Charge L

Large Processor Overclocking Unit I
Large Anti-Thermal Screen Reinforcer I
Large Anti-EM Screen Reinforcer I

Vespa EC-600 x8
Curator II x5
Hobgoblin II x9
Praetor II x5

Thorium Charge L x3454

### Release or development git branch? Please note the release version or commit hash:
2.0.0b3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 8.1

### Other relevant information:
Wasted 10m on rigs :P

**Comment by blitzmann** [comment]
Can you please post the EFT fitting along with drones and information on any other possible modifications (projection/fleet bonus/implants/etc)

**Comment by blitzmann** [comment]
I'm getting the same values...

2.0.0b3:
![image](https://user-images.githubusercontent.com/3904767/36357832-b4816bfc-14d1-11e8-8985-29f056526a6e.png)

1.35.1:
![image](https://user-images.githubusercontent.com/3904767/36357837-cee4609e-14d1-11e8-9904-1a706751a310.png)

Please check other inputs such as fleet bonuses, implants, boosters, projections, skills (although i see that they are both All 5, so that should be a problem). If it's still wonky, it would be helpful if you can remove any modules that don't affect cap directly, just to clean up the fit a bit for troubleshooting. From there. From there, try to pinpoint which modules seem to be causing the difference in values. On both clients, offline all modules and turn them on one by one and compare if both clients get the same values. When you get to a point where it seems they aren't getting the same values, let me know the results :)

I hate to ask that of you, but as I can't reproduce the issue, I don't have any other way to try to pinpoint the cause :)

**Comment by BaconCatBug** [comment]
I checked for effects, no dice. Happens even on a fresh re-extraction of the beta.

With Guns only, differing energy numbers:
http://prntscr.com/igldmr

Guns with no Magstabs, differing numbers:
http://prntscr.com/iglee0

Booster only: Same numbers, different percentages:
http://prntscr.com/igldwb 

Midslots, again differing numbers:
http://prntscr.com/igler6

Is it possible I might have a corrupted database somewhere? Other than the install folder, where are files stored? I didn't use the installer, I just extracted the zip.

**Comment by BaconCatBug** [comment]
I found something: If I put thorium ammo, I get this 
http://prntscr.com/iglikg

But antimatter:
http://prntscr.com/iglioz

Same GJ/s numbers but one is somehow cap stable (when it isn't, as shown in the in game fitting tool for that fit) but the other isn't.

**Comment by blitzmann** [comment]
Hmm, not seeing any of this on my side. 0.o

Can you please send me both databases to sable.blitzmann@gmail.com? They can be found at the following locations:

1.35: `%userprofile%/.pyfa/saveddata.db`
2.0b3: `%userprofile%/.pyfa/saveddata-py3-dev.db`

The purpose here is to have exactly the same data that you have so that I can compare 1:1 and try to figure out the issue.

Please name the fits something that I can easily look up (like `issue1405` or something) and let me know the name

**Comment by blitzmann** [comment]
@BaconCatBug Right-click the fire-power panel and check to see if you have "Factor reload time" checked. With it checked, I'm getting 36.4% on 2.0b3, while not having it checked I'm getting 3:36.

This might be the answer, however it seems that there may be some bugs with it. 

1) I had to toggle it twice before it took effect.
2) Toggling it on 1.35 has no effect on cap.
3) I don't really remember the relationship between that option and the option under preferences > fitting engine > "Factor in reload time...", would have to delve deeper to find out if that setting has any effect

**Comment by BaconCatBug** [comment]
That's the stuff, toggling it on and off on 2.0.0b3 changes the cap time.

**Comment by blitzmann** [comment]
Sweet. I'll keep this ticket open as I reacquaint myself with these functionalities, and try to figure out why I can't seem to get it to work on 1.35 (possible bug on 1.35 that 2.0 fixed?? unlikely, but who knows)

Thanks for the help in troubleshooting it :)

**Comment by blitzmann** [comment]
Solved it. Modules without were returning `-1` for as their `numShots` property when they didn't have a charge (think Large Shield Booster). The old codebase returned `None`, but that doesn't work very well anymore for Python 3, so I changed it to `-1`.  Apparently the capsim has a fit with that, so I changed it to `0`.

**Comment by BaconCatBug** [comment]
Yay I am helping!
