### ISSUE TITLE
Import Fittings not working

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1410]
This is for version 2.0.0b3

Clicking on File>Import fittings
then Selecting a EVE XML fitting file
results in the import dialog box hanging
and force close being the only recovery option

**Comment by blitzmann** [comment]
Thanks for the report(s)! All the broken things!

**Comment by blitzmann** [comment]
This seems to be due to all the encoding code that we had in place. Python 3 now defaults to utf, and so I'm hoping that we can remove the bulk of the codec juggling that we're doing for imports. I have this working now, but will want to test with fit names / fit name using unicode characters (chinese, russian, etc) to be on the safe side.

**Comment by Neugeniko** [comment]
Checked this with russian and chinese fits names and appears to work.
