### ISSUE TITLE
Application stops refreshing with certain fits in Graph.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1430]
### Expected behaviour:
DPS (in graph) is shown no matter if charges are not loaded or partially loaded for a fit.
Graph legend is always shown when fits are listed in graph window.
App refreshes when changes are made to fit/fit selection/character selection etc while graph is open.

### Actual behaviour:
DPS not shown if the weapon type only has some of its weapons or none loaded.
Graph legend is missing if one fit doesn't have charges or has partial charges fitted.
App Fails to refresh when changes are made.

### Detailed steps to reproduce:
Open the following fit.
Optionally open other fits with charges loaded.
Open the graph window.
Note there is no graph of dps for this fit.
Note there is no legend in the graph.
Note that the app fails to refresh while in this state. 

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Jaguar, AS RKT LP WEB AB]

Assault Damage Control I
Co-Processor II
Overdrive Injector System II

Stasis Webifier II
1MN Afterburner II
Initiated Compact Warp Disruptor
Medium Ancillary Shield Booster
Medium Ancillary Shield Booster

Rocket Launcher II, Mjolnir Javelin Rocket
Rocket Launcher II
Rocket Launcher II
200mm AutoCannon II

Small Bay Loading Accelerator II
Small Anti-Kinetic Screen Reinforcer II

Hobgoblin II x2
Hobgoblin II x2

Barrage S x1120
Caldari Navy Inferno Rocket x150
Navy Cap Booster 50 x45

### Release or development git branch? Please note the release version or commit hash:
py3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by blitzmann** [comment]
Well that's... weird.

**Comment by blitzmann** [comment]
![image](https://user-images.githubusercontent.com/3904767/36636153-477473da-198e-11e8-8409-511d7a037a19.png)

Not exactly sure what this means or what causes it, however it's almost certainly an issue with event propagation. Change state on fitting window -> cause FitChanged event to post > graph window catches it, does it's thing, then `event.Skip()` > fitting window then catches it and does it's thing (updates GUI)

So, two things:
1) Figure out what causes that error in the first place, and
2) Seems to me that the logic that handles this error doesn't propogate the event correctly.

At least that's somewhere to start :)

**Comment by blitzmann** [comment]
Event fixed and pushed

**Comment by Neugeniko** [comment]
I'm also getting the following error.

Steps to reproduce:
Open graph with no fit open.
Drag a fit with no/partially loaded charges.
Close graph.
Select a fit in left menu.

OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.2.4
Logbook version: 1.2.1
Requests version: 2.18.4
Dateutil version: 2.6.1

####################

Traceback (most recent call last):
  File "C:\Program Files (x86)\Newark\prog\Pyfa\gui\graphFrame.py", line 232, in draw
    values = self.getValues()
  File "C:\Program Files (x86)\Newark\prog\Pyfa\gui\graphFrame.py", line 183, in getValues
    values[fieldName] = field.GetValue()
RuntimeError: wrapped C/C++ object of type TextCtrl has been deleted

**Comment by blitzmann** [comment]
Hrm... thanks for the additional info. I'll look into the error in the status bar first, then move onto that one.

**Comment by blitzmann** [comment]
Indeed, `mod.maxRange` was returning `None` (because without a charge, there isn't any range) which was causing and issue with something like `None > 0.0` which is no longer valid in Python 3. I suspect there's still many instances of these little `None` bugs left, especially in the graphing engine. A full audit of the classes and their return values and references is probably in order at some point.

I'm also debating displaying the full error dialog instead of a small error in the status text which loses all context, that way folks will be able to report on these things and know when something went wrong.

**Comment by blitzmann** [comment]
@Neugeniko I can't reproduce that traceback, can you give a bit more details, perhaps the exact fit that you were trying to drag / was that fit open in the fitting window?

**Comment by Neugeniko** [comment]
Refined steps;

Steps to reproduce:
Open graph with no fit open.
**Open a fit with no/partially loaded charges.**
Drag the fit to the graph window.
Close graph.
Select a fit in left menu.


Fit Used;
[Jaguar, AS RKT SP WEB AB AA]

EFFA Compact Assault Damage Control
Small Ancillary Armor Repairer
Adaptive Nano Plating II

Fleeting Compact Stasis Webifier
1MN Y-S8 Compact Afterburner
Initiated Compact Warp Scrambler
Medium Ancillary Shield Booster
Medium Ancillary Shield Booster

Rocket Launcher II, Mjolnir Javelin Rocket
Rocket Launcher II, Mjolnir Javelin Rocket
Rocket Launcher II, Mjolnir Javelin Rocket
125mm Gatling AutoCannon II

Small Bay Loading Accelerator II
Small Anti-Kinetic Screen Reinforcer II


Hobgoblin II x2
Hobgoblin II x2


Barrage S x1200
Caldari Navy Nova Rocket x150
Nanite Repair Paste x8
Navy Cap Booster 50 x45

**Comment by Neugeniko** [comment]
Updated the above procedure.

**Comment by Neugeniko** [comment]
Updated the fit. Was wrong had more charges than the one im testing with.

**Comment by Neugeniko** [comment]
This second problem seems to happen to any fit actually.

**Comment by blitzmann** [comment]
I can reproduce.

The problem is the fact that the FIT_CHANGED event is not unbinding properly. When you open the Graph window, it binds to this event so that it can receive updates whenever a fit is changed. When the window is closed, it is supposed to unbind.

Unbinding doesn't seem to be working though, which causes those errors, since we have an object that is still receiving the events, however the underlying wxWidget object for the window has been garbage collected.

I ran into a similar, if not identical, issue with the fitting view when doing the initial port. Turns out it was a bug on wxPython itself: https://github.com/wxWidgets/Phoenix/issues/624

There are two differences with that issue and this issue:
1) `.Unbind()` returns `True` for us, whereas it was returning `False` in that wxPython bug report
2) We aren't using the `handler=` parameter in the `.Unbind()`, which I believe was the cause of the bug before.

Additional information: this doesn't happen with wxPython 4.0.1. but we can't use that version due to other pending issues, so ¯\_(ツ)_/¯

A quick hack fix would be to add this to the `draw()` function:

```
    def draw(self, event=None):
        if not self:
            return
        ...
```

This isn't the proper fix, but will work in a pinch. I will continue to look into the problem to try to find a proper solution

**Comment by Neugeniko** [comment]
The hack has issues with the app failing to refresh properly.

**Comment by blitzmann** [comment]
Ah, sorry, would probably needs something like this lol:

```
   def draw(self, event=None):
        if not self:
            if event:
                event.Skip()
            return
        ...
```

**Comment by blitzmann** [comment]
Right now I think I'll add this to the graph so that I can get another beta release out this week, with the intention of looking into this further at some point.

**Comment by blitzmann** [comment]
Since this issue had three bugs that have been fixed (at least, from the user's perspective), I'm going to mark this as fixed and create a new issue to look into the event unbinding specifically. Thanks as always for helping with the troubleshooting @Neugeniko!
