### ISSUE TITLE
Open fittings in a new page by default option problem.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1432]
### Expected behavior:
When the option 'Open fittings in a new page by default' is selected in preference I expect pasted fittings to still open in a new tab.

### Actual behavior:
When the option 'Open fittings in a new page by default' is selected in preference pasted fittings overwrite the currently selected tabs.

### Detailed steps to reproduce:
Select option 'Open fittings in a new page by default' in preferences.
Open a fitting
Hit Ctrl-C and select EFT format
Hit Ctrl-V
Note the fitting overwrote the current tab.
### Release or development git branch? Please note the release version or commit hash:
py3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

### Other relevant information:
 This is also possibly causing some refresh problems (unable to reproduce those atm).

**Comment by blitzmann** [comment]
Thanks, this is actually a pretty old bug from when that feature was first developed. IIRC, it's only really applied to fits selected from the fit browser. Shouldn't be too difficult to fix though, will take a look :)

**Comment by blitzmann** [comment]
So it was due to `CmdDown()` always evaluating to `True` because the event was triggered with Ctrl+C, and of course Ctrl is pressed.

Simple fix for this is to always open imported fits as new (regardless if coming from Ctrl+C or Edit > From Clipboard, and regardless of setting in preferences). The idea is that if you're importing a fit, you wouldn't want to close the current one you're working one. Thoughts?

**Comment by Neugeniko** [comment]
Yep if you importing you usually want to check out what your importing without interfering with whatever else your doing.

**Comment by blitzmann** [comment]
Sweet, just wanted to run it by someone else. Fix merged into master and 2.x
