### ISSUE TITLE
Error when deleting characters.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1445]
### Expected behavior:
Character gets deleted in character editor and no errors occur.

### Actual behavior:
The following error occurs.

OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.2.4
Logbook version: 1.2.1
Requests version: 2.18.4
Dateutil version: 2.6.1

####################

Traceback (most recent call last):
  File "C:\Program Files (x86)\Newark\prog\Pyfa\gui\builtinViews\entityEditor.py", line 149, in OnDelete
    self.DoDelete(self.getActiveEntity())
  File "C:\Program Files (x86)\Newark\prog\Pyfa\gui\characterEditor.py", line 145, in DoDelete
    sChar.delete(entity)
  File "C:\Program Files (x86)\Newark\prog\Pyfa\service\character.py", line 344, in delete
    eos.db.remove(char)
  File "C:\Program Files (x86)\Newark\prog\Pyfa\eos\db\saveddata\queries.py", line 538, in remove
    saveddata_session.delete(stuff)
  File "C:\Python36-32\lib\site-packages\sqlalchemy\orm\session.py", line 1812, in delete
    self._delete_impl(state, instance, head=True)
  File "C:\Python36-32\lib\site-packages\sqlalchemy\orm\session.py", line 1845, in _delete_impl
    self._delete_impl(st_, o, False)
  File "C:\Python36-32\lib\site-packages\sqlalchemy\orm\session.py", line 1829, in _delete_impl
    self.identity_map.add(state)
  File "C:\Python36-32\lib\site-packages\sqlalchemy\orm\identity.py", line 149, in add
    orm_util.state_str(state), state.key))
sqlalchemy.exc.InvalidRequestError: Can't attach instance <Skill at 0x1578ddd0>; another instance with key (<class 'eos.saveddata.character.Skill'>, (9, 33078), None) is already present in this session.

### Detailed steps to reproduce:
File>Import Character File Several time using the attached file.
Go into Character Editor
Delete these newly created characters.
The error should occur after a few deletions

[Florinio (after plan VNI & Vexor).zip](https://github.com/pyfa-org/Pyfa/files/1766124/Florinio.after.plan.VNI.Vexor.zip)

### Release or development git branch? Please note the release version or commit hash:
py3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
win 10

**Comment by Neugeniko** [comment]
If security status is not passed at line 97, services/character.py, this error does not occur.

**Comment by blitzmann** [comment]
Thanks! I can reproduce, haven't looked at the security status bit.

IIRC, there is an issue with how Skills are created and attached to a character going back a few months. People have reported on it after updating their skills via API (since it deletes all skills and repopulates them). I wonder if it's something related. Not sure what security status has to do with this error though, as that's a character attribute and not a skill attribute. 

More info: for the characters that this error happens for, their skills are never deleted from the database. So, for example if you have an error with key `(9, 33078)`, character ID 9 will be deleted, but the skills for 9 will still be there (I believe we have a script that runs on pyfa startup that deletes orphaned skills to prevent issues)

**Comment by blitzmann** [comment]
> If security status is not passed at line 97, services/character.py, this error does not occur.

If you're just removing the parameter, it's not going to work. `sCharacter.apiUpdateCharSheet(char.ID, skills)` throws an error because sec status is expected. The character is still created before this, however - this function simply updates the skills associated with the character, which is why is still seems to work. The issue seems to be related to the skills themselves and how they are applied to the character. Still need to look deeper.

**Comment by Neugeniko** [comment]
sCharacter.apiUpdateCharSheet is used without security status at line 69, and works without using it for me.

**Comment by blitzmann** [comment]
@Neugeniko Think I have a fix, can you try out this branch to see if you can get it to break?

https://github.com/pyfa-org/Pyfa/tree/issue/1445

When we update via a character sheet (either through API or through Character file import), we remove the skills form the character and recreate them. This isn't really necessary, since the character should already have all skills on them - just get the skill and change the level.

Even if this works, I want to look into it a little more to make sure it doesn't break anything else. This could very well be a fix for phantom bug that's been plaguing pyfa for a few months now, so if it seems okay I will probably include this in master.

**Comment by blitzmann** [comment]
> sCharacter.apiUpdateCharSheet is used without security status at line 69, and works without using it for me.

huh... I think that might be a bug, honestly. If I remove the sec status, I get to this catch block here:

```
                    ...
                    sCharacter.apiUpdateCharSheet(char.ID, skills, securitystatus)
                except Exception as e:
                    pyfalog.error("Exception on character import:")
                    pyfalog.error(e)
                    continue
```

The log doesn't print because it's in another thread, but you can throw a breakpoint in there and it should get there, and the skills aren't actually set for me (they are "Not Learned")

**Comment by blitzmann** [comment]
Oh wait, that branch doesn't set the levels properly. Arg! Lemme look

**Comment by blitzmann** [comment]
kk, branch updated, should actually work properly now :P

**Comment by Neugeniko** [comment]
Looks like it works, tried importing character file 30 times and deleting them in character editor and no error.

**Comment by blitzmann** [comment]
And I've also noted that `Character.apiUpdateCharSheet()` is only used in two places, so applying that patch shouldn't cause many, if any, issues.

**Comment by Neugeniko** [comment]
You want to create a seperate issue for double clicks filtering through to the shipbrowser from the import character file dialog?

**Comment by blitzmann** [comment]
> You want to create a seperate issue for double clicks filtering through to the shipbrowser from the import character file dialog?

Done, thanks!
