### ISSUE TITLE
Projecting a fit with a scram, WDFG or Standup Disruptor onto a fit with a mwd can cause errors.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1458]
### Expected behavior:
Speed shows as normal when MWD is online(off).

### Actual behavior:
Speed shows as if MWD is active(on) when MWD is online(off).

### Detailed steps to reproduce:
Self project the following fit.
Toggle the projection on and off alternating with the mwd active and online.
Note you can get the mwd online whilst the speed shows as if its active.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Broadsword, AC IP PS MW]

IFFA Compact Damage Control
Gyrostabilizer II
Gyrostabilizer II
Tracking Enhancer II

50MN Y-T8 Compact Microwarpdrive
Large F-S9 Regolith Compact Shield Extender
Adaptive Invulnerability Field II
Large F-S9 Regolith Compact Shield Extender
Adaptive Invulnerability Field II
Adaptive Invulnerability Field II

425mm AutoCannon II
425mm AutoCannon II
Warp Disruption Field Generator II, Focused Warp Scrambling Script
425mm AutoCannon II
425mm AutoCannon II
425mm AutoCannon II

Medium Core Defense Field Extender II
Medium Core Defense Field Extender II

### Release or development git branch? Please note the release version or commit hash:
1.35.1 or py3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
If you project the modules instead of the fits, then this behaviour goes away as the module projections automatically get turned off when you turn a mwd on.

**Comment by Neugeniko** [comment]
The above lead me to the conclusion we are projecting the disallow remote assistance which shouldnt happen, it only applies to the ship that is using it.

And indeed we are in file warpdisruptsphere.py it get set without a context.

fit.ship.forceItemAttr("disallowAssistance", 1)

**Comment by Neugeniko** [comment]
I've learn a bit more about pyfa code but I haven't gotten any closer to solving the op. all ive got is this doesnt happen with module projections of the same modules just fits using those modules. Putting in a recalc solves the problem. Its almost as if you click the mwd on, the recalc does the speed calc then turns the mwd off. if the mwd off was done first then it world work but i dont know how ordering is done within calc...yeah this seems to be the case..i put a breakpoint in the mwd effects file and the WDFG wffect file and the ordering is the wrong to get this working.

**Comment by blitzmann** [comment]
This is most likely due to a runtime issue. Each effect is assigned a runtime ("normal" if not explicitly set). Early goes first, normal next, late last. For each runtime, we run through the list of modules in a specific order (that I can't remember right now), and apply the effects.

What is happening here is most likely the following:

MWD runs it's "Boost Velocity" effect, modifying the velocity of ship
Then, Warp Sphere runs, which will actually turn off the MWD. Unfortunately, the MWD effect has already been applied.

I think that this is compounded by the fact that projected modules _always_ run after local fit calculations, and there's not method to reverse an effect. I could be wrong with that, but this might just be a bigger problem and not very easily fixable

**Comment by Neugeniko** [comment]
Outside of that loop recalc of type projected get run at the end of the recalc function.

**Comment by Neugeniko** [comment]
The canHaveState function might be a place to define the code to handle this, as it is called in service\fit.py  checkStates function to handle recalcs.

**Comment by blitzmann** [comment]
> The canHaveState function might be a place to define the code to handle this, as it is called in service\fit.py checkStates function to handle recalcs.

Sorry, not sure I follow, though I don't think `checkStates` would be the best place for a solution (if there even is one). I believe that function is simply a helper function to make sure all modules have the correct state when the fit is loaded, after the state has been toggled, etc. The crux of the problem is that during calculations, when the MWD calculation runs, it has no idea about the projection calculation that cancels it out, so it simply applies itself to the fit. Then the scram script turns it off, but that doesn't actually touch the calculation since it's already happened, it just turns it's state to the off position (which will be picked up during the next recalc)

The way the pyfa calcs work is that they are applied as they go (for the most part), rather than staging all work and then going "if this module is on, apply" at the end. So there are unfortunately situations that we run into where a calculation has been done before another calculation that was supposed to affect it is run. We normally handle these with the `runTime` effect property, however projected fits are run outside of that normal loop.

That being said, it may be possible to define a special effect type that runs inline with local fit calculations, instead of after all `runTime`s process. That way we can have special projected effect run before the local fit runs... let me take a quick look at that, it might be somewhat easy, if not hackish.

**Comment by blitzmann** [comment]
So, I made a tweak that would work... however I don't like it, and don't think I'll be including it as it currently stands. See f71a49e42ec37cdf2aa0ec158c932eb20c46efd0

It basically gives the warp sphere effect a new type, `pre-projected`, and before we run local fit calculations, it goes through projected fits and runs only effects marked as `pre-projected`. Then the normal fitting calculations run.

I don't like it for a few reasons:

* This is a pretty heavy-handed addition for the sake of one bug. We have four nested loops for the pre-projection calculations, which are required (could make it 3 if we get rid of the "apply x number of times", which is probably unneeded). This solution is pretty much custom-made for this specific issue
* This does not run a fitting calculation on the projected fit first. If we ever have a projected effect that needs to both run before local fitting calculations and also include calculations based on the projections local calculation, this would not be able to support this.
* And of course, it's very much not tested, and when it comes to fitting calculations involving projected / gang stuff, it makes me nervous, especially when I'm not too hot on the solution.

To properly fix this would probably require a substantial re-working of how effects are applied. For example, perhaps calculating all fits scoped to their local, caching any effects that may need to be projected, and simply just applying those projections at the beginning / end of fitting calculation where needed, instead of doing it within the runtime loops and whatnot.

Or a way to "remove" an already-applied effect. This might be easier to accomplish, but would require us to kind of keep track of how things are applied (we kinda sorta do this already). If anything, this would be the next thing I would research - could take a look at which attributes were modified by any MWD (using the affected by tracking), and reverse the calc depending on the method used.

As it stands right now, I'm thinking about categorizing this as a `wontfix`, but would want to revisit this at some point. It's not a crucial bug, and would require a lot of thought to properly handle it, and 2.x has a lot more in the pipeline :)

Sorry if none of this makes sense, it's late :P

**Comment by Neugeniko** [comment]
The work around when this bug is encountered is simple enough, just toggle a module, but my main concern is it how often is it encountered. Projecting a fit with a scram may be pretty common.

**Comment by DarkFenX** [comment]
This has been fixed a while ago. Latest versions now properly disable mwd.
