### ISSUE TITLE
Bug Report: Unable to Retrieve Skills

### ISSUE THREAD

**Issue by RedViper9** [pyfa-org/Pyfa#1473]
### Expected behavior:
On inputting API key and vCode, character can be imported and skills can be loaded.

### Actual behavior:
Get Character works, Fetch Skills fails and gives error 3390
Googling error 3390 does not lead to anything that looks useful.

### Detailed steps to reproduce:
Sorry, won't publicly post API. I do have a non-public skill from ye olde days. Perhaps that is causing a problem? Fetching skills on newly made alt character works just fine.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
N/A

### Release or development git branch? Please note the release version or commit hash:
pyfa 1.35.2 Stable - YC120.2 1.2

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10.

### Other relevant information:
Attempted:
Generated new API key, fetch fails.
Deleted character, created new character with different name, third API key, fetch fails.

**Comment by blitzmann** [comment]
Hi there @RedViper9. 

Thats an odd error... not really sure what it means. I understand not wanting to post the api information, but would you mind sending it to me via email? Please also send your database located at `%userprofile%/.pyfa/saveddata.db` just so that I can have as close as possible what you have for testing (also, which skill are you talking about that may not be publicly available? That's really interesting)

Additionally, did previous versions of pyfa have this issue, or are you a new user? If you're new, downgrading is not recommended, so don't worry about it, just wondering if you've ever run into this before.

**Comment by blitzmann** [comment]
Sorry, forgot to mention: email is sable.blitzmann@gmail.com :)

**Comment by hendrikgit** [comment]
Hello, I have the same issue. I also have some old skills that are no longer distributed todya and thought it might be related.
I remember one of the skills in question is mobile refinery operation, can't think of the others right now.
I'll send you a mail with more information.

**Comment by blitzmann** [comment]
Thanks @hendrikgit, mail received! And thanks!

https://esi.tech.ccp.is/latest/universe/types/3390/?datasource=tranquility&language=en-us

This is the skill that seems to have been removed. We don't handle it properly right now, which should be a quick fix!
