### ISSUE TITLE
Feature request: Removed mods to be added to "recently used"

### ISSUE THREAD

**Issue by ErikKalkoken** [pyfa-org/Pyfa#1492]
# Suggestion
I would suggest that mods that are removed from a current fit should automatically be added to the "Recently Used Modules" view.

## Motivation
If you play around with fits you often remove mods for testing. Having them available for quick refitting later in the "Recently Used Modules" view, helps to significantly speed up the process. Currently you need to find that module again on the market (if you remember which one it was), which can take some time. Btw. this is also the behavior of EFT, so many people will be used to this.

**Comment by blitzmann** [comment]
I can get behind this, and I don't believe it would be too difficult. The biggest question would be how best to communicate that change to the market browser (which handles the recent modules list) from the fitting window. Thanks for the suggestion!

**Comment by ErikKalkoken** [comment]
Any news on this enhancement? Is it still being considered?

**Comment by DarkFenX** [comment]
This was created before I got back to maintaining pyfa. I think it's really nice to have (and at some point pyfa had this behavior) but it still needs to be coded. If anyone can do it - you're welcome.

I might have some time for it but much later. Will try to squeeze it into next release, but no promises.

**Comment by DarkFenX** [comment]
Fixed in 9be1b96226651a2e7557117648e6196a2e779877. It triggers only when something gets added or removed explicitly (so for example will trigger for subsystem you added via market, but will not trigger for subsystem which was replaced by it; however if you remove subsystem manually, it will be added). Changing variation does not trigger it. Works for following items:

- modules / subsystems
- drones / fighters
- cargo
- implants
- boosters

Does not trigger for any projected items (including modules and drones).

 Also implemented sorting by recency, it was using default market sorting before.

**Comment by DarkFenX** [comment]
Forgot to mention that original use-case might be covered by variations menu and undo/redo. But recently used still might be good for some fringe cases.
