### ISSUE TITLE
Unable to Retrieve Skills

### ISSUE THREAD

**Issue by DeddMazay** [pyfa-org/Pyfa#1503]
When I'm fetching skills this [message](https://i.imgur.com/EzVz9nj.png) has appeared. What am I doing wrong?
vers. 1.36.0

**Comment by DeddMazay** [comment]
Successfully fetched. Probably some time must pass after creating API

**Comment by blitzmann** [comment]
That error might happen if the request to fetch the skills takes too long - I don't know the timeout off hand, bu I suspect it's 10-30 seconds. If it doesn't recieve a response from the EVE servers in that time, it fails. This could be due to local network conditions or possibly EVE's API servers undergoing maintenance.

Glad you go it working though, gonna close this now :)
