### ISSUE TITLE
Inconsistency on ammo charges listing (long range <--> short range)

### ISSUE THREAD

**Issue by SubjectXXX** [pyfa-org/Pyfa#1520]
## Bug Report
Ammo types jump up and down

### Expected behavior:
List is ordered and static.

### Actual behavior:
No ammo loaded:
![image](https://user-images.githubusercontent.com/2082595/38556282-65ce011c-3cc9-11e8-9d5f-e9b66e7de8d3.png)

Selecting Void S as ammo:
![image](https://user-images.githubusercontent.com/2082595/38556313-8471162c-3cc9-11e8-9c9b-734fd00f0029.png)

Selecting fed navy AM:
![image](https://user-images.githubusercontent.com/2082595/38556341-9a7c9d4c-3cc9-11e8-96b5-cab9bd0057c5.png)

Probably has something to do with skill order being applied, since two optimal range bonuses come from two different skills..

### Detailed steps to reproduce:

Try loading different ammo types onto problematic fitting.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Harpy, cap stable?]

Micro Auxiliary Power Core II
[Empty Low slot]
[Empty Low slot]

'Censer' Medium Cap Battery
Pithum C-Type Medium Shield Booster
1MN Y-S8 Compact Afterburner
Warp Scrambler II

Light Electron Blaster II, Void S
Light Electron Blaster II
Light Electron Blaster II
Light Electron Blaster II
[Empty High slot]

Small Ancillary Current Router II
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
1.36.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
win7

**Comment by blitzmann** [comment]
huh, interesting. Haven't touched this code in a while, so not sure why it's all of a sudden causing issues. Will take a look, thanks!

**Comment by blitzmann** [comment]
wow, this has been like this since 2010 when the ammo picker sorter thing was implemented. Impressive.

You're correct in the assumption that it's taking into consideration the current modifications being applied to that module. The way that it's sorted is it takes the range / falloff modifiers for each charge and applies them to the currently calculated range and falloff for the module. Of course, if you apply a charge that changes this calculated value, the end result could be a different sort.

The fix here is that I take the base value for the module, not the calculate value, and calculate the range modifiers for the charges based on that. It gives a static list in that situation. There may be some situations in which it's not 100% correct, but the list should be a "void is, in general, the shortest range ammo you get, barring some funky shit with gang links and drugs".
