### ISSUE TITLE
Cant make new ship fittings

### ISSUE THREAD

**Issue by blacktornado21** [pyfa-org/Pyfa#1522]
### Expected behavior:

Open a new ship fitting to fit a ship

### Actual behavior:

error window with texts pops up

### Detailed steps to reproduce:

attempt to make new fit

### Fits involved in EFT format (Edit > To Clipboard > EFT):

every ship

### Release or development git branch? Please note the release version or commit hash:

1.36

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

windows 10

### Other relevant information:

started happening randomly a few weeks ago, thought reinstalling pyfa would fix it but it didnt. Also started happening out of the blue

**Comment by blitzmann** [comment]
Sorry for the delay in getting back to you on this!

> error window with texts pops up

It would be really helpful for you to copy and paste that text, otherwise I don't even know where to begin to look. 

Along with posting the text here, you could send me a copy of your database (found at `%userprofile%/.pyfa/saveddata.db`) to `sable.blitzmann@gmail.com`. it may be that something in your database has become corrupted, not allowing it to change or create new fittings.

**Comment by blitzmann** [comment]
@blacktornado21 Don't think I ever received an email from you, and I haven't had anyone else report an issue like this. There is a new version cycle, 2.x, that may or may not have fixed this already. Please give it a try, and if there's any error that pops up, please be sure to post the error text :)

Gonna close this for now.
