### ISSUE TITLE
jargon.yaml and defaults.yaml overwriting order/comments

### ISSUE THREAD

**Issue by ftsartek** [pyfa-org/Pyfa#1533]
Changing or creating comments/new definitions in jargon.yaml will be 'adjusted' upon launching pyfa - even if the content of defaults.yaml is identical. Comments and ordering will be removed and/or changed. Happens immediately on Pyfa launch. Comparison files attached for clarity (in .txt form)
[defaults.txt](https://github.com/pyfa-org/Pyfa/files/1962252/defaults.txt)
[jargon.txt](https://github.com/pyfa-org/Pyfa/files/1962253/jargon.txt)

It's not a big deal, since functionally it's still the same but when entering new abbreviations/definitions it can be a bit annoying to find where you left off.

Makes no difference whether defaults.yaml is modified or as shipped with pyfa.

**Comment by blitzmann** [comment]
@fsufitch Could you take a look at this when you can? Even though there is no functional difference, I would think it would be beneficial to keep comments around for users

**Comment by fsufitch** [comment]
Yep. I even know the exact cause of this: the jargon service merges your custom `jargon.yaml` with the stuff in `defaults.yaml` to be able to receive future updates to the default jargon, then re-exports the combination. This export does not have comments, since comments are never parsed or accounted for in any way.

In light of that, I see a spectrum of resolutions:
 
1. Do not merge updates from `default.yaml` into `jargon.yaml` at all. That would to be done manually, or just by deleting 'jargon.yaml`. This means that, if it already exists, Pyfa would treat `jargon.yaml` as read-only, which would preserve comments.

2. Hacky plaintext merge of `default.yaml` into `jargon.yaml`. That is, if there are new entries to be introduced, they get simply appended to the file, as opposed to exported using a YAML exporter. This would also preserve comments, but risks corrupting the integrity of `jargon.yaml` if (for some reason) there is more complex data in there.

3. Shift the jargon file format from YAML to JSON or another human-readable serialization format with no comments. This obviously does not preserve comments since comments no longer exist.

4. `Won't fix` it for now, and deal with it this way until we get around to building a GUI to manipulate the jargon file (which could track comments, order, and more).

I can do #1, #2, or #3 quickly, if any of those are acceptable, but #4 is probably something that needs its own ticket, planning, and feature release.

**Comment by fsufitch** [comment]
That is very doable. YAML is a superset of JSON and works about the same way. As far as how  I load the file, I use standard `pkg_resources` access to grab it as a string, before feeding it into the PyYAML parser.

As far as actually doing this, I kind of preferred the simplicity of having one "authoritative" file, but I can see the merits of your idea. Taking the defaults and overlaying user-configured jargon onto them even allows effectively "disabling" some, by setting the jargon to blank (e.g. `xlasb: ""`).

This should be a fairly simple change, and I can do it when I get some free time.

**Comment by blitzmann** [comment]
I can totally understand why it was done the way it was done, but methinks it would be more... standard, for lack of a better term to have the user config not written to. If a user customizes it, they would expect it to stay the same and not changing. And for now, with a GUI system being a ways out, I think it's the best course. 

Thanks for the response! Not rush, let me know if I can assist ;)

**Comment by blitzmann** [comment]
Fix was merged, thanks a bunch to @fsufitch!
