### ISSUE TITLE
search filter did not work so well

### ISSUE THREAD

**Issue by BikerGitHub** [pyfa-org/Pyfa#1544]
### Expected behavior:
I search for "Pith X-Type Shield Booster",it should in "Complex" tab.
When I enter "Booster","Pith X-Type Shield Booster" should include in the result.
### Actual behavior:
The "Complex" tab shows grey,and can't been click.

### Release or development git branch? Please note the release version or commit hash:
1.36.0 and v2.0.0b6

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
windows 10

**Comment by blitzmann** [comment]
Thanks for the bug report! I'll take a look at this when I get home and confirm, hopefully get a fix in before the new release :)

**Comment by BikerGitHub** [comment]
I can't coding but hope make it better.

**Comment by blitzmann** [comment]
So this is because the results that are returned by a search are limited to 100 (for performance reasons). The Normal / Faction / Complex / Officer filtering is actually a subfilter on that already filtered list. So, when you search "Booster", "Pith X-Type Shield Booster" simply isn't returned as an item due to it being truncated by the 100 item limit.

There might be a way to have the "normal" tab show literally 100 normal items of the search term, "Complex" shows 100 of the search term, etc. However, that is a very low level change and I'm not even sure it would be possible (would have to look at how those sub categories are calculated). I don't think there would be much benefit to doing it that way, as I believe most folks would simply narrow the search more.

Hope that clears things up :)
