### ISSUE TITLE
Can't add any character via sso. pyfa2 

### ISSUE THREAD

**Issue by Flevity** [pyfa-org/Pyfa#1550]
OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 784, in addCharacter
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 209, in login
AttributeError: 'Esi' object has no attribute 'settings'

**Comment by HHpetra** [comment]
me too. so puzzled.

**Comment by Vel-RahnKoon** [comment]
Same for me.

**Comment by blitzmann** [comment]
Do you guys get a message about it failing to initialize?

I am assuming you guys went straight through to logging in via the character editor. Try going to EVE SSO > Manage characters and logging in through there. That should initialize the ESI service (it needs to gather some data the first go round), and that might solve the problem.

**Comment by Flevity** [comment]
Yeap I got failing to initialize message. Even throughout  EVE SSO > Manage characters I've got that an error. https://i.imgur.com/QUuga77.png

**Comment by blitzmann** [comment]
> update: OK I succecefuly initialized ESI with EVE SSO > Browse EVE Fittings. 

Making the ESI initialization more... robust, is one of my high priorities. Suggestions welcomed if you're interested in code lol.

>seems like pyfa.io blocked in Russia

I am not using amazon hosting. Hrm... not sure what to do about this one however... I do have a task to re-introduce your own ESI Developer client details to circumvent pyfa.io entirely. But I needed pyfa.io as a middleman for authorization requests. :/ I'll look into giving an option to save client details and doing SSO directly instead of through a proxy

**Comment by Ledger4Life** [comment]
yeah still have issues with this  =)

OS version: Darwin-17.5.0-x86_64-i386-64bit
Python version: 3.6.3 (default, Oct 22 2017, 22:24:50) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.1

####################

Traceback (most recent call last):
  File "/Users/ryan/pyfa/gui/esiFittings.py", line 329, in addChar
  File "/Users/ryan/pyfa/service/esi.py", line 209, in login
AttributeError: 'Esi' object has no attribute 'settings'

**Comment by blitzmann** [comment]
@minlexx I think the main issue with the pyfa.io proxy is the fact that I must keep my client details secret, and yet give users the ability to "log in once" and not have to worry about a 20 minute timer that comes with implicit authentication. This way users get a refresh token, but don't know my client secret for ESI.

If pyfa.io is blocked in russia (my hosting is probably hosted through google or AWS themselves), then that's something we'll have to work around somehow.

There seems to be two inherit issues in this thread:
1) ESI service is not initializing correctly. This is most likely due to esipy, which uses pyswagger, not able to fetch the data from the eve swagger definitions (I've seen request timeouts and the like, as you've noted @minlexx). The solve for this, I would think, would maybe do this in a background thread when pyfa starts and allow it a larger timeout time. This has nothing to do with pyfa.io - this is pyswagger reading the swagger definition from eve
2) pyfa.io being blocked, which I don't currently have a solve for other than to allow folks to utilize their own client details like 1.x CREST stuff did.

We may very well scrap esipy if the issues with pyswagger get in the way too much and just use targeted endpoints - pyfa doesn't use the vast majority of the swagger interface, so a lot of that "fetch definition" that can take 15+ seconds or even timeout might be a bit... too much, so I don't think it would be a huge loss. However, if we can work around that for now, that would be preferable

**Comment by blitzmann** [comment]
> esipy / pyswagger do not support connecting through proxy (?), thus making it impossible to use ESI from Russia, for example, where large IP ranges of google/amazon are still banned (shame). 

Wait a minute... are you saying that ESI itself can't be accessed from Russia? IIRC, CCP hosts ESI on AWS...

**Comment by Flevity** [comment]
yeap =/

**Comment by Vel-RahnKoon** [comment]
I shut down my PC and that got it to work.

**Comment by minlexx** [comment]
@blitzmann I'm honestly not sure what's the real problem, it is hard to debug because of complexity of pyswagger. Sure, we tend to blame our stupid government here for all internet problems lately.

pyfa.io seems fine: http://isitblockedinrussia.com/?host=pyfa.io
ESI not so well: http://isitblockedinrussia.com/?host=esi.tech.ccp.is , http://isitblockedinrussia.com/?host=esi.evetech.net  :(

**Comment by GKFC** [comment]
Same issue to me, here's the popups I get:

![pyfa_message](https://user-images.githubusercontent.com/24534756/39845154-9cc345d0-5437-11e8-9a7e-9d6e6b9f3266.png)

(which isn't the case re: my connection) and then:

![pyfa_exception](https://user-images.githubusercontent.com/24534756/39845159-a2c7820c-5437-11e8-8e7b-6c72c56bf2e8.png)

pyfa won't let me copy and paste the text because the focus is on the dialog box behind... so I end up copying / pasting the fit that's open instead...

Is it because it's looking for a specific location that isn't on my computer?  No idea who ryan is...

Cheers,

G.

**Comment by blitzmann** [comment]
> btw, I found out why pyfa.io isn't available from Russia, it seems that you somehow use pythonanywhere's services which hosted on AWS in a subnet blocked in Russia 34.192.0.0/10

Yep, that would do it. pyfa.io is on pythonanwhere as it was cheap and easy to get up and running, but as stated, probably hosted by AWS themselves.

@minlexx That is odd that it shows pyfa.io being available and other say it isn't. Maybe it's regional? I have no idea. And I don't think it would be possible to feed pyswagger / esipy the swagger.json file without some major hacks, and even then it wouldn't really be the proper way of doing it. The way that pyswagger does it it not only fetches the swagger.json, but goes through it and downloads models, parameters, etc for the endpoints.

I'll try to send it off in a BG thread and just have ESI services not available until it either works or fails x times. That should be a quick fix, hopefully. But I'm increasingly of the mindset to just shim out a quick and dirty way of accessing ESI stuff through `requests` package, seeing as I don't have a real need for many of the features pyswagger offers. pyfa uses a total of 3 endpoints IIRC. That, along with the token fetching stuff, I don't think it's too complex. The initialization time is just killing it.

I can say that the ESI service seems to be working well for the vast majority of the folks utilizing it. Unfortunately, that's not good enough for me, considering there's no real other way to get character skills.

**Comment by blitzmann** [comment]
Also, just throwing it out there, these problems could be related to #1548 - if the SSL is fucking up, that could cause the whole ESI initialization process to fail.

Can you guys please take a peak into `%userprofile%/.pyfa/*.log` (whichever log file is applicable). You should see a log with `service.esi`, can you please copy and paste that line and the surrounding lines as well? That should give me a good idea of what types of errors these actually are (timeouts, SSL, etc)

**Comment by blitzmann** [comment]
@minlexx in that picture you posted with the exception, can you reproduce and post the contents of `partial`? That looks like it could be ESI actually returning an error themselves that we aren't handling correctly?

**Comment by minlexx** [comment]
> @minlexx in that picture you posted with the exception, can you reproduce and post the contents of partial? 

I saved the contents of `partial`: [here, 548 Kb](https://eve-wh.space/static/pyfa_incomplete_read.txt)
Looks like partial download...

**Comment by Flevity** [comment]
@blitzmann part of my log with the error
[pyfa.log](https://github.com/pyfa-org/Pyfa/files/1992434/pyfa.log)

**Comment by KadnikovVN** [comment]
@minlexx you are wrong. pyfa.io is not blocked in Russia but www.pyfa.io is BLOCKED. Pyfa(app) redirect to www

http://isitblockedinrussia.com/?host=www.pyfa.io
It is working with proxy on main browser or from US side (azure)

**Comment by minlexx** [comment]
Meh... either use VPN for us, or have proxy support built in pyfa anyway :confused:

**Comment by blitzmann** [comment]
Hi all! The new point release is out with the ESI fixes stored in the pipeline. please check that to see if your problems still persists. :)

If it does, please log a new issue. 

For those of you that have www.pyfa.io blocked, please note that there is now the ability to enter your own client details to skip the middle man proxy. (I might be able to use the proxy info from network tab to go to pyfa.io, but I didn't think of it this release. @minlexx would this be feasible? IIRC you got the proxy support up and running recently for v2).

More details on what parameters you need to setup your own developer application can be found here: https://github.com/pyfa-org/Pyfa/wiki/EVE-SSO

**Comment by minlexx** [comment]
> @minlexx would this be feasible?

Yes! pr #1578
