### ISSUE TITLE
Graphing: Alpha spikes vs DPS

### ISSUE THREAD

**Issue by christhegoth** [pyfa-org/Pyfa#1615]
Over-all I do like this one.

Can I request:

Drone Application to be calculated, instead of just a basic module.  It doesn't seem to cover it properly.  Well, not that I can see anyway.  Apparently Ogres are amazing against fast-moving frigates etc.

Alpha & DPS on the same graph? Actually seeing alpha spikes vs time/distance could be useful.  A saw-tooth wave vs the usual plot.

Apart from that great stuff. Many thanks :)

**Comment by blitzmann** [comment]
Hey there,

Not sure I understand the drone thing:

>Drone Application to be calculated, instead of just a basic module. It doesn't seem to cover it properly. Well, not that I can see anyway. Apparently Ogres are amazing against fast-moving frigates etc.

Can you be a  bit more descriptive? I think you're talking about drone DPS within the graph, but I'm not exactly sure. :)

As for the graph, the thing with alpha is that it's only ever accurate at the start of the graph. Alpha, or volley, damage happens when all module fire at the same time. However, with the differences in cycle speed, these modules will obviously get out of sync overtime.

Of course, most of the time damage modules fire at the same time anyway, in game. However pyfa doesn't have any concept of "grouping" weapons together. It might be possible to have an option that says "group like modules" and instead of dps show what you're asking for. But at the same time, we need to consider what the x -axis would be - time is kind of redundant (you'll be hitting for the same damage every x seconds). Distance doesn't really make sense as it would assume a linear constant growing distance between weapon group strikes - which rarely happens in game.

Not saying it's not possible, anything is possible, but I need to make sure the requirements of such a graph are completely thought out and there is indeed a use case for it. Creating graphs in pyfa is a general headache, and won't be undertaken unless it's something very useful. :)

**Comment by christhegoth** [comment]
Grouping as modules, and then showing the dps as a spike that then ebbs off, may well help people. That would have to be over time though.

Which takes us into a second graph, including distance, time, sig, speed, & angle.  I think that that would help a lot.

x & y would be: time & dps respectively. The spike, vs the line.

Then you bring in a z axis.  That can be changed from sig to speed to angle to....

3d graphs might be the way forward.

.

As for drones; on current pyfa it's like a 'minimum damage' you see before you load the highs. Tat 'minimum damage' doesn't seem to change much if you play with sig or speed etc, & it should.

Not sure if it is me going mad, but if not it would be handy if drone DPS reflected drone vs the usual DPS graph stuff.

.

As for gun-grouping that would also help, but I'd be happy just seeing the 3d graph at this stage.  That won't be easy in itself I'd imagine.


Danke :)

**Comment by blitzmann** [comment]
> 3d graphs might be the way forward

I love your optimism with this lol.

3D graphs, to me, sound very difficult. Maybe they aren't all that bad, but just thinking about it makes my head hurt lol

These are some interesting concepts, but I'm gonna be real with you - I'm not a data visualization guy. never have been. Not good with generating graphs, reading graphs, or converting data points to a meaningful graphing chart. With that in mind, I'm going to mark this as "help wanted" - if anyone runs across this issue that is interested in taking it on, please report here and let me know! I can provide assistance if needed, but there's a few other things in the backlog that I thing should take priority before I try to dive into a new graph implementation.

> As for drones; on current pyfa it's like a 'minimum damage' you see before you load the highs. That 'minimum damage' doesn't seem to change much if you play with sig or speed etc, & it should.

Still not sure what you mean here, do you mean the fact that the drones tend to have a steady line up until a distance point where it suddenly drops off? That is intentional, and that drop off signals the pilots Drone Control range. The idea is that drones would be able to apply their DPS to any target before that drop off *with respect to your ship*, not the distance from target to drone.

There's other funky things about drones in game that don't quite work well for pyfa DPS simulation, such as the fact that there are times when drones in game catch up to target, turn off their MWD (so they slow down), get a couple shots off, and then by then the target is getting away and so they must turn on their MWD again to chase and close distance. These kind of mechanics would be extremely difficult to reproduce in any meaningful way in pyfa, methinks; this is just one of those things that are better left to pilot understanding of game mechanics.

**Comment by mkosto** [comment]
I also notice that with the drones, right now when you load Ogres the DPS application for a target with a Signature radius of 1 m and traveling at 1000ms is more than 50% than a stationary 1km object.

This should be way lower, as it stands on paper heavy drones are better than medium and lights for shooting everything, even small fast targets.

**Comment by DarkFenX** [comment]
DPS/volley/damage inflicted over time graphs are in master now. As for drone application - we have no way to model that accurately, so few workarounds were used which will be desribed in release notes.
