### ISSUE TITLE
"live" build needs gui/bitmapLoader.py, file is actually gui/bitmap_loader.py

### ISSUE THREAD

**Issue by ExecutorElassus** [pyfa-org/Pyfa#1623]
## Bug Report
I'm using the gentoo install script that pulls directly from git. I'm at commit fb5849e43ee095d35f352ac432970889b2f5f687

When preparing source, I get the following error:
```
>>> Source unpacked in /var/tmp/portage/games-util/pyfa-9999/work
>>> Preparing source in /var/tmp/portage/games-util/pyfa-9999/work/pyfa-9999 ...
sed: can't read gui/bitmapLoader.py: No such file or directory
 * ERROR: games-util/pyfa-9999::gentoo failed (prepare phase):
```

### Expected behavior:
The file in …/work/pyfa-9999/gui/ is named bitmap_loader.py
The installer should be looking for this instead, or the file should have the sought-after name

### Actual behavior:
build fails at prep stage

### Detailed steps to reproduce:
see above

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
gentoo linux, 4.16.10 kernel.

**Comment by minlexx** [comment]
Error in ebuild file, where do dyou get that ebuild from? Pyfa does not provide any. That ebuild needs updating probably

P.S. I'm saying this again and again, such apps as Pyfa do not really need packaging, **especially** in Gentoo, where you can run it directly from source, updating with `git pull`? (For Linux look into Flatpak / AppImage maybe?)

**Comment by ExecutorElassus** [comment]
here's the traceback:

`Call stack:
 *     ebuild.sh, line  124:  Called src_prepare
 *   environment, line 4088:  Called edos2unix 'config.py' 'pyfa.py' 'gui/bitmapLoader.py' 'service/settings.py'
 *   environment, line 1005:  Called die
 * The specific snippet of code:
 *       sed -i 's/
`

There's nothing in the ebuild itself that lists that file. It just pulled everything from git. But if you can just run pyfa directly from `git pull`, I'll just do that.

**Comment by minlexx** [comment]
> where did you get that ebuild from? 

^^

> if you can just run pyfa directly from git pull, I'll just do that.

You can, just install required python modules from `requirements.txt` (which should be done by ebuild anyway): 
```
/usr/bin/python3.6 -m pip install --user -r requirements.txt
/usr/bin/python3.6 ./pyfa.py
```
or individually one by one. wxPython-4 might be a problem (or not, I don't remember now)

**Comment by blitzmann** [comment]
Thanks @minlexx for the responses!

@ExecutorElassus, as @minlexx mentioned, this isn't really a pyfa issue. There are a variety of folks around that manage distro-specific packages (arch, ubuntu, gentoo, etc). These are all third party and not official packages - I don't oversee any of them. With the switch to 2.x and the underlying changes to the requirement (python 3, wxpython 4, etc), a lot of these old packages broke. I gave ample, multi-month warning that this would be happening so that Linux packagers can get their stuff updated, but a lot of them have slipped through unfortunately.

I assume you're working off of this:
https://gitweb.gentoo.org/repo/gentoo.git/tree/games-util/pyfa/pyfa-9999.ebuild?id=7ad57335d01b572de6c6b180f1b5e8d8f86203b3

At first glance, this indeed is targeted towards to old 1.x codebase. I understand the want to have native packages, but until it's updated, I would suggest what @minlexx says - simply using `python3 -m pip`, and install the needed requirements, optionally in it's own virtualenv, and then run pyfa itself. wxPython 4.0b2 might be tricky - you have have to compile that one manually.

Closing this as it's not pyfa-specific, feel free to continue discussion

**Comment by minlexx** [comment]
https://gitweb.gentoo.org/repo/gentoo.git/tree/games-util/pyfa/pyfa-9999.ebuild?id=7ad57335d01b572de6c6b180f1b5e8d8f86203b3  <=- that ebuild is outdated, that's surely for python2, wxPython3, lots of requirements missing. That's a main problem of distro packaging - it is almost always outdated. @ExecutorElassus ask @ZeroPointEnergy who was author of https://github.com/gentoo/gentoo/pull/7367

P.S.
>  ZeroPointEnergy commented 26 days ago

>  ZeroPointEnergy commented 2 days ago

See, how many days are between updates of single PR. Easier to run from source than to rely on distro packaging...

**Comment by blitzmann** [comment]
Spoke a bit with @ExecutorElassus on Slack...

It's going to be difficult getting pyfa up and running on Gentoo. It seems that the main problem will be wxPython 4.0.0b2 - gentoo doesn't have an ebuild for wxP4 yet, and so the only option is to build from source. If one isn't used to building from source, this can be a pretty difficult hurdle.

Besides building wxP4, the only other option that I see is running pyfa.exe through WINE 😆 

It's been mentioned that there should be a Liunx wiki page that lists various distros and what's required to get the correct environment working for each distro. Might be time to set that up. :)

**Comment by blitzmann** [comment]
@ZeroPointEnergy, I forgot you were the maintainer of the gentoo one. We had that discussion on the proper licensing. Maybe you would know better than anyone:

How difficult do you think it would be to get an updated ebuild for both pyfa and wxPython 4.0.0b2?

**Comment by ZeroPointEnergy** [comment]
I'm aware of this problem. Unfortunately at the moment wxPython 4 is missing from the Gentoo repository and that is a requirement for Pyfa >2.0.0. (see https://bugs.gentoo.org/632602)

@minlexx as for that huge gap in the commits there was a licensing problem which had to be sorted and unfortunately I had some rl stuff which got in the way. Other than that I actually try to keep it updated ;-)

**Comment by blitzmann** [comment]
Thanks for the link @ZeroPointEnergy! I've added my own comment to hopefully push for some movement on it 😄 

Thanks for all your hard work trying to keep this up to date! 👍

**Comment by ZeroPointEnergy** [comment]
@blitzmann thanks, I appreciate the help :smile:
