### ISSUE TITLE
Titanium Sabot Incorrect ratios in Resistances Section

### ISSUE THREAD

**Issue by PantherSeraphin** [pyfa-org/Pyfa#1640]
## Bug Report

![image](https://user-images.githubusercontent.com/40214613/41311357-f3f74f82-6e7b-11e8-9008-08b8e7ee76ec.png)

### Expected behavior:
Titanium Sabot Should be near 75% kin to 25% exp 

### Actual behavior:
Currently showin 76.9% Explosive to 23.1% Kin

### Detailed steps to reproduce:
Right click resistances window and apply 

### Release or development git branch? Please note the release version or commit hash:
Release V2.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows Server 2012r2

**Comment by blitzmann** [comment]
```
select 
	t.typeName, 
	ta_kin.value AS Kin, 
	ta_exp.value AS Exp, 
	ta_kin.value/(ta_kin.value + ta_exp.value ) AS KinPerc, 
	ta_exp.value/(ta_kin.value + ta_exp.value ) AS ExpPerc
from invtypes t
join dgmtypeattribs ta_kin on ta_kin.typeID = t.typeID and ta_kin.attributeID = 117
join dgmtypeattribs ta_exp on ta_exp.typeID = t.typeID and ta_exp.attributeID = 116
where t.typename like 'Titanium Sabot%' and t.groupid = 83
```

```
"Titanium Sabot S"	"6.0"	"2.0"	"0.75"	"0.25"
"Titanium Sabot M"	"12.0"	"4.0"	"0.75"	"0.25"
"Titanium Sabot L"	"24.0"	"8.0"	"0.75"	"0.25"
"Titanium Sabot XL"	"48.0"	"16.0"	"0.75"	"0.25"
````

At first I was going to suggest that it was set to the average of the ammos. But a quick query shows that you're 100% right - its' all a 75%/25% split throughout.

Looking back, the original PR that added these default values was #639. It looks like the values were scraped against the Chukkers website. It isn't immediately clear where these ammo profiles come from though, if they are from some sort of calculated stat from Chukkers or elsewhere.

I'm not sure if I really want to go through all these and manually check TBH. If anything, It would be scripted out (or, better yet, generated on demand so that all ammo types are automatically represented in the menu). But the time it would take wouldn't be worth it in my opinion (not that it's hard, it's just busy work)

As a work around, you can change these values yourself: Window > Damage profile, select the Titanium Sabot one, and edit it to be 75/25. OR, fun fact, you can fine any ammo in the market and right click -> set as damage profile, and it'll use the literal values from that item.

**Comment by DarkFenX** [comment]
It's not  that hard to go through them manually. Using this request:
```
select 
	t.typeName,
	ta_em.value AS Em, ta_thr.value AS Thr, ta_kin.value AS Kin, ta_exp.value AS Exp,
	100*ta_em.value/(ta_em.value + ta_thr.value + ta_kin.value + ta_exp.value) AS EmPerc, 
	100*ta_thr.value/(ta_em.value + ta_thr.value + ta_kin.value + ta_exp.value) AS ThrPerc,
	100*ta_kin.value/(ta_em.value + ta_thr.value + ta_kin.value + ta_exp.value) AS KinPerc, 
	100*ta_exp.value/(ta_em.value + ta_thr.value + ta_kin.value + ta_exp.value) AS ExpPerc
from invtypes as t
inner join invgroups as g on t.groupID = g.groupID
join dgmtypeattribs as ta_em on ta_em.typeID = t.typeID and ta_em.attributeID = 114
join dgmtypeattribs as ta_thr on ta_thr.typeID = t.typeID and ta_thr.attributeID = 118
join dgmtypeattribs as ta_kin on ta_kin.typeID = t.typeID and ta_kin.attributeID = 117
join dgmtypeattribs as ta_exp on ta_exp.typeID = t.typeID and ta_exp.attributeID = 116
where t.typename like '%Meson%' and g.categoryID = 8
```
I updated ammo profiles in 843ced15bf535ba0dff3b868b6f60886fda42f11. Please note that exotic plasma charges have different ratios across sizes, so averaged ratio was used.

I also changed database reimport logic to update values if there was such entry in database. While it may delete user data and shitty approach, being unable to update profiles without wiping out user data is much worse imo.
