### ISSUE TITLE
Set default level for character

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#165]
We already have the ability to set default level in the DB which will populate skills based on this. Support this in the UI. understandably this won't take care of any skill prereq trees, but will probably will make it easier to people to make fits for newbies set to all 3 and whatnot...

I've started this, but ran into an issue. If you have, say, lvl4 set as default char, then updated via API, the skills that aren't present on character sheet aren't dumped (even tho we issue a `del self.__skills[:]` when updating API).

**Comment by Ebag333** [comment]
>but will probably will make it easier to people to make fits for newbies set to all 3 and whatnot...

@blitzmann This isn't a thing.

There's not really any benefit for designing ships under all 3 instead of all 0.  When designing ships for newbies, you need to design to a specific set of skills.

Currently we have:
1. 0 skills (base stats).
2. Starting skills (which are race specific)
3. Specific player skills (which we know nothing about unless imported 
4. V skills (max)

Soon we will have alpha clones, which people will want to design fits for.  For Alpha clones we will have:
1. Starting Skills for Alpha Clones
2. Max Skills for Alpha Clones

I don't know offhand if starting skills for Alpha clones will match that of the starting skills for non-alpha clones.  I hope/suspect so.

CCP has said that they plan on publishing the alpha clone info to CREST (or somewhere), so we can fetch it and dynamically build the character.  It will also change over time (highly likely) as CCP adds/removes skills to account for the current meta (too many alpha clone ganking ships is a huge concern).

Anyway, as someone who regularly designs fits for brand new players, I've created my own Gallente starting character, but it'd be _fantastic_ to have this as a default char in Pyfa.  Unfortunately for Pyfa, this has very little to do with `all skills to 1/2/3/4/5` as the skills will be all over the map.

If I had a char with all skills to 3, it'd be _waaaay_ off from a genuine starting character.

I would wait to see what CCP publishes (to CREST or wherever), and then write something to scrape it from the endpoint and add/update the character in Pyfa.

**Comment by blitzmann** [comment]
haven't looked at this issue for almost two years. Gonna close it. A lot of what ebag said makes sense. Not only that, but pyfa has had the ability to modify skills temporarily and save as a new character for some time (`Change Affecting Skills` feature), which could help with this.
