### ISSUE TITLE
Instalation on linux

### ISSUE THREAD

**Issue by serdurarara** [pyfa-org/Pyfa#1654]
Hello

i am new in the linux world .
i am trying to install the pyfa on Ubuntu 16.04 LTS with no success.. i cant find any useful info online..
could someone help me install it pyfa?

thanks in advance

**Comment by blitzmann** [comment]
There's various ways, you can try to find someone that creates a deb package for pyfa, though I don't know of any off the top of my head.

You're going to have to download Python 3.6. That should come with a program called `pip`, which is Pythons package manager. 

Then, you need to install wxPython 4.0.2 (this was just released a few days ago, and will be the minimum version going forward). More info found here:
https://wxpython.org/pages/downloads/index.html

From there, download everything else in `requirements.txt` via `pip`. Then run pyfa via `python pyfa.py`

I can provide limited support to get you up and running, but with Linux it's kind of assumed that folks know how to do their research and get up and running themselves, considering it's more of an advanced OS.

**Comment by serdurarara** [comment]
i have seen in a few threads this "requirments.txt" file.. i cant find it in the "https://github.com/AdamMajer/Pyfa/releases".. i found this link in the "readme" file. i know that linux is an advanced OS.. i am trying to learn :)

**Comment by blitzmann** [comment]
>  AdamMajer released this on Mar 16, 2016

So those are old Debian package builds, doesn't seem to be maintained any longer. The README really needs to be updated, just haven't had time to do so.

You will have to download the pyfa source code. there are two ways to do this: found under the release assets: https://github.com/pyfa-org/Pyfa/releases or you can use git, which is a version control software. Using git, it's easier to get in-development stuff, but it's also more complex and unnecessary if you're not a developer or want to keep up with bleeding edge.

Once you have the source code, you'll have `requirements.txt`. You might want to edit out the wxPython entry in `requirements.txt` since doing it through `pip` will actually compile it, which could take a few hours. So remove it from requirements, and then run `python3 -m pip install -r requirements.txt `, then you could install wxPython using the information I provided in the previous post.

After that, you're python environment should be sufficiently set up. All you need to do to run it is navigate to the pyfa source code and run `python3 pyfa.py`

**Comment by serdurarara** [comment]
oooooh i get it now m8 :D thaaaanks a lot!!!

**Comment by serdurarara** [comment]
hmmm i run "python3 -m pip install -r requirements.txt" and i tried to run "python3 pyfa.py" but i get the following error message 

Traceback (most recent call last):
  File "pyfa.py", line 27, in <module>
    import config
  File "/home/marios/Downloads/Pyfa-2.2.0b1/config.py", line 4, in <module>
    from logbook import CRITICAL, DEBUG, ERROR, FingersCrossedHandler, INFO, Logger, NestedSetup, NullHandler, \
ImportError: No module named 'logbook'

i tried to installed it manually with "pip install logbook" it succeds but when i am runing the "python3 pyfa.py" i get the same error :/

**Comment by minlexx** [comment]
Not `pip install logbook`, try `pip3 install logbook` or better `python3 -m pip install --user logbook`

**Comment by serdurarara** [comment]
same thing.. :/

**Comment by pezz** [comment]
Just a side question if I may: when do you expect wxPython 4.0.2 to become the minimum version?

**Comment by blitzmann** [comment]
Hi guys, back from a mini vacation (read: Steam Summer Sale >_>). Sorry I kinda bailed on this thread lol

@serdurarara were you able to get this resolved on your end? I'm going to close the issue since it's not pyfa-related (instead, it has to do with your environment), but we can still discuss the situation if you're still having difficulty. I do think, though, that it's going to have to be a bit of research on your part as to how these things come together, atg least until someone somewhere gets a debian package going for pyfa 2.x :)

> Just a side question if I may: when do you expect wxPython 4.0.2 to become the minimum version?

Yeah, I was pushing hard for Robin to release 4.0.2. I'm going to be evaluating it (apparently there is now 4.0.3?), and probably get it included in the next release after tomorrow. That being said, pyfa should work with it if you run pyfa from source and want to upgrade it yourself. :)
