### ISSUE TITLE
Cannot change ship skills of ships of dual factions

### ISSUE THREAD

**Issue by ZweisteinT** [pyfa-org/Pyfa#1661]
When you try to develop a Fitting for, lets say Nightmare or rattlesnake, you can:

right click -> Change Ship Skills ->

but you can only change one of the Battleship Skills there. For the Rattlesnake i can change Caldari Battleship, but not Gallente Battleship.

**Comment by burnsypet** [comment]
Hey, the reason that Gallente Battleship does not appear when you try to change the ship skills is because it does not affect the hull. Gallente Battleship affects missile damage, which is applied to the charges (the missiles). 

If you add a missile launcher then add a thermal or kinetic missile and right click > change charge skills then you will see Gallente Battleship listed:

![image](https://user-images.githubusercontent.com/6990224/42389093-7c445be8-813f-11e8-9905-0e1ef999e821.png)

**Comment by blitzmann** [comment]
Indeed, as @burnsypet put it, the skills that affect an item are actually tracked by literal afflictions. Even though the hull "uses" a skill for a role bonus, that skill never touches the hull, and so the hull never knows about it. The reasons behind this are complex and have to do with the way that the effect system currently works. As of this moment, this is the way it's going to remain. There have been efforts in the past to improve on this, without much luck. The main problem is that the "Change skills" menu was largely tacked onto the fitting engine a couple of years ago, when the engine wasn't really designed with that kind of thing in mind, so to go back and make sure these certain skills "register" with the hull would be a fairly large amount of work.
