### ISSUE TITLE
Cap Battery wrong negativ value and color

### ISSUE THREAD

**Issue by Errious** [pyfa-org/Pyfa#1686]
As you can see in the Pictures the value is mutated negativ but in pyfa i get only positiv result.

![image](https://user-images.githubusercontent.com/3904767/42856346-d64520f6-8a12-11e8-917b-bca9e667606b.png)

[in pyfa](https://i.imgur.com/R6FkZ59.png)
![image](https://user-images.githubusercontent.com/3904767/42856349-db56da76-8a12-11e8-88c7-3db98bb75d57.png)

**Comment by blitzmann** [comment]
Hrm, interesting... That stuff is determined by a `highIsGood` attribute, I wonder if it's jacked in the EVE data.

What is the base value for that attribute?

**Comment by blitzmann** [comment]
So I think it's CCP that is actually bugged in their UI. The lower the value, the more resistance you get to cap warfare (reduces the effects of capacitor warfare modules by -x%).

I will raise a bug report with CCP about this.

**Comment by blitzmann** [comment]
Can you give me the base module you sued and which mutaplasmid was used on it?

**Comment by blitzmann** [comment]
@ISDAstaris can you verify if this has been fixed in game?

**Comment by Errious** [comment]
No it is not...

Am Mi., 22. Aug. 2018 um 03:59 Uhr schrieb Ryan Holmes <
notifications@github.com>:

**Comment by ISDAstaris** [comment]
This has been resolved internally and will hit Sisi/Tranquility with an upcoming release.

**Comment by blitzmann** [comment]
👍 Thanks @ISDAstaris !

**Comment by ISDAstaris** [comment]
https://hoboleaks.space/Singularity_1380494-1381012.html#highlight1536354093413,1 ;-)

**Comment by blitzmann** [comment]
@ISDAstaris I do have a question on this - the change noted tells us now that the higher the number the better it is. However, in game, it is actually the opposite as far as I'm aware - the lower the number (the more negative), the better it is. So `-28%` is better than `-17%`, because it will reduce the energy warfare effects by that amount.

So, I'm wondering if 
1) This wasn't the proper fix? Or
2) `highIsGood` is based on the absolute value, not the literal value, (so, `|-28%| => 28%` is better than `|-17%| => 17%`) . If this is the case, then I think I may have a few things to fix within pyfa...

**Comment by ISDAstaris** [comment]
I'm unsure how this attribute has been authored and how it works internally. You might want to poke one of the devs about more details, for example on Tweetfleet slack.

**Comment by blitzmann** [comment]
Seems to me that the EVE UI was actually bugged, and instead of fixing the UI, they "fixed" it by just flipping that attribute around... will try to get with a dev on tweetfleet soon about this

**Comment by blitzmann** [comment]
Actually, the `highIsGood` attribute seems to have been fixed according to recent data, still not sure if this was actually fixed in the EVE client, but assuming it was. Going to close this issue :)
