### ISSUE TITLE
Feature Request - Tabs indicator of items presence

### ISSUE THREAD

**Issue by xkite25** [pyfa-org/Pyfa#1717]
Awesome tool !!! :) Thanks for your time in developing it !!

A small feature I think would be helpful for users on all tabs headers (Drones, Fighters, etc.) :

It would be great for each tab header to have an indicator along the tab name stating whether each tab has some items or not so that when a user opens a fit he knows he should have a look at it. Obviously when creating a fit, adding items in one of those tabs would add the indicator to the tab name.
Indicator could be a color and/or the number of items in the tab for example ...

Thanks a lot and keep going !!!
AZ

## Bug Report
N/A

### Expected behavior:
N/A

### Actual behavior:
N/A

### Detailed steps to reproduce:
N/A

### Fits involved in EFT format (Edit > To Clipboard > EFT):
N/A

### Release or development git branch? Please note the release version or commit hash:
Pyfa 2.4.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7

**Comment by blitzmann** [comment]
Interesting idea... I can see this as being an optional thing people can turn on in the settings. There's a few technical hurdles to overcome with it, as tabs don't generally update their names (the exception being fit rename, but I think to do it is a convoluted process)

There are a few questions on how it might be done though - if you have two stacks of 5x Warrior IIs, is that considered 2, or 10? Or do we only count the active drones (in which case, it's pretty much the same as the drone bandwidth which is already visible)?

Open to ideas here. This is going to be one of those things that I can get to on off time, but I'm always strapped for that lol, so might also be picked up by someone else. But we should have a discussion on the requirements here so that it's unambiguous what needs to be done. :)

**Comment by xkite25** [comment]
@blitzmann 
Thanks once more for your comments and approach of this feature.

In my view this feature was not an option, lol, as it gives a better "readibility" but why not after all ... :)

As for the questions you are mentioning, I would consider the following approach:

Approach 1: Basic
- reduced development for you (I guess)
- output : basic information i.e. there is something in this tab
In this option there is no count of items in each tab. Just a colored tab indicating to the user that there are some items in there.

Approach 2 - the cherry on the cake - maybe to consider according to feedbacks received ...
- a bit more if not much more dev for you
- more detailed info indicating the number of items. In this case, as you questionned, how do we manage stacks ? Once more I would go for the easy solution which is just the number of items. 
Example 1: 
- 1 stack of 5 mining drones II 
- 1 stack of 5 warriors II 
then the tab header would display "Drones 10" or "Drones (10)" or "Drones [10]" 
I'd rather go for the last one with the brackets ... but this is purely esthetical :)
Example 2:
- 1 stack of 2500 void S 
- 1 stack of 2500 null S 
then we would end up with a tab name looking like "Cargo [5000]"

I realise there is another reason why this feature is worth having in my view:
This is the case of the command tab where one can check the impact of external effects provided by other ships fits to the current fit (great tool by the way !!!). Having an indicator on the "Command" tab remembering the user that the dps values, mining values or resistances values he is reading are subject to the "Command" tab would be useful I believe. 
Same for "Projected" by the way ...

Remain open for ideas / discussion.
I would even offer my help for coding but I fear my 20 years without touching a line of code would be more detrimental than nothing else ...

**Comment by DarkFenX** [comment]
Without seeing this ticket, I actually implemented everything you wanted in here. See release 2.11.1.

**Comment by xkite25** [comment]
Thanks a lot @DarkFenX !!!!
