### ISSUE TITLE
Bugs on Boosters and Deployable Structures

### ISSUE THREAD

**Issue by xkite25** [pyfa-org/Pyfa#1718]
## Bug Report
- Boosters
It seems like not all the boosters available IG are visible ...

- Deployable structures. 
It seems like these are not exported correctly and hence not recognized and imported by Eve IG Fitting Tool

### Expected behavior:
For Deployable structures:
Deployable structure imported in IG Fitting Tool

### Actual behavior:
For Deployable structures:
Here is the flow I am using :
--- Add a mobile depot to a fit in the cargo tab.
--- Export to EFT
--- Import in EVE
When importing here is the message received :
 
"The following entries in the import data could not be interpreted:
Mobile Depot x1
'Wetu' Mobile Depot x1
'Yurt' Mobile Depot x1"

If the fit does not have any other items it is not imported at all (which makes sense). If it has other items then these are imported but not the deployable structures

### Release or development git branch? Please note the release version or commit hash:
Pyfa 2.4.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7

**Comment by blitzmann** [comment]
> If the fit does not have any other items it is not imported at all (which makes sense). If it has other items then these are imported but not the deployable structures

This is a limitation with the in game client. pyfa allows folks to store basically anything within their cargo, however I believe EVE only allows certain things (ammo I think, and maybe a few other categories). So yeah, when you import it, EVE doesn't know what to do with those items and simply discards them.

There's not much we can do here. :)

So that covers deployable things. Now...

> It seems like not all the boosters available IG are visible ...

Can you give an example of a booster that is in game but isn't in pyfa? There was recent changes to boosters and their market tree, so it's very possible there's a few issues with it still, but I need to have a bit more information on this. :)

**Comment by blitzmann** [comment]
@xkite25 would you be able to provide any more details as per my previous message?

**Comment by xkite25** [comment]
@blitzmann 
Apologize, I was away with no connection for a week, jsut came back ...

Thank you for your answers/comments.

Boosters:
Indeed, you are right. I just started my pc and launched pyfa and boosters are ok now although I am sure it was not the case before I leave for a week. I guess I had to restart pyfa whatever reasons ...

Deployable:
I understand the issue is on the IG client so on CCP side. Thanks for the explanation. 
Maybe CCP should do something about it (I don't know if you have any direct relations with CCP team). After all, deployables are like ammo, drones or any other items, they can be stored in the cargo hold of ships. So from my point of view it would make sense to be able to save fits with them ... Now from the implementation perspective, I have no idea about the feasibility ...

Thanks

**Comment by blitzmann** [comment]
> Indeed, you are right. I just started my pc and launched pyfa and boosters are ok now although I am sure it was not the case before I leave for a week. I guess I had to restart pyfa whatever reasons ...

The latest version of pyfa didn't have proper market groups, and there was a recent re-occurrence of an issue which causes pyfa to use an old, cached database file, so... it may very well have been that.

> Maybe CCP should do something about it (I don't know if you have any direct relations with CCP team). 

I have a couple of contacts, mostly for when I have questions on how new mechanics work so I can implement them, but no game design pull lol. The reason is most likely because the fitting window is driven by the DNA format IIRC, and the DNA format is very, very limited in what it is able to do. It's basically a list of IDs and their qty, so if you had, say, a web fitted to your ships, and a web in your cargo, it wouldn't know how to break those two up. It knows how to do that for ammo because, obviously, ammo can't be fitted, so it goes into "cargo". I'm sure they could also do that with non-module items like deployable structures, but I'm sure there's a lot of assumptions surrounding the idea that it's ammo only. 

I suspect this will never be fixed on CCPs side due to the niche requirements and the fact that it's probably entangled in so many other parts of the codebase that it's not really lucrative to "fix". Just my hunch on it though.
