### ISSUE TITLE
Pyfa starts and open fits very slow

### ISSUE THREAD

**Issue by shark200300** [pyfa-org/Pyfa#1752]
So, my pyfa worked fine, untill something happened and this started
It takes about 1 minute to start pyfa and 20s to open fit
This installision of pyfa worked fine previously, so there is a problem on my side probably. but i cant find what is it.
I tried to completly reinstall pyfa and phyton. and starting with empty database. didnt help
Here is logs
https://pastebin.com/Mn86v0jc

**Comment by blitzmann** [comment]
What was your previous version of pyfa?

**Comment by shark200300** [comment]
i installed them as they go so i guess it is v2.4.0
Once again - my version was working ok untill recently, than i guess some OS update/installed program/changed setting/etc did something. I just want idea where to look :)

**Comment by blitzmann** [comment]
Yep, I'm seeing your logs - shows about 1 min to start up and 20 seconds to create a new fit... odd.

Since we switched to 2.0x, we've gotten reports that pyfa can start abnormally slow on some machines, for unknown reasons. However, they also report that it seems to run fine after initial loading...

Beware, lots of questions incoming. Please answer as many as you can :)

Does this happen for every fit you create? What about loading an existing fit? What about adding modules, etc, does it take forever to update the stats? What about searching for items and the like? Do you use the .exe installer? Where do you install is to (program files/desktop/etc)? It almost seems like it could be a performance issue with the `eve.db` database...

Also, you can start pyfa with a `-p` flag to get it to print out a profile - I can then use that to analyze which things seems to be slowing it down. Use it with a path to save the file, like:

`pyfa.exe -p "c:\users\User1234\Desktop\"`

That should spit out a file that might be useful.

**Comment by shark200300** [comment]
Does this happen for every fit you create? - **Yes, 20s for every fit**
What about loading an existing fit? - **Same as above**
What about adding modules, etc, does it take forever to update the stats? **No, after fit is loaded, everything works fine**
What about searching for items and the like? **Same as above**
Do you use the .exe installer? **Yes**
Where do you install is to **C:\pyfa**

Now to the fun thing
Yesterday, despite slowness i spended few hours in pyfa editing some fits
After this i turned off pc. Today i started with adding flag as you told, and to my great surprise pyfa started normally and issue is gone. Than i restored my old DB, rebooted pc and everything still fine.
So either just fact that i spended some time in pyfa, or adding flag did somethig.

**Comment by blitzmann** [comment]
Thanks for the answers! 

> So either just fact that i spended some time in pyfa, or adding flag did somethig.

Well that's odd... it now works fine even without the flag?

> Where do you install is to C:\pyfa

The next thing I would suggest if it starts again is to try the zip download on your desktop instead of the installation package.

**Comment by blitzmann** [comment]
If I don't here any response about it reverting to weirdness, gonna close this in a few days :)

**Comment by shark200300** [comment]
> Well that's odd... it now works fine even without the flag?
> 
> >

Yes, also i immediaty removed flag after successful launch, and it continued to work fine.
