### ISSUE TITLE
Can't drag/drop implants to Implants "Additions" window

### ISSUE THREAD

**Issue by feyyd** [pyfa-org/Pyfa#1778]
## Bug Report
Unable to drag implants from market to the Implants window with "Use Fit-specific implants"

### Expected behavior:
Drag and drop functionality to add implants from Market Window.

### Actual behavior:
Circle with line through it prevents Drag and Drop

### Detailed steps to reproduce:
Use Fit-specific implants.  Drag an implant from market browser to the window, prevented from adding.  Must double click to add.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
All

### Release or development git branch? Please note the release version or commit hash:
2.5.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
Apologies if this is duplicate or was discussed before, I kind of remember talking about this but could be mistaken.

**Comment by blitzmann** [comment]
Nice find, I think this would be an easy fix, will have to check tonight :)

**Comment by blitzmann** [comment]
Ah, so this has never been a thing. I was thinking it was forgotten about when we converted to command pattern. I think it might be difficult due to having the fit/character switch for implants - although, we could always consider it to be the same as double-clicking implant (change to fit and add like normal)
