### ISSUE TITLE
Modulated (Deep Core) Strip Miner II yield unaffected by Mining Laser Upgrade when importing

### ISSUE THREAD

**Issue by YraelOramara** [pyfa-org/Pyfa#1790]
### Expected behavior:
Mining yield increased for each Mining Laser Upgrade active when fit is imported.

### Actual behavior:
No increase in yield at all, but CPU usage still increases.

### Detailed steps to reproduce:
Import any fit with a Modulated Strip Miner II or Modulated Deep Core Strip Miner II slotted. Removing and readding any/all modules does not fix the issue.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
Any barge/exhumer with any of the above modules slotted. Example:

```
[Covetor, Mining]

Mining Laser Upgrade II
Mining Laser Upgrade II
Mining Laser Upgrade II

[Empty Med slot]

Modulated Strip Miner II
Modulated Strip Miner II

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]
```

### Release or development git branch? Please note the release version or commit hash:
Release v2.5.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Tested on Arch Linux 4.18.16 and Windows 10

### Other relevant information:
May be related to https://github.com/pyfa-org/Pyfa/issues/1702

**Comment by blitzmann** [comment]
Mining turrets have always been a bit shoddy in pyfa, specifically the ones that take the crystals. Part of this is because pyfa devs have always been geared more towards PVP (so, I don't actually know mining mechanics very well), as well as the calculations are a bit convoluted because you have normal mining vs mining whatever the crystal is supposed to mine.

FWIW, the laser upgrades indeed increase the mining amount attribute of the strip miners. Unfortunately, I think pyfa is displaying some other attribute? I'll have to dig into this a bit more.

**Comment by blitzmann** [comment]
So, I was incorrect, it's not applying to the proper attribute.

Strip miners have two attributes of interest: `miningAmount` and `specialtyMiningAmount`. These two values are the same if there isn't any charge loaded. When there is a charge loaded, the specialty mining amount is supposed to increase 1.75x. 

The problem, for pyfa, is that everything seems to only affect the `miningAmount` attribute only, and the `specialtyMiningAmount` is not getting any bonuses. The reason why it's getting some bonuses is because the value is actually copied from `miningAmount` after it has received some of it's bonuses, but before other bonuses are applied. See [this effect](https://github.com/pyfa-org/Pyfa/blob/master/eos/effects/crystalminingamountinfo2.py))

The solution here, I think, is to do the attribute value copy on a later runtime. This allows all bonuses to apply to `miningAmount` first (skills, mining laser upgrades, etc), and then one of the last things it will do is set `specialtyMiningAmount = miningAmount`. Once this happens, any effect that boosts `specialtyMiningAmount` will be applied to the correct value (and in this case, there's only one effect that is applied to `specialtyMiningAmount`, and that's the crystals boost of 1.75x).

> Tested on Arch Linux 4.18.16 

Please checkout the latest master, or download the latest source in a zip, and try out the fittings. They should now look proper :)

**Comment by YraelOramara** [comment]
Looks good; nice work :+1:

(and before anyone gets the wrong idea, I'm not into mining either 😜)
