### ISSUE TITLE
Multiple Abyssal effects can be applied

### ISSUE THREAD

**Issue by DanFraserUK** [pyfa-org/Pyfa#1794]
As the title says, simply, one can apply multiple abyssal effects to a ship fitting in the projected tab.

**Comment by blitzmann** [comment]
This is somewhat by design. While you can only be in 1 weather environment, there are various localized environments that can happen at the same time. But IIRC, there isn't really a good way programatically to differentiate the localized from the weather (think I had to  hard code that to separate the menus).

I'll take another look at this soon, but for now gonna consider this low priority :)

**Comment by blitzmann** [comment]
Got this fixed. All environmental effects that are not under the localized effects is now exclusive. Also fixed a couple weird things with undo/redo happening when trying to undo application of system effects
