### ISSUE TITLE
[MINOR] Assertion error in debug log

### ISSUE THREAD

**Issue by nickPietrass** [pyfa-org/Pyfa#1810]
## Bug Report:
When opening a new fitting view, fittingView fails an assertion in bitmap.cpp
pyfa needs to be running with the --debug option

### Expected behavior:
Clear debug log

### Actual behavior:
```
------------------ new fitting view -------------------
<gui.builtinViews.fittingView.FittingView object at 0x7f8865603ee8>
###################### Created new view:<gui.builtinViews.fittingView.FittingView object at 0x7f8865603ee8>
====== Fit Selected: <gui.builtinViews.fittingView.FittingView object at 0x7f8865603ee8>True
[2018-11-29 10:01:03.106810] CRITICAL: gui.builtinViews.fittingView: Failed to make snapshot
[2018-11-29 10:01:03.106998] CRITICAL: gui.builtinViews.fittingView: C++ assertion "bmpData->m_pixbufNoMask" failed at ./src/gtk/bitmap.cpp(1262) in SetSourceSurface(): no bitmap data
```
### Detailed steps to reproduce:
Open any fit, open a new fittingView

### Fits involved in EFT format (Edit > To Clipboard > EFT):
any

### Release or development git branch? Please note the release version or commit hash:
latest  791b6e1 & latest stable release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Arch Linux python3 & python3.7

### Other relevant information:
Testing it on the windows release later, but should happen everywhere

**Comment by blitzmann** [comment]
Did this only just start happening with the latest commit? Do you know if it was happening with previous releases?

@DarkFenX @minlexx since you guys are mainly Linux folks, do you get the same error? I can check tonight as well on Windows / OSX / maybe Linux

Also, @nickPietrass, while I don't think this is the cause, pyfa only supports Python 3.6. it hasn't been tested with 3.7. Additionally, which version of wxPython do you have installed?

**Comment by blitzmann** [comment]
Additionally, I rarely run without debug option, but all that does is set a config variable that we use to display additional things like typeIDs, fitID, etc. Not sure why it would affect anything :/

**Comment by nickPietrass** [comment]
Just randomly ran across it today, will update later with more test data from 3.6 and windows release.

**Comment by blitzmann** [comment]
@nickPietrass have you run across this again since?

It's in the make snapshot code, which to be honest, isn't that important and I think it rarely ever used. It doesn't affect the actual usage pf pyfa. It's probably some race condition or the like where a bitmap image wasn't yet available.

let me know if you continue to get this error, can reopen issue if needed
