### ISSUE TITLE
Add button to optimize fit price

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1841]
During DB build time for each item type find

1. Direct replacements (same attributes, besides maybe meta lvl, so like domination and dark blood disruptors)
2. Better replacements (using highisgood)

Add some UI elements which can do price optmization by

1) doing replacements for strictly similar module, which is cheaper
2) doing replacements for strictly similar or better module, which is cheaper

Price should be force refreshed for all involved items, if it's older than 1-2 hours. 

I think I can implement backend support pretty easily (except for undo/redo stuff), what do people think about this feature in general and about how it should be handled on UI side?

**Comment by blitzmann** [comment]
I really like this idea. On the ui can be a menu item in the edit menu which displays a list of modules with a list of replacements, if any, and show before and after price ( or maybe isk saved price) Maybe I can mock up an idea soonish

**Comment by DarkFenX** [comment]
It should take a while to optimize as it takes some time to fetch the prices, so I am unsure it you can show it as menu items. I was more thinking about button in prices stats panel.

**Comment by blitzmann** [comment]
Ah yeah, I was envisioning a window that, when opened, would go and fetch the prices of similar items for a fit, while displaying a loading message until prices have been updated (if needed). Basically a triggered fetch. Also, when I say menu item, I mean on the main pyfa window Edit menu for the fit as a whole, not individual module context menus.

Having it done automatically could work too, like you described. Price fetching should already be done in another thread so I think most of the work there is finished. Would just have to include the similar items with the actual items in the price request and they'll be updated if need be. Once prices have been fetch, can have a visual cue somewhere showing that optimizations are available. Cache threshold is 24 hrs instead of proposed 1-2, which I think is fine but we could tweak pretty easily if needed.

The delay that you talk about, is that a delay in the context menu showing up or a delay in the item stats window showing after you click the Stats menu item? I know that the context menu can take some time to show when it has lots of menus in it (variations, affecting skills, etc), it's always been a pain point, but dont think it's due to price fetching as I'm almost positive that prices are always collected in another thread. :)

**Comment by DarkFenX** [comment]
You probably misunderstood me. I think that optimization process should be automatic, but triggering it should be manual. So that user presses button, and then pyfa handles everything automatically - price fetching, replacing etc. And if price is older than 2h by the moment user presses on optimization button, then it has to be re-fetched despite having normal 24h validity period. For some items price is quite volatile, as well as availability (eg TS small emp smartbombs).

Use-case would be: I have a fit, i want to buy it in Jita. Right before doing so i press optimize button, copy to multibuy and get all the items i wanted in-game.

From time to time I am doing this optimization manually which is very inconvenient.

**Comment by DarkFenX** [comment]
Implemented database generation logic in price_optimize branch.
