### ISSUE TITLE
Feature Request: Add missing skills column and fill it with the needed skills for each module

### ISSUE THREAD

**Issue by Tharnadar** [pyfa-org/Pyfa#1846]
As said in the tile, would be nice to have column with the missing skills for each module, this would help to tweak the fitting in order to minimize the minimum skills to use the fit.
Thank you

**Comment by blitzmann** [comment]
Hey there,

I'm not sure I understand what you're asking for. You mean a column on the fitting window where it shows the modules, ammo, states per module, etc?

I think we may already have something like this. If you don't have the skills to fly a specific fit, the skill book in the top right turns red. Hovering over it shows you which skills are missing:

![image](https://user-images.githubusercontent.com/3904767/52485600-3fa70300-2b87-11e9-8d27-968b4b8036b7.png)

Additionally, right clicking the skill book will give you the option to grant the missing skills to the character.

![image](https://user-images.githubusercontent.com/3904767/52485631-53eb0000-2b87-11e9-93d6-59055a219b8f.png)

When granting missing skills, these skill level changes are temporary (as noted by the asterisk on the character). In order to save them, you'll have to go into the character editor and save the character. The reason behind this is so that you can edit a character like this to see what happens, but not make the changes permanent. 

Does this address what you're looking for?

**Comment by Tharnadar** [comment]
> A picture is worth a thousand words
[https://pasteboard.co/I0dWdCT.png](url)

**Comment by blitzmann** [comment]
@Tharnadar 

There's an option to change the format of the tooltip that shows skills per item, instead of just the skills:

![image](https://user-images.githubusercontent.com/3904767/52515452-c260aa00-2be9-11e9-9bb6-528492354cca.png)

"Compact skills needed tooltip"

![image](https://user-images.githubusercontent.com/3904767/52515481-22575080-2bea-11e9-8be5-16244a26ca04.png)

I think adding this information to the fitting window itself is an interesting idea, however adding a new column is a bit extreme for this case as it's not always relevant, and then there's the problem of what happens when there's multiple skills missing, and those skills require skills, etc. I'm hoping this option for the tooltip works for you to display which items need which skills.

**Comment by Tharnadar** [comment]
Awesome, that's all I need. thank you mate, you did a great job!
