### ISSUE TITLE
Segmentaion fault after clicking on market group

### ISSUE THREAD

**Issue by sincomil** [pyfa-org/Pyfa#1855]
## Bug Report
After  successful pyfa start you can browse created and stored fittings, but if you click on "Module Market Group" or even simply click on any of market groups you will get immediately segfault

### Expected behavior:
User should be able to view market group items to create a fitting

### Actual behavior:
Segfault + Exit

Pyfa-2.7.0 release
Arch Linux + VENV pip-installed packages:
$ pip list
Package         Version
--------------- ---------
asn1crypto      0.24.0
beautifulsoup4  4.6.3
certifi         2018.8.24
cffi            1.11.5
chardet         3.0.4
cryptography    2.3.1
cycler          0.10.0
diskcache       3.0.6
idna            2.7
kiwisolver      1.0.1
Logbook         1.4.0
markdown2       2.3.5
matplotlib      2.2.3
numpy           1.15.1
packaging       17.1
pip             18.0
pycparser       2.18
pyparsing       2.2.1
Pypubsub        4.0.0
python-dateutil 2.7.3
pytz            2018.5
PyYAML          3.13
requests        2.19.1
roman           3.0
setuptools      39.0.1
six             1.11.0
SQLAlchemy      1.2.11
urllib3         1.23
wxPython        4.0.3

$ pacman -Q | grep wxgtk
wxgtk-common 3.0.4-2
wxgtk2 3.0.4-2
wxgtk3 3.0.4-2

It should be some how influenced by last update with pacman -Suy, because Pyfa 2.7.0  was working before last update
[pyfa.log](https://github.com/pyfa-org/Pyfa/files/2879928/pyfa.log)

**Comment by blitzmann** [comment]
>It should be some how influenced by last update with pacman -Suy, because Pyfa 2.7.0 was working before last update

This leads me to believe it's your environment, and not an issue with pyfa. Unfortunately, with distros like Arch Linux with a almost bleeding edge rolling release, libraries are going to break. There's not much we can do about that. I would double check that your python package versions match up with requirements.txt. i see multiple packages that are newer than what pyfa might expect (though I'm reluctant to say that's the reason for this issue)

**Comment by sincomil** [comment]
I understand that it is very difficult to create such software like pyfa to be compatible with rolling release Linux distros. But I need a little help to get more info about what causes this particular segfault, because a can't figure out what packages was updated to. Running pyfa with debugging and logging options does not helps as you see. Is it possible to catch out a library that throwing an segfault?

**Comment by blitzmann** [comment]
Unfortunately I'm not a linux guy. I know enough to be dangerous,  but low level debugging is out of my scope.

The first thing that pops out is wxgtk being 3.0.4, while your wxpython is 4.0.3 which I think is supposed to be built for wx 3.0.3. Since your other dependancies are pip based and this is probably one of the only arch packages that affects pyfa, I would start there

**Comment by sincomil** [comment]
Checked out that last time wxgtk was updated on my system at 2018-09-17 and obviously wxgtk is not a cause of my problem, tried to run completely with new empty profile/database on new Virtual Env with all dependencies from requirements.txt from GIT, but  got the same result.

**Comment by blitzmann** [comment]
What other packages on your system were updated with pacman? 

If wxgtk isn't the direct cause, then it might be a library that it itself uses that was updated and causing problems.

**Comment by blitzmann** [comment]
> But I need a little help to get more info about what causes this particular segfault

Unfortunately I can't say. The log you provided is a pyfa log, but doesn't help if pyfa seg faults because it's not a pyfa crash, it's a crash much lower in the system. I would recommend rolling the updates back (I believe pacman allows for this IIRC since it keeps a cache of old packages, but I also understand that Arch isn't really a system designed for downgrading, so YMMV).

At the end of the day, though, this doesn't seem to be a pyfa issue, it's a library / system package issue, especially if everything was working before a system update. It would be different if you updated pyfa to a new version and started having problems. For that, I'm going to close this ticket, but feel free to continue discussion here.

@DarkFenX @minlexx you guys have any ideas on how @sincomil can better diagnose this issue? Since I'm not a linux regular, I'm not sure what other options are available...

**Comment by Arnek1** [comment]
I had the same issue with my Arch Linux System. Since today last upgrade Pyfa is working again.
These are the relevant packages which where upgraded:
[2019-02-28 18:08] [PACKAGEKIT] upgraded gdk-pixbuf2 (2.38.0-1 -> 2.38.1-1)
[2019-02-28 18:08] [PACKAGEKIT] upgraded go (2:1.11.5-3 -> 2:1.12-1)
[2019-02-28 18:08] [PACKAGEKIT] upgraded libmagick (7.0.8.28-1 -> 7.0.8.29-1)
[2019-02-28 18:08] [PACKAGEKIT] upgraded imagemagick (7.0.8.28-1 -> 7.0.8.29-1)
[2019-02-28 18:08] [PACKAGEKIT] upgraded lib32-gdk-pixbuf2 (2.38.0-1 -> 2.38.1-1)

So seems to be linked to one of these packages.

**Comment by blitzmann** [comment]
@Arnek1 thanks for the info!

pixbuf and image magick I believe are used in wx, so this would make sense (especially since the issue was with market items, where we're displaying various small icons)

@sincomil please do another update and see if you are still having issues. :)

**Comment by sincomil** [comment]
Confirm that system update resolved the issue, then I've tried to rollback _some_ of updated packages back to previous version to find out specific one, but can't get same result as before update:
tried to rollback this packages that I suspected:
gdk-pixbuf2 2.38.0-1 <- 2.38.1-1
imagemagick 7.0.8.27-1 <- 7.0.8.30-1
libmagick 7.0.8.27-1 <- 7.0.8.30-1
pcre 8.42-2 <- 8.43-1
python 3.7.2-1 <- 3.7.2-3
python-anytree 2.6.0-1 <- 2.6.0-2
python-cffi 1.12.1-1 <- 1.12.2-1
python-lxml 4.3.1-1 <- 4.3.2-1
python-numpy 1.16.1-1 <- 1.16.2-1

Full list of updated packages in attached file just FYI: [upgraded-packages.txt](https://github.com/pyfa-org/Pyfa/files/2926197/upgraded-packages.txt)
