### ISSUE TITLE
Develop a blocking modal letting user know local pyfa server is running

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1859]
From: https://github.com/pyfa-org/Pyfa/issues/1849

We should have a dialog box that appears and prevents any other user interaction other than a cancel button, letting user know that pyfa is running a local server and waiting for the login process to complete.

**Comment by noobish** [comment]
I was going to post a feature request for it, but you beat me to it. How bout this for even more functionality:

Rather than a configurable timeout, pick one of these approaches:
- add a cancel button to the pop-up with the SSO sign-on button on it, and keep the local server up listening until the user clicks cancel.
- as long as the pop-up is open (with no cancel button required), the server stays listening.

The note describing the process could be right on the form.

**Comment by blitzmann** [comment]
That's something that we can do as well... I would require it to be a dialog that prevents any other user input, so that the user doesn't forget there is a server running (for security reasons)...

Going to change the issue to reflect that

**Comment by DarkFenX** [comment]
This could be used for network-blocked operations in general. E.g. I'd also like to have this for price optimization feature I'm working on - window is blocked until prices are fetched and fit is updated.

**Comment by blitzmann** [comment]
@darkfenx for general "wait until done doing things" we have a wait box thing. Take a look at the code surrounding opening previously open fits. Think that would work well for your application, unless you need ability to cancel it in which case yeah you'll need something similar to this

**Comment by blitzmann** [comment]
Just finishing up the final touches:

**Comment by noobish** [comment]
You work quickly, good sir. o7
