### ISSUE TITLE
Empty market group -> move view to first non-empty left tab

### ISSUE THREAD

**Issue by SubjectXXX** [pyfa-org/Pyfa#1868]
## Bug Report
Its not really a bug, but its really annoying and time consuming. When I open item in market, that has Complex version of it and then move to item, that doesnt, item list is empty and I need to manually click on bottom tab to find a populated item window. Mind you, I have large monitor and while clicking on market categories, to switch item types, there is alot to travel with mouse pointer to the bottom of the screen..

### Expected behavior:
When switching items in market, if item does not have selected type (Faction, Complex, Officier), focus selection on first left tab, that has item type.

### Actual behavior:
Moving from Small energy neuts, I selected Corpii B-type small energy neut, then I wanted to add Exile Booster. When I clicked on market tree to select Exile category, bottom item selection was empty, since it remained on Complex tab. I had to move mouse on bottom, to switch tab to Normal.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
No need

### Release or development git branch? Please note the release version or commit hash:
2.7.0

**Comment by DarkFenX** [comment]
At some point in the past, I coded it to work differently (i don't remember how exactly it behaved in this case though). While i was MIAing someone changed it, and i just assumed people were not happy with it - and didn't revert the changes.

Checking commit history, following commits changed logic (get more details via `git log -p -- gui/marketBrowser.py`):

- d6db30b7fccf2d8d4bdc3d087a1e9e872957e867
- a7b6647135326ae41088b2ebce067f33b840193a

Currently, logic of market jumps and switching market group is the same: it just switches market group and doesn't touch meta groups at all, which is very inconvenient in some cases.

How it used to work (i think):

- Market jump to item: switch market group and select meta group which corresponds to meta group of the item (deselect the rest).
- Market group switch: switch market group and keep selected meta groups if possible. If some meta groups become unavailable, buttons gray out but keep their state (so that when another market group selected - items from this meta group is shown). If no items in currently selected meta groups available - add first available meta group to selection to show something.

If there are no objections - I can restore this logic. I find it much more convenient than current implementation.

**Comment by DarkFenX** [comment]
@blitzmann what are your thoughts?

Change requested by @SubjectXXX contradicts to #818 (as it clearly states that metagroup button states should be kept throughout application runtime).

However, to me old behavior was more convenient. I can understand how turning on all metagroups for search was annoying (and i can easily live w/o it).

However, there're some things I am missing:

- market jump to item. Semantically it has always been "jump to item in market" for me rather than "jump to item's market group". It means that pyfa should enable metagroup of the item if it's not enabled (so that item you're jumping to is always shown). Optionally, it can disable all other metagroups.
- market group switch AND search: if no items in currently selected meta groups available - add leftmost available meta group to selection to show something

**Comment by SubjectXXX** [comment]
Its really easy fix, no complications involved:
If you search for item in market or simply go through market tree with pressing + next to each category, if on level, that should show items and there are no items for meta tab, that was previously opened, open/focus meta tab to the left.

Not sure how would that break decisions in #818 tho, I dont see major problem there.

You right click on item in fitting and select Open Market Group. If previously, meta tab Complex was selected and this new search doesnt have meta Complex (Damage control for example doesnt have Complex meta type), search does happen, but returns empty tab. Now you have to click on Faction or Normal to get any items listed.

**Comment by SubjectXXX** [comment]
I have reread your post, Dark, and yes, I agree with first line: Open meta market group which item, that was clicked on, is part of.

**Comment by DarkFenX** [comment]
Fix is easy, decision on how it should behave is not.

> Not sure how would that break decisions in #818 tho, I dont see major problem there.

It changes metagroup button state automatically (thus enabling meta groups user preferred to not see earlier). Quote from #818:

> Keeping the filter choice at least for the duration of the app being open makes sense.

**Comment by SubjectXXX** [comment]
Ahh, I see the problem..

Maybe a new setting Retain selected meta filter? Default could be true, and we, that usually dont search directly in market search bar, can set it to false..

**Comment by blitzmann** [comment]
@DarkFenX i agree, old way was more convenient. we've had a few complaints with current functionalities for a couple years now. alternatively, we can show a message on the pane saying "x items not shown due to meta filters". 

but i think it might be best to just go back to old way. honestly, i 'm not the best to ask when it comes to day to day usability of things like this since i havent really used pyfa how its intended for, like, years :P

**Comment by DarkFenX** [comment]
See pull request #1913
