### ISSUE TITLE
Options and UI: context menus, main menu, preferences overhaul

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1887]
I am going to touch two issues with UI. Issue 1: some options are not visible. Currently, we're using two ways to set various options:

- stats panels context menus (incoming damage pattern, factor reload, target resists, price options)
- preferences (everything else)

When users explore functionality of pyfa, they see what's available in main menu, however it's not obvious at all that some stats panels have context menus available.

Issue 2: some main menu items feel out of place. `Window > Turn overrides on`, for example, or `Edit > Optimize Fit Price` which i added recently in `price_optimize branch`. In fact, two sections which look logical to me are `File` and `Help` (except for importing defaults part).

There might be many ways to solve them (feel free to suggest). I will post my proposal below,

**Comment by blitzmann** [comment]
For the context menus on stats panel, I've had idea before of registering context menu to the panel itself, and to include a little menu icon in the header that, when clicked, opens the menu. This would be baked in functionality to our stats pane class. I dont think we have many which is spanlwn based on where you click in the panel, just panel overall, so I think thos would be a good solution.

Definitely open to ideas on main menu, I have no idea what to do with it

**Comment by DarkFenX** [comment]
I would change following:

- move or copy some stats panel context menu items (to preferences or main menu, depending on how often they are needed)
- overhaul main menu structure

We have following options available in via stats context menu items:
- incoming damage pattern: duplicate to main menu (likely to be often used)
- factor reload: duplicate to main menu (likely to be often used)
- target resists: duplicate to main menu (likely to be often used)
- "total" price options (move to preferences)
- price cache reset (just remove, preferences already has such option)

Main menu structure change:


File
- new tab (ctrl-t)
- close tab (ctrl-w)
---
- backup all fittings
---
- quit (ctrl-q)

Fit
- undo (ctrl-z)
- redo (shift-ctrl-z)
---
- to clipboard (ctrl-c)
- from clipboard (ctrl-v)
---
- factor reload (ctrl-r)
- incoming damage pattern menu
- target resists
---
- optimize price (ctrl-?)
- graphs (ctrl-g)
---
- browse ESI fittings (ctrl-b)
- export to ESI (ctrl-e)

Character
- save character
- save character as
- revert character
---
- export skills needed
---
- manage ESI characters

Global
- disable fitting restrictions (ctrl-d, if it's global setting)
---
- attribute overrides
- turn overrides on/off
---
- preferences (ctrl-p)

Editors
- character editor (ctrl-h)
- implant set editor
- damage pattern editor
- target resists editor

Help
- wiki
- forums
---
- about

to move:
- import database defaults

To remove:
- import fittings (ctrl-o, imports xml, do we need it?)
- export fittings (ctrl-s, exports xml, do we need it?)
- export HTML (uses osmium, do we need it?)
- import character file (character import from XML API file, do we need it?)

**Comment by blitzmann** [comment]
In general, I would keep the context menus on the stats panels in place for now instead of moving any of them away in the preferences. We already have the functionality there, and I feel like it would cause more headaches if context menus that users know about aren't there anymore. However, duplicating the functionality to preferences / menu where it makes sense... makes sense. :P I am planning on taking a look into my idea of having a literal menu icon for those panels (for the release after next though).

As for menu proposal, I really like it! Makes things a bit more obvious on where to expect things. At the very least we could reorganize the current menu items into this new structure, and if there's time left before release develop some of the "new" items.

> import database default

Can we just stick this under preferences > Database as a button? I've never liked it in the help menu

As for the removals:

* Import fittings - lots of people still use the walking husk that is EFT, and this import supports importing those files. I continue to routinely get inquiries about how to migrate from EFT to pyfa and all their fits

* Export: Because it's weird having import but not export? I agree that the functionality is limited though. I believe EVE still allows importing via XML file (which is useless now due to ESI integration). I dunno, gonna leave this one up to you. :)

* Import character file: this is both for eve XML API, which is defunct, and I think the code for it is actually commented out). I believe it also supported EVEMon character exports, which is kinda defunct, but not really? I honestly have no idea if this program is still around, it's been picked up and abandoned so many times. If EVEMon is around, I would say keep it. Otherwise, we can remove it

**Comment by blitzmann** [comment]
I'm looking into getting the menus to drop down after clicking on a "menu" icon, something like this:

![image](https://user-images.githubusercontent.com/3904767/54890481-f2a19680-4e7f-11e9-8c08-54a5a45d5814.png)

obv work in progress - I'm just playing around with the sizers right now to see where this thing should go, but that's how it should look (should also only display for those that have a menu)

**Comment by blitzmann** [comment]
![image](https://user-images.githubusercontent.com/3904767/55001565-4066ed80-4fab-11e9-9e59-79871361b4e7.png)

It's working quite well. I like how it looks (might bold the menu icon, unsure, will need to test) and it definitely conveys the idea that there are options located in this panel.

**Comment by DarkFenX** [comment]
See #1914, I've started work on it and it looks easy so far. I hope to complete it by the next release (which is in 1 or 2 days, depending on time i have).
