### ISSUE TITLE
HTML export files are broken

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1890]
When HTML export file is opened in browser, expansion of specific fit doesn't work. I suppose it's because it used osmium for fetching fit details?

Should we reimplement our own HTML view or just remove this feature altogether?

**Comment by blitzmann** [comment]
`eftFit = Port.exportEft(getFit(fit[0]))`

This is the likely cause - due to recent changes, where we now have options as a required parameter for this function. 

If this is the only reason it's broken (besides the other issue you mentioned), think it should remain, at least for now. I am planing to implement the anonymous usage stats that we discussed a little while ago, and we can then make informed decisions on some of these older features that may not be used as much anymore. :)

**Comment by DarkFenX** [comment]
Fixed by 6291fe16263eab02583af8a01bc242b90d669487

**Comment by DarkFenX** [comment]
Closing it as it was introduced after latest release
