### ISSUE TITLE
On linux, right-clicking in character editor skill tree or item's "affected" tab is bugged

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1895]
wxPython version: 4.0.4 (wxWidgets 3.0.4) from debian repos

This issue is a follow-up for #1886. Right-clicks in character editor skill tree and "affected" tab bring context menu up when user presses RMB and close it when he releases RMB. Context menu is shown in other pyfa widgets on RMB release, so i think it should be changed to be shown on RMB release too.

**Comment by blitzmann** [comment]
Did a little digging and it would seem that wxListCtrl (the thing that drives our fitting window, drone/cargo/etc view) also exhibit the same problem. There's a literal event for context menu for this class `wx.EVT_LIST_ITEM_RIGHT_CLICK` but using it directly displays this issue.

The work around that we've always done is this: 
```
     if "__WXGTK__" in wx.PlatformInfo:
            self.Bind(wx.EVT_RIGHT_UP, self.scheduleMenu)
        else:
            self.Bind(wx.EVT_RIGHT_DOWN, self.scheduleMenu)
```
And then in `scheduleMenu`, we calculate where exactly the user right-clicked so that we have some context. We'd have to do something very similar in our case for TreeListCtrl / HyperTreeList.

I also want to move Character Editor from TreeListCtrl to HyperTreeList, so that we have one unified method of doing these things.

**Comment by blitzmann** [comment]
Might be good idea to also investigate `wx,EVT_CONTEXT_MENU`, which is an event that happens on all `wx.Window`s and is platform-specific. 

https://wxpython.org/Phoenix/docs/html/wx.ContextMenuEvent.html

> Notice that the exact sequence of mouse events is different across the platforms. For example, under MSW the context menu event is generated after EVT_RIGHT_UP event and only if it was not handled but under GTK the context menu event is generated after EVT_RIGHT_DOWN event. This is correct in the sense that it ensures that the context menu is shown according to the current platform UI conventions and also means that you must not handle (or call wx.Event.Skip in your handler if you do have one) neither right mouse down nor right mouse up event if you plan on handling EVT_CONTEXT_MENU event.

I think this is the most proper way of handling it, but a bit more research would be required.

**Comment by blitzmann** [comment]
@DarkFenX Can you test `context_menus` when you get a chance? Should be fixed

**Comment by DarkFenX** [comment]
It works. Behavior changed from "menu on mouse up" to "menu on mouse down", but that's consistent with gnome software.

**Comment by blitzmann** [comment]
Awesome 👍 

Merged branch in.
