### ISSUE TITLE
Use non-image tick for "factor reload" menu item

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1897]
Helps to work around issue #1896, and improves consistency in general.

**Comment by blitzmann** [comment]
Re-labeling this as a bug since it's functionality that is missing on Linux.

I've fixed this instance, but noticed that target resists probably shows the same issue. We should probably take a gander at all our context menus on Linux and make sure we're displaying properly on Linux

Also, and this shouldn't be a priority right now, but https://wxpython.org/Phoenix/docs/html/wx.MenuItem.html#wx.MenuItem.SetBitmaps is a possibility to keep the pretty bitmap checkmarks on Windows :D
