### ISSUE TITLE
EFS export error

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1902]
```
pyfa v2.8.0
EVE Data Version: 1459933 (2019-02-16 05:18:51)

OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
wxPython version: 4.0.4 (wxWidgets 3.0.5)
SQLAlchemy version: 1.0.5
Logbook version: 1.4.3
Requests version: 2.21.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\copySelectDialog.py", line 138, in Validate
  File "C:\projects\pyfa\gui\copySelectDialog.py", line 185, in exportEfs
  File "C:\projects\pyfa\service\port\efs.py", line 601, in exportEfs
  File "C:\projects\pyfa\service\port\efs.py", line 526, in getWeaponBonusMultipliers
AttributeError: 'Effect' object has no attribute '_Effect__effectModule'
```

Looks like we missed a reference to the old effect structure

**Comment by DarkFenX** [comment]
Fixed by facb0b1023ac5b9a35a3a0547d2de07ea4e9fe74. If i understood correctly what author wanted to achieve by these checks, that is.

**Comment by MaruMaruOO** [comment]
@DarkFenX Thanks for the initial patch.
I used `_Effect__effectModule` because `isImplemented` would rarely return an incorrect False when the effect handler wasn't generated.
#1907 adds the missing checks so `isImplemented` and `isType` never return incorrect values.

Sorry for the slow reply on this, I had some issues updating wxPython in order to get 2.8 working.

**Comment by DarkFenX** [comment]
@MaruMaruOO which cases would lead to this behavior? While i haven't thoroughly checked, my understanding is that effects for all involved items should be generated, and if sometimes it doesn't happen - it might be sign of some kind of bug you're trying to work around.

**Comment by MaruMaruOO** [comment]
I think it was always an ordering issue.
Take fighters for example.
When added all their abilities except propmods should be active by default.
Instead because the constructor uses `isImplemented`  the abilities were only active if the handler had been called since opening pyfa.

You can test it without #1907 by reopening pyfa, creating a new super fit and adding a fighter.
Then create another new super fit and add that same fighter to it.
The fighter you added first will have no active abilities because the handler didn't run till after it was constructed.
The fighter you added second will have the correct active abilities.

Having said that #1907 should work fine as a catchall fix for that type of thing.

**Comment by DarkFenX** [comment]
Indeed, I did not check the context when chaning how effects are loaded. Thanks for the fix!

**Comment by Pr3ciseD34th** [comment]
Can someone tell me how i can install this fix?

**Comment by MaruMaruOO** [comment]
@Pr3ciseD34th It's probably easiest just to grab a [development build](https://github.com/pyfa-org/Pyfa/wiki/Development-Builds), you'll want the [master branch version](https://ci.appveyor.com/project/blitzmann/pyfa/branch/master/artifacts).
If that doesn't work for you just give me a yell.
