### ISSUE TITLE
Should drone speed be taken into effect for DPS graph

### ISSUE THREAD

**Issue by djrscally** [pyfa-org/Pyfa#1995]
When working on #1911 I expected to see some validation to disapply the drones effects on the target (DPS/Web/Paint) when the target's speed _after_ application of webs from the ship is still higher than the speed of the drone. That doesn't exist, but it results in scenarios where the graph can tell you unrealistic information. For example:

![image](https://user-images.githubusercontent.com/4592235/58750617-a466d000-848c-11e9-87fb-20f8548a469d.png)

Obviously that DPS can't be applied to the target, those drones just won't catch up.

So; should PYFA account for drone and target speed, and determine whether or not to apply the drone's effects to the target when drawing DPS vs Range graphs? Or is it fine as it is? I think it's fine for experienced players, who'll understand that it's an unrealistic situation. I think it's a little less fine for newer players.

**Comment by DarkFenX** [comment]
It has been discussed recently on russian forums. Drones are very complex to deal with as it's impossible to simulate their behavior without knowing their AI, let alone build good analytical formulas (even if approximations).

1) Drone control range. It's used only when you decide to engage drones. If target goes outside of it, drones will keep shooting. Sentries will keep shooting no matter what, mobile drones will sometimes deaggro vs fast-moving targets, like they normally do even if target is within drone control range, but then you will not be able to reaggro them. Do we cut off drone DPS at drone control range or not?
2) Drone tracking. How do we take it into consideration, as position of drone, your ship and target is often different?
3) Drone speed. How does drone speed affect their damage application? This question slightly intersects with tracking and this is what you're trying to solve. 

Currently, Pyfa handles it as 1) 0 dps past drone control range and 2-3) always 100% dps within it for mobile drones, no matter the drone and target attributes; sentry drones assume ship's position and use regular turret application

Now, to your suggestion. You want to "cut off" drone effects if target is faster than mobile drones. However, this is not very good general solution as it ignores drone position, target position and drone projection. Consider following cases:

1) You have nidhoggur (3 range-scripted omni computers) with space superiority fighters shooting ceptor which is burning around it at 30k. Drone attack range is 36k, their speed is 2.4k, ceptor speed is 6k. With your suggestion it would mean that they apply zero damage while in reality they will apply some of their damage.
2) Similar situation - ishtar with wasps, some omni computers, some dramiel cruises around ishtar at speed of 2.5km/s at range of 7k while tackling it. Wasps have speed of 2.3 km/s so they will be shown as if they apply 0 dps, while they would apply some (good tracking and almost 10k optimal + some falloff).

Obviously it will also tell lies in these cases.

I thought about good generic solution and I think it would need to involve extra controls. For example, "drones stick to your ship", "drones stick to target", "drones are stationary" (this is different from "stick to ship" because I am going to introduce movement vector for shooting ship as well). First would basically transform mobile drones into ship guns (so that user can assess optimal/falloff/tracking of drones), second would keep them as-is, third would transform them into sentry drones.

However, none of those "unapply drones" when target speed is greater than drone speed. I guess graphs could have extended set of controls then:

Radio selection for general mobile drone/fighter behavior:

- stationary
- stick to your ship
- stick to target (force full application)

Radio selection for mobile drone/fighter behavior if they are slower than target:

- keep regular behavior
- override with "do 0 damage"
- override with "stick to your ship"
- override with "stationary"

Myself, I would choose "stick to target" in 1st and either "stick to your ship" or "stationary" in 2nd to cover most of use-cases, but definitely not "do 0 damage".

Someone on russian forums suggested to introduce yet another setting "drone offset" relative your or target ship. But at this stage I think it's worth to ask - is it overkill to have such amount of options for various edge-cases, which will show unrealistic numbers anyway (since we cannot simulate drone application)?

In any case, please read it thoroughly and let me know what you think about it, knowing a little more about various cases which you probably did not consider.

**Comment by djrscally** [comment]
Yeah you're right, a flat disapply damage is an equally unsatisfying solution. 

I do quite like your idea of extra controls to determine their behaviour, but I also worry about overcomplicating the graphs. The matter's kinda exacerbated by the lack of a time dimension to play with, since in a lot of scenario's the application is going to differ massively depending how long into the fight you are and taking an average or something is kinda rubbish too.

I guess the first thing to decide is; is this even enough of a problem that it's worth spending the time to change it. It surprised me not to see anything in the code, but I've never missed the feature whilst using PYFA.

**Comment by DarkFenX** [comment]
I think that during the DPS graph rework (which I am doing atm) I will just do the following:

- add setting "attach mobile drones to target" / "attach mobile drones to your ship"
- "attach to target" means that for mobile drones application/projection are ignored (current behavior), for fighters projection is ignored. For mobile drones, DPS falls to 0 at max drone control range
- "attach to your ship" turns mobile drones into "guns" mechanics-wise, fighters will consider both application and projection

**Comment by DarkFenX** [comment]
Implemented drone options on dps_sim_graph branch:

![image](https://user-images.githubusercontent.com/275209/60753691-4bd0a880-9fdf-11e9-9694-222f7c1e7719.png)

**Comment by robert-blankenship** [comment]
Did you guys end up implementing something to account for drone tracking in the damage graphs?

The flat curve is very deceptive since you get the same damage curve for all signature radii and drone types... Is there some kind of simplification we can do that will match actual game scenarios a little more closely? Like, maybe we can assume that the drone is not doing any "manual piloting"; it's just hitting "w" on the target. And also assume that the enemy ship is doing the same, just hitting "w" on the attacking ship and not trying to target drones.

Maybe there is a way to test the DPS that Pyfa comes up with using these assumptions to check and see if they are similar at all to what happens in the game.

PS: Thanks to everyone at Pyfa for their work on this tool... It's extremely helpful!

**Comment by DarkFenX** [comment]
Nope we did not. It is very hard to simulate it. There is some data on this topic: https://www.reddit.com/r/Eve/comments/ctvpp4/pyfa_v2100_released/exr0cgd/ but i never got to actually coding it in and checking it.

If anyone wishes to try implementing it, I will gladly accept it into graphs.
