### ISSUE TITLE
Can't add characters from SSO

### ISSUE THREAD

**Issue by XXDarrienX** [pyfa-org/Pyfa#1999]
### Expected behavior:
Adding Character to Character Management

### Actual behavior:
Pyfa hangs on Waiting for character login through Eve Single Sign-On
When chrome loads to the page for authorization and you authorize the character it displays pyfa local server for a few seconds then simply says pyfa and nothing else.

I am able to add an ESI character on my work laptop running Win7 64bit but my home computer is on Win10 64bit and it will not add characters

I have also tried to do this with the manual way to get the link and then I get an error

### Detailed steps to reproduce:
Go to character - Manage ESI Character - Add Character - Authorize the correct character

### Release or development git branch? Please note the release version or commit hash:
2.9.4

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win10 64b

### Other relevant information:
This is working on a Win7 machine but not a Win10 machine. I also reinstalled the application to no avail
[pyfa-2019-06-09.log](https://github.com/pyfa-org/Pyfa/files/3269104/pyfa-2019-06-09.log)
![pyfa error](https://user-images.githubusercontent.com/28017703/59154171-d5697680-8a31-11e9-83d9-725d6914b1cf.jpg)

**Comment by wscholine** [comment]
I am having a similar issue with v2.9.4: 

![deleteme](https://user-images.githubusercontent.com/41452690/61557057-39b82680-aa31-11e9-82bd-48a6a5489929.png)

I do Character->Manage ESI Characters->Add Character, get sent to login.eveonline.com in the browser, login, authorize character, and get redirected back to localhost, where I very briefly see a page that says

![del3](https://user-images.githubusercontent.com/41452690/61557363-0c1fad00-aa32-11e9-94ed-1e15db2bba08.png)

before it gets redrawn without the "Processing response..." text.

Meanwhile pyfa is displaying this
![del4](https://user-images.githubusercontent.com/41452690/61557444-4721e080-aa32-11e9-9bdc-4464fec6a7ef.png)

which I eventually have to dismiss because it's just hanging.

The logs appear to be pretty worthless:

[pyfa_debug-2019-07-19.log](https://github.com/pyfa-org/Pyfa/files/3412248/pyfa_debug-2019-07-19.log)

I think you need to instrument this area of code with more logging points. You keep getting this symptom, and it keeps getting marked "fixed," but then you still keep getting the reports.

**Comment by DarkFenX** [comment]
What kind of anti-virus monitors and firewalls do you have installed?

**Comment by XXDarrienX** [comment]
Sorry for the late reply but I am using Total Defense AV, I tried disabling it but that did not matter. I am also using a router based firewall which I also tried turning off. My corporate network is more restrictive but I am able to add it when I am at work on my work laptop.

**Comment by DarkFenX** [comment]
```
[2019-06-09 02:07:46.958641] ERROR: gui.esiFittings: HTTPSConnectionPool(host='esi.evetech.net', port=443): Max retries exceeded with url: /verify/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```
Indeed it's unlikely to matter. Log insists that there is an issue while trying to establish TLS connection to CCP ESI.

If anyone knows how to use wireshark, please provide traffic dump from such failed Pyfa run, it might provide additional info which might be useful to see where the actual problem lies - in Pyfa or in ESI.

**Comment by DarkFenX** [comment]
Just booted up my win10 installation, both Server-driven and Manual ways to add character work on 2.9.4 installed from exe build.

@XXDarrienX @wscholine is this issue still actual for you? Can you capture traffic of the failed log in attempt with wireshark? If you can - please send traffic dumps to `phoenix@mail.ru`. They contain no sensitive data as it's encrypted, but they contain unencrypted TLS handshake with all the relevant certificates being exchanged and errors being sent, which is point of interest for me.

**Comment by DarkFenX** [comment]
Closing, reopen if it's still actual.
