### ISSUE TITLE
Maximize button missing in module stats window

### ISSUE THREAD

**Issue by BessieBusybody** [pyfa-org/Pyfa#2028]
## Bug Report
Window from "Module stats" now has no maximize button, Win+UP_ARROW hotkey doesn't work too. 

### Expected behavior:
Window with maximize button

### Actual behavior:
Window without maximize button

### Detailed steps to reproduce:
1) Right click on module
2) Click "Module Stats"

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Atron, Runner (low skilled)]

Type-D Restrained Inertial Stabilizers
Type-D Restrained Inertial Stabilizers
Type-D Restrained Inertial Stabilizers

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
2.10

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
Indeed, I changed it as part of secondary window rework. Fortunately, it's an easy fix.

Could you check if there're other secondary windows (e.g. various editors, graph window, i.e. anything besides main window) which used to have maximize button but now it doesn't?

**Comment by BessieBusybody** [comment]
Compared side by side 2.9.4 and 2.10 menus. Entries with maximize button missing:
```
Fit
- Graphs
- Browse ESI fittings
- Export to ESI
Global
- Attribute overrides
Editors
- Character editor
```

**Comment by DarkFenX** [comment]
Following windows are now resizeable and have maximize button (all of them besides char editor were just resizeable before):

- Graphs
- Character editor (resizing was disabled due to skill view bugs, will see if i can fix them later)
- ESI browse fittings
- ESI export
- ESI char management
- Item stats
- Damage pattern editor
- Attr override editor
- Implant set editor
- Target profile editor

See 0269a64ae1f0f0f18329bf9fc4dcca1c6a6c4337
