### ISSUE TITLE
Advanced missile mechanics

### ISSUE THREAD

**Issue by ErwinMadelung** [pyfa-org/Pyfa#2082]
Missile mechanics are not properly implemented in the damage graphs atm. It's not a big issue but should be easy to correct. Let me explain. The missile range is not simply flight time times missile speed.
>If the missile flight time is not an integer then the missile will fly for integer number of seconds and has a chance to fly one more second. For example missile with flight time of 12.3 seconds has 70% propability to fly for 12 seconds and 30% propability to fly for 13 seconds.

Source: https://wiki.eveuniversity.org/Missile_mechanics#Missile_range

Or as an example on a specific fit:
```
[Raven, INIT - 3G]

Ballistic Control System II
Ballistic Control System II
Ballistic Control System II
Damage Control II
1600mm Steel Plates II

500MN Quad LiF Restrained Microwarpdrive
Large Micro Jump Drive
Missile Guidance Computer II, Missile Range Script
Missile Guidance Computer II, Missile Range Script
Missile Guidance Computer II, Missile Range Script
Sensor Booster II, Scan Resolution Script
Sensor Booster II, Scan Resolution Script

Cruise Missile Launcher II, Nova Fury Cruise Missile
Cruise Missile Launcher II, Nova Fury Cruise Missile
Cruise Missile Launcher II, Nova Fury Cruise Missile
Large Remote Armor Repairer II
Cruise Missile Launcher II, Nova Fury Cruise Missile
Cruise Missile Launcher II, Nova Fury Cruise Missile
Cruise Missile Launcher II, Nova Fury Cruise Missile

Large Anti-Explosive Pump I
Large Trimark Armor Pump I
Large Hydraulic Bay Thrusters I
```
The flight time is 20.4 s the maximum velocity is 14601 m/s. atm pyfa gives the range as 20.4*14601 = 297860.4. But the full DPS is only realised up to a range of 20*14601 = 292020. And damage is still done up to 14601*21 = 306621 but only 40% on average. Those details are a bit much for the general fitting window but they could be easily implemented into the damage graph.

Another issue with the damage graph is that it now gives relative movement but the missile range stays unaffected although it should not be unaffected. If a target flies away the range should be shorter while if a target approaches it should be higher.

**Comment by DarkFenX** [comment]
I am aware of this mechanic. I do not know how to show it though. I believe the only way to show these details is to show distance spread on tooltip. On graphs, you say those could be easily implemented, but how?

20.4s @ 14601 m/s means one of, as you written:

- 60% chance to fly 292020
- 40% to fly 306621

(assuming missile flies at its max speed right away)

But showing this spread on 2D DPS graph is not easy: you already have both axes taken for useful info (X is range, Y is DPS). How do you show the spread? If I could, I would also show gun damage spread somehow.

So, if you just calculate chance-weighed average this, it coincides with the value we already show in Pyfa:

292020×0.6+306621×0.4 = 297860.4
14601×20.4 = 297860.4

**Comment by DarkFenX** [comment]
Done in 7fb6170bcb4673225aa2a7886d5eee1273e308f9

![image](https://user-images.githubusercontent.com/275209/68788444-751bd800-0654-11ea-82d8-5b066e620b83.png)

**Comment by DarkFenX** [comment]
@ErwinMadelung , skimmed through EVE Uni missile page, found this link: https://forums-archive.eveonline.com/default.aspx?g=posts&m=6523910#post6523910

> Missiles now get a small bonus to their flight time based on the radius of the ship launching them. So in the above example they will hit targets 40km away.

Do you have any idea how this bonus works?

**Comment by DarkFenX** [comment]
See #2083

**Comment by DarkFenX** [comment]
> Another issue with the damage graph is that it now gives relative movement but the missile range stays unaffected although it should not be unaffected. If a target flies away the range should be shorter while if a target approaches it should be higher.

Oh and regarding this part: DPS graphs are in no way combat simulation. You can read the situation as "target speed and position on missile impact" (on in fact, on each missile impact, as target position does not change in time). Simulating whole missile flight with all its quirks would be quite painful process:

1) According to my experience, in high-speed situations missiles sometimes do "final leap" to target. For example, you fly away from a missile in some fast ship, the missile is insignificanly faster than your ship (cruise missile vs ceptor). It slowly approaches you and suddenly covers few remaining kilometers instantly. Is it network delays/jitter combined with client-side lag compensation? Is it actual thing, and if yes, what are exact conditions for this final leap? 
2) In maneuverable fast situations, missiles sometimes fail to hit target. Two different situations: a) Rocket maledictions is being chased by light drones which are closer than 7k. Rockets are faster than drones yet they fail to hit them very often. b) Abyss sacrilege vs the drifter assault BS spawn. As you orbit them, their missiles seem to fail to hit you, you end up with swarms of missiles chasing but failing to hit you. Is it due to missile agility? Something else?
3) UI challenges. Vector controls are static. They do not change in time (because, as I said, it is not a simulator). If you try to push it more into simulator field, I think the case which would be more interesting is when target orbits you. But this is not covered by current UI and needs alot of extra info (implementation of solution to ship motion equations, for example).

If you wish something similar to DPS sim, i think it's better to create separate ticket for that.

**Comment by ErwinMadelung** [comment]
The change to the damage graph is exactly what I wanted. In some cases it's important. Your Garmur example is pretty good.

Regarding the other problem: yeah I can see that it's not really implementable :( I don't fully know how the server works out the missile trajectories myself.
