### ISSUE TITLE
Command Burst Charges with Change all Charges option

### ISSUE THREAD

**Issue by EntelligenteEnte** [pyfa-org/Pyfa#2119]
There used to be two multi-level menus for setting charges, one for the current module and one for all modules of the same type. Although I generally appreciate being able to set the charges to all modules at once, one now has to disable that options in the Preferences menu for setting Command Burst charges as there is no advantage of using the same charge on multiple Command Bursts.

I have not read up on why the old functionality was replaced with the current one, but opening the preferences window before and after every command burst is not very comfortable although it requires less actions than choosing all weapon charges individually.

I would suggest to either bringing the two menus back or excluding Command Bursts and maybe also Scriptable Mids from that option.

**Comment by DarkFenX** [comment]
It was changed a while ago, also introducing following conventions:

- hold alt for batch action (eg remove whole stack of drones, replace charges for all similar modules, activate ability on all light fighters)
- hold ctrl to copy instead of move

By default, pyfa changes charge only in selected modules. By holding alt (on windows alt interferes with context menus i believe, so on windows ctrl can be used as well), it changes charge in the selected module and all similar to it.

There is a preference option which changes this behavior. You can make pyfa change all charges by default, and in only one module while alt or ctrl are pressed. The option even mentions it i think.

**Comment by EntelligenteEnte** [comment]
Thank you, the tooltip says that the action can be reversed by pressing said key. From reading the tooltip I did not know what that meant but I did not try it either. However, it seems to work just fine.

**Comment by DarkFenX** [comment]
@EntelligenteEnte how would you formulate it so that it's clear? I am not a native speaker, so often struggle with this.

**Comment by EntelligenteEnte** [comment]
I am not a native speaker either.

Currently it says the following:
`"When disabled, reloads charges just in selected modules. Action can be reversed by holding Ctrl or Alt key while changing charge."`

I would suggest something like
`"When disabled, charges are changed in selected modules only. Holding Ctrl or Alt key when selecting charges inverses this setting." `
as it does not have to do anything with reloads and to make clear that it is only temporary, reversing sounds more persistent. It was also not clear that "action" referred to the setting and not to the actual action of changing ammunition.
