### ISSUE TITLE
T3C offensive skill adjust not possible

### ISSUE THREAD

**Issue by cdgori** [pyfa-org/Pyfa#2150]
## Bug Report
For any T3 cruiser, none of the offensive subsytems associate with the correct racial skill (e.g. Amarr Offensive Systems for a Legion) in the "Change Ship Skills" mouseover menu.  

(Side note: I expected subsystem skills to appear in the "Change Subsystem Skills" menu option but they appear in "Change Ship Skills" - that I can definitely live with but might give a clue to the root cause, dunno.)

### Expected behavior:
You should be able to adjust the $racial Offensive Systems skill to see the effect on ship performance.

### Actual behavior:
You can't.  :)

### Detailed steps to reproduce:
-Create new fit for a Legion.
-Add a Legion Defensive subsystem (ex: Augmented Plating)
-Right click on the subsystem, "Change Ship Skills" will show Amarr Defensive Systems.
(it will be the same for a Core or Propulsion subsystem and the corresponding subsystem skill)
-Add a Legion Offensive subsystem (ex: Support Processor, but I tried them all and it is the same for any/all)
-Right click on it, Change Ship Skills will NOT show Amarr Offensive Systems.

It is the same for a Loki, offensive subsys doesn't give skill option, other subsys do.  I didn't check Tengu or Proteus but I'd bet it's the same.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Legion, Legion fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

Legion Defensive - Augmented Plating
[Empty Subsystem slot]
Legion Offensive - Support Processor
[Empty Subsystem slot]

### Release or development git branch? Please note the release version or commit hash:
Release, 2.18.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
@cdgori You probably misinterpret what this thing does (but, pyfa does poor at explaining that). What this context menu actually means is: "Change skills affecting ship", "Change skills affecting module" etc.

So, for example, you have legion's interscalated nanofiber sub. It shows up in "Change Ship Skills" since it affects ship itself. But support sub is not shown there since it does not affect ship itself, it affects only modules fit to it. And it is shown in "Change Module Skills" list for e.g. medium remote repairer.

If you disagree with this behavior - please explain what alternative behavior would be good and consistent from your point of view. Or if you think those menus could be better described - please write that description.

**Comment by cdgori** [comment]
@DarkFenX I see now, your explanation makes sense actually.  It's just a weird case of where the specific offensive subsystem skill doesn't change anything on the ship (per-skill level), only some modules, and so you see the option on the affected module.

This is reasonable once you understand it.  It also explains why "Change Subsystem Skills" only shows the specific T3C skill, since that is what can affect those subsystems (if you think of them like modules).

But yes, it's counter-intuitive at least initially.  I don't have any great suggestion for making it better though.

**Comment by DarkFenX** [comment]
Yeah it's not easy :)

Going to close this now, if you have any ideas - feel free to reopen.
