### ISSUE TITLE
pyfa.exe false positives or no?

### ISSUE THREAD

**Issue by micde** [pyfa-org/Pyfa#2163]
https://www.virustotal.com/gui/file/832838a392dc2b38ce0091b167f947bde558a94f308c2743adcc00f5ee82c02e/detection

Windows defender sprung into action, looked into it. This came as the result.

Are these false positives?

**Comment by DarkFenX** [comment]
This issue is doom of pyinstaller. We dropped 32 builds because of this.

Regarding those detections. ~4-5 AV vendors detect pyfa.exe as suspicious. But as long as no major AV vendors flag is as a threat, it is okay.

What you've seen is most likely windows defender seeing new executable. It collects database of executable signatures, and for first few launches (globally) shows warning to user. If users do not mark it as virus, this warning is removed for the rest of the users who launch it.

But, to be sure please share what exactly you've got.

**Comment by micde** [comment]
ok, that would be it then. it was saying unknown software. Thanks.

**Comment by DarkFenX** [comment]
Closing then.
