### ISSUE TITLE
Error fetching skills

### ISSUE THREAD

**Issue by cdgori** [pyfa-org/Pyfa#2166]
## Bug Report

pyfa v2.20.1
EVE Data Version: 1706308 (2020-04-15 01:32:35)

OS version: Windows-10-10.0.18362-SP0
Python version: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.16
Logbook version: 1.5.3
Requests version: 2.23.0
Dateutil version: 2.8.1

####################

When I open SSO character management, left click a character then press "Fetch Skills" I get a window with this traceback:

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlite3.InterfaceError: Cursor needed to be reset because of commit/rollback and can no longer be fetched from.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\esiFittings.py", line 403, in fetchSkills
  File "site-packages\sqlalchemy\orm\attributes.py", line 286, in __get__
  File "site-packages\sqlalchemy\orm\attributes.py", line 722, in get
  File "site-packages\sqlalchemy\orm\strategies.py", line 750, in _load_for_state
  File "<string>", line 1, in <lambda>
  File "site-packages\sqlalchemy\orm\strategies.py", line 892, in _emit_lazyload
  File "site-packages\sqlalchemy\ext\baked.py", line 544, in all
  File "site-packages\sqlalchemy\orm\loading.py", line 101, in instances
  File "site-packages\sqlalchemy\util\langhelpers.py", line 69, in __exit__
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\orm\loading.py", line 81, in instances
  File "site-packages\sqlalchemy\orm\loading.py", line 81, in <listcomp>
  File "site-packages\sqlalchemy\orm\loading.py", line 602, in _instance
  File "site-packages\sqlalchemy\event\attr.py", line 322, in __call__
  File "site-packages\sqlalchemy\orm\mapper.py", line 3353, in _event_on_load
  File "eos\saveddata\character.py", line 61, in init
  File "site-packages\sqlalchemy\orm\attributes.py", line 286, in __get__
  File "site-packages\sqlalchemy\orm\attributes.py", line 722, in get
  File "site-packages\sqlalchemy\orm\strategies.py", line 750, in _load_for_state
  File "<string>", line 1, in <lambda>
  File "site-packages\sqlalchemy\orm\strategies.py", line 892, in _emit_lazyload
  File "site-packages\sqlalchemy\ext\baked.py", line 544, in all
  File "site-packages\sqlalchemy\ext\baked.py", line 444, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3430, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 984, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Cursor needed to be reset because of commit/rollback and can no longer be fetched from.
[SQL: SELECT "characterSkills"."characterID" AS "characterSkills_characterID", "characterSkills"."itemID" AS "characterSkills_itemID", "characterSkills"."_Skill__level" AS "characterSkills__Skill__level", "characterSkills".created AS "characterSkills_created", "characterSkills".modified AS "characterSkills_modified" 
FROM "characterSkills" 
WHERE ? = "characterSkills"."characterID"]
[parameters: (4,)]
(Background on this error at: http://sqlalche.me/e/rvf5)

### Fits involved in EFT format (Edit > To Clipboard > EFT):

n/a

### Release or development git branch? Please note the release version or commit hash:

Release, v2.20.1

**Comment by WatchMeCalculate** [comment]
Did you by chance update recently? Or did this just start happening out of nowhere?

**Comment by cdgori** [comment]
I probably downloaded pyfa 2.20.1 in the afternoon after the release email got to me that morning (~ish, I couldn't say exactly).

**Comment by cdgori** [comment]
I updated to 2.20.2.  Fetch skills from the character management window crashed the pyfa application (no traceback).

But, the resync (I dunno the real name, the double round arrow in between the character name and the skill dependency icon in the top right) button worked and clearly picked up my most recently trained skill.

**Comment by WatchMeCalculate** [comment]
Can you go to `~/Users/<your username/.pyfa/` and find the latest logfile that has that traceback in it and post it here? I think I was able to reproduce the issue but would like to verify.

**Comment by DarkFenX** [comment]
FYI this was new functionality added in #2159 (not previously available skill update). Looking at my own judgement and how @cdgori used it, this "fetch skills" button probably doesn't do what users expect it to do. It updates skills for all characters, rather than selected one. This probably should be changed.

How many characters do you have in there when it happens?

**Comment by DarkFenX** [comment]
Just tried adding multiple characters and fetching skills, it worked. But, it also has spawned one pop-up per character in the list.

I am unsure we need that button there. I think that when we add a character, pyfa could automatically fetch its skill. This button would be removed then, and character skills could be updated regular way (via the character editor or the skill refresh button).

@soro , what do you think about this change?

**Comment by WatchMeCalculate** [comment]
I was able to reproduce the traceback above by having a character that had an expired sso token which caused the thread to fail. I would like to know if there is any output from @cdgori to show if there were any exceptions in the thread.

I'm wondering if the issue is a race on the cursor where if one of the updateThreads fails, another thread tries to use it before it performs a rollback.  I'd have to look at that code a bit more. But that's where i'm leaning

**Comment by WatchMeCalculate** [comment]
Probably could be its own issue: If sso refresh fails it bubbles up as `HTTP Error 400: invalid_token` and there isn't anything actionable from an end user side. We also don't force a re-login I'm pretty sure.

**Comment by soro** [comment]
Yeah, we could just always fetch the skills, but the reason I put the button there is that it gives you a way of fetching skills for characters that were added before the fix and don't yet have an imported character available. I guess we could also just go through each ssocharacter when populating the list and check if a corresponding character exists and if not just fetch the skills.

**Comment by soro** [comment]
> I was able to reproduce the traceback above by having a character that had an expired sso token which caused the thread to fail. I would like to know if there is any output from @cdgori's log to show if there were any exceptions in the thread.
> 
> I'm wondering if the issue is a race on the cursor where if one of the updateThreads fails, another thread tries to use it before it performs a rollback. I'd have to look at that code a bit more. But that's where i'm leaning

I did not check for thread safety of the code doing the update - I just assumed that had been taken care of. Lazy, I know.

**Comment by DarkFenX** [comment]
I removed skill fetch button in there, and I added some code to refresh character selector when new character was added. I guess this issue can be closed, character skills now have to be updated by regular means (character editor or skill refresh button next to character selection list).

**Comment by cdgori** [comment]
> Can you go to `~/Users/<your username/.pyfa/` and find the latest logfile that has that traceback in it and post it here? I think I was able to reproduce the issue but would like to verify.

Here you are (not sure if this is necessary given the resolution, but you have it anyway):
[pyfa-2020-04-15.log](https://github.com/pyfa-org/Pyfa/files/4494445/pyfa-2020-04-15.log)

**Comment by cdgori** [comment]
I am not sure if I use this functionality correctly, but might as well say this: I add each character in SSO character management (across 3 accts), then use character editor to associate a "pyfa character name" with each SSO character.

I agree that it's a bit confusing to have the Fetch Skills button in the SSO character management window and the Get Skills button in the EVE SSO tab of the Character Editor - I honestly can't tell what the difference is (other than Fetch Skills seems to work on all characters at once?)

**Comment by DarkFenX** [comment]
@cdgori the flow has been changed. Now when you add a character in "SSO Character Management", it creates a new pyfa character with the same name for you, and connects it with the SSO character. If you already have pyfa character with the same name - it will just connect the pyfa character with the SSO character. While doing it, it will also fetch all skills.

That "Fetch Skills" button was confusing because it fetched skills for all active SSO characters, while other two buttons manipulated single character. I had 3 options what to do with it:

1. Rename button to "update skills for all characters" and fix all the bugs connected to it (this issue, the fact that it spawns separate popup for each character)
2. Rework it so that it works only on currently selected character
3. Remove it and just leave conventional way of updating skills (via character editor and via skill refresh button on the main pyfa frame)

I went with option 3 just to avoid functionality duplication. While they are not duplicates, strictly speaking (fetch one vs fetch all), I could not see a scenario when you would want to have mass fetch. After all, if you work on a fit which needs a character for which you haven't updated skills in a while, it takes a single button press to fetch them.
