### ISSUE TITLE
First projecting a ship with Logi bots does not have bonuses applied.

### ISSUE THREAD

**Issue by agondolo** [pyfa-org/Pyfa#2168]
## Bug Report
When **first** adding a Scythe with logi bots to the projected additions, the drones do not apply their full rep amount to the ship's recharge rates. The Scythe's 100% bonus is not accounted. Neither is the Scythe's character's skill in Repair Drone Operation.

When reopening the fit, however, the bonuses are applied to the projected ship's Logi bots.

### Expected behavior:
Role and ship bonuses and character skills apply to logi bots when first projecting a fit.

### Actual behavior:
The recharge rate is the base rep amount of the logi bots.

### Detailed steps to reproduce:
Create a fit with Logi Drones, e.g., a Scythe with 5x Light Bots. Key numbers: 12 EHP/s base. 24 EHP/s with the Scythe's 100% role bonus. And 30 EHP/s with 25% bonus from an All V character.

Open a blank fit (e.g., another Scythe), and project the Scythe with bots on it. Immediately look at the recharge rate (when switched to raw HP mode instead of effective HP) and see it is 12 EHP/s.

Restart pyfa and look at the blank fit: it will correctly show 30 EHP/s.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Scythe, Bug test provider]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

Light Shield Maintenance Bot I x5

### Release or development git branch? Please note the release version or commit hash:
release v2.20.1 (though have seen it prior. had to play around to figure out how to reproduce it)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win10

**Comment by DarkFenX** [comment]
Issue connected to effect runtime. Also noticed it happening sometimes. Will fix by the next release.

**Comment by DarkFenX** [comment]
I was wrong. This was caused by fix for #2160. There, I forced projected fit recalculation while fetching projected fit, so that modified restrictions are calculated properly and "excessive" command bursts (powered by command processor rigs) do not get offlined. This flagged fit as calculated, and while projection was being added, its stats were cleared during SQLAlchemy session refresh, but calculation flag was retained.

I implemented another workaround - we just ignore restrictions for projected fits, and we do not force early calculation of projected fits. This way, drone stats get properly calculated.
