### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by m-sasha** [pyfa-org/Pyfa#2246]
I'd like to work on improving the performance of PyFa, as parts of it are annoyingly slow.
My question is what is the best way to communicate with you, the main devs, about changes I'd like to do?
Some questions are short, like "Is the `time.sleep(0.5)` in `OpenFitsThread.run()` really needed?"
Others require longer discussion.
Should I open an issue per topic? Write the questions in this issue? Is there a gitter chat?

**Comment by blitzmann** [comment]
We have a slack. I'm embarrassingly bad at actually having it up ever since my workplace moved off Slack to MS Teams, but as I'm coming back around a little more I got it set back up on my desktop. Apparently I need to get it to start at boot tho

https://pyfainvite.azurewebsites.net/

Both @DarkFenX and I can be reached through it for real(ish)-time communication. Just pop into the general channel and say hi :) if we need to move to a different channel for more indepth discussions, we can figure that out at the time.
