### ISSUE TITLE
Mac still not being supported?

### ISSUE THREAD

**Issue by GKFC** [pyfa-org/Pyfa#2338]
Hi,

Just wondering as it's been a few patches now without an update for Mac...  interested to hear any feedback you may have.

Cheers,

G.

**Comment by DarkFenX** [comment]
I was super overloaded at work. I had two issues to resolve before yesterday's release: reconfigure crowd.in to master branch and fix macOS builds. Unfortunately due to said work i did not have time to do it all, so i left macOS build for later. I will be spending my spare time this week on fixing it. It needs transfer to new builder system, but hopefully I can have something for you by the end of this week

**Comment by GKFC** [comment]
Thanks for the update, I appreciate you've had a busy time, and it's good to hear Mac will be getting some attention now.

I look forward to seeing any updates coming through.

**Comment by kulnor** [comment]
Likewise much appreciate your work and efforts for making this available on OSX

**Comment by OrthelT** [comment]
@DarkFenX So glad to hear MacOS support is coming back. I know you put tremendous effort into this. It's greatly appreciated. If you have a Patreon or other way to thank you for all your work, please do let us know.

**Comment by DarkFenX** [comment]
https://ci.appveyor.com/project/pyfa-org/pyfa/builds/39519410/job/2tn5sgxn3ttglua1/artifacts try this build. It works on my macOS laptop, but I am curious if it works on yours.

If there are no issues reported within next few days, i will try to catch up with backlog of issues and make a new release, with macOS build this time.

**Comment by OrthelT** [comment]
@DarkFenX Thanks for this. It runs, but crashes frequently. I've included a couple crash reports below to help you debug the problem. 
Crash Report 1: [https://tinyurl.com/sry5hcae](https://tinyurl.com/sry5hcae)
Crash Report 2: [https://tinyurl.com/yk2us4z7](https://tinyurl.com/yk2us4z7)

**Comment by DarkFenX** [comment]
Are crashes random, or on certain actions?

**Comment by OrthelT** [comment]
> Are crashes random, or on certain actions?

I haven't been able to find find a pattern yet, so it looks like it's random from what I can tell.

**Comment by kulnor** [comment]
I installed and seem to be running fine on my end, but have not used extensively (mostly browsing existing fits and copy/pasting)

**Comment by joonashak** [comment]
@DarkFenX I just made a couple of fits from ground up with the new version you posted, and everything worked perfectly. Also browsed old fits and imported some from ESI, no problems there either. Catalina 10.15.7.

**Comment by MauroCL-Developer** [comment]
@DarkFenX For me the crashes started with macOS Big Sur. One crash pattern that I can reproduce often with all the Pyfa releases since Big Sur was launched is the following:
1. Open Pyfa
2. Search for a ship.
3. Type Enter.
4. Pyfa crashes.

One more, but it is less consistent:
1. Open Pyfa
2. Modify one the preloaded fits.
3. Close the fit.
4. Pyfa crashes.

Then, not so often, but there is a pattern that I found throughout the time.
1. Open Pyfa
2. Right click to change the variant of a module in one of the preloaded fits.
4. Pyfa crashes.

**Comment by DarkFenX** [comment]
I have 2 macbooks in my reach, old one with catalina and new one with bigsur. Unfortunately i have only catalina one atm, and won't have time to test on BigSur until middle on next week.

I will try to push sisi update with a mac build today, debugging on big sur will be left for later.

**Comment by kulnor** [comment]
I'm on Big Sur, will let you know if I experience any issue.

**Comment by DarkFenX** [comment]
Let's move over to 2338
