### ISSUE TITLE
Updating/Adding characters using ESI throwing "Server Response Not Received" error

### ISSUE THREAD

**Issue by bieno002** [pyfa-org/Pyfa#2366]
## Bug Report
When trying to update the skills on my character I've had in the program for a long time, I get errors after logging in to eve sso. I removed the character and tried to add it again and get the errors as well.

### Expected behavior:
Adding characters works.

### Actual behavior:
Doesn't work.

### Detailed steps to reproduce:
Add a character through esi, after successful sign in and hitting authorize, get an error saying: 
"Error! Server response not received.
The local pyfa server may have timed out, or may not have started correctly."

### Release or development git branch? Please note the release version or commit hash:
Release version 2.38.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
![image](https://user-images.githubusercontent.com/337774/139622235-1b7ddee5-09ce-403f-8444-418be07be419.png)

**Comment by ak08743** [comment]
Had the same issue, figured out that was uMatrix blocking requests to localhost. Check that whatever AD blocking/Privacy addons you are using in the default browser are not blocking the requests (uBlock Origin, uMatrix, NoScript, etc.)

**Comment by bieno002** [comment]
Ah ok that must be it, I was using Brave browser which blocks a lot more than most browsers. I'll try it with chrome. Thanks!

**Comment by blitzmann** [comment]
I'll make a point soon to update the message that is displayed to point out that sometimes browsers block the request to localhost, and that the manual mode option may help.

The reason we're seeing this a bit more often with the 2.38+ release is because it works a bit differently than pre-2.38. Instead of the SSO redirecting the browser to localhost, in which a page is served up by the server pyfa started, we instead redirect to a public callback page which then makes a request to localhost to post the SSO data. Some browsers apparently block these kind of requests.

**Comment by notepid** [comment]
![image](https://user-images.githubusercontent.com/1101091/151312770-0a49f229-2f33-450d-bd0b-6fb450854aba.png)
When using Brave and setting "Shields Down" for https://pyfa-org.github.io/ fixed this for me.

**Comment by blitzmann** [comment]
Duplicate #2370, keeping that thread alive, closing this one
