### ISSUE TITLE
pyfa Error! There was an unknown error. Please report this to the pyfa issues page.

### ISSUE THREAD

**Issue by leoslemixv-int** [pyfa-org/Pyfa#2384]
### Other relevant information:pyfa
Error!
There was an unknown error. Please report this to the pyfa issues page.
 File "service\server.py", line 29, in do_GET
  File "service\esi.py", line 172, in handleServerLogin
  File "service\esi.py", line 138, in handleLogin
  File "service\esiAccess.py", line 175, in auth
  File "service\esiAccess.py", line 203, in token_call
  File "site-packages\requests\sessions.py", line 590, in post
  File "site-packages\requests\sessions.py", line 542, in request
  File "site-packages\requests\sessions.py", line 655, in send
  File "site-packages\requests\adapters.py", line 498, in send

**Comment by blitzmann** [comment]
Hi @leoslemixv-int , are you still having this issue?

The error that you pasted doesn't seem to be the entire one, please copy an paste everything within the text area when an error presents itself.

**Comment by 1072387333** [comment]
同样的显示

  File "service\server.py", line 29, in do_GET
  File "service\esi.py", line 172, in handleServerLogin
  File "service\esi.py", line 138, in handleLogin
  File "service\esiAccess.py", line 175, in auth
  File "service\esiAccess.py", line 203, in token_call
  File "site-packages\requests\sessions.py", line 577, in post
  File "site-packages\requests\sessions.py", line 529, in request
  File "site-packages\requests\sessions.py", line 645, in send
  File "site-packages\requests\adapters.py", line 513, in send

**Comment by 1072387333** [comment]
pyfa
Error!
There was an unknown error. Please report this to the pyfa issues page.

  File "service\server.py", line 29, in do_GET
  File "service\esi.py", line 172, in handleServerLogin
  File "service\esi.py", line 138, in handleLogin
  File "service\esiAccess.py", line 175, in auth
  File "service\esiAccess.py", line 203, in token_call
  File "site-packages\requests\sessions.py", line 577, in post
  File "site-packages\requests\sessions.py", line 529, in request
  File "site-packages\requests\sessions.py", line 645, in send
  File "site-packages\requests\adapters.py", line 513, in send

**Comment by blitzmann** [comment]
Can you please provide more information? What were you trying to do in pyfa? What operating system?

Can you provide the log file? The path to it can be found in the prefreneces
![image](https://user-images.githubusercontent.com/3904767/158513647-251666f9-c067-46fe-8ddc-32115639387d.png)
(note that the filename might not be correct, but it'll be the latest .log file in that path)

I looks like it's during ESI character registration. Have you tried the "manual" option in the preferences instead of the "auto" server option?

![image](https://user-images.githubusercontent.com/3904767/158513346-48d006a3-5946-4c25-8fc5-2474591516e5.png)

Errors within the server are hard to diagnose since it's threaded, and it's hard to get information about it in the main thread. Getting that log file may prove useful, but it may also not tell much.

**Comment by 1072387333** [comment]
I'm trying to connect with my character skills,
The system I use is windows

The log file is as follows
[pyfa-2022-03-16.log](https://github.com/pyfa-org/Pyfa/files/8258939/pyfa-2022-03-16.log)
[pyfa-2022-03-15.log](https://github.com/pyfa-org/Pyfa/files/8258940/pyfa-2022-03-15.log)

Manual mode still prompts the error
![image](https://user-images.githubusercontent.com/51105200/158518080-01f60060-e9ca-4a4d-bac1-b70a49467420.png)

The hint in the picture is;
Unable to start local server, please try going to Preferences->EVE SSO->Login Authentication Method and set to manual mode. If you still encounter problems, please file an issue on Github to report the problem.

But I have set to manual mode
![image](https://user-images.githubusercontent.com/51105200/158518310-5b40afc4-56c4-4d87-b726-c12d3f8d5b34.png)

**Comment by blitzmann** [comment]
Oh, so manual mode isn't working as it should.

I'll check the logs in the next couple days, see if I see anything

**Comment by blitzmann** [comment]
@1072387333 I know you said you had manual mode already set, but after setting it please try to restart pyfa and try again. I don't know if it switches without restarting, and I don't know if you did that by chance.

Additionally, the logs show the following error

```
[2022-03-15 12:37:53.627269] ERROR: gui.esiFittings: HTTPSConnectionPool(host='login.eveonline.com', port=443): Max retries exceeded with url: /v2/oauth/token (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
```

It looks like it's not able to finish the request to the token endpoint. This can happen for a variety of reasons, however it's usually due to your network (access is being restricted by a firewall, proxy isn't set up correctly, etc...)

Some questions: 
1) Do you by chance have a proxy set up under Preferences > Network? Or a general proxy set up on your computer?
2) When you click Manage ESI Characters > Add Character, does it immediately fail or does it go to EVE's login page in your browser
    a) When you login, does it redirect you to pyfa-org.github.io? What does that page say?
3) Is this the first time you've tried to login to this account in pyfa?

General information about where this error seems to be triggering.

/v2/oauth/token is accessed under two situations:
* During the initial login. After you log into EVE's site, it will redirect you to a page we control. From there, it does one of two things, depending on your settings:
    * If using a local server: Tries to make a request to your local pyfa server, to provide it with information it needs to complete the login process
    * If using manual mode: It displays a text box that you should be able to use to enter into an input in pyfa. Again, this encodes information that is needed to complete the login process.
    * Once pyfa has this initial data, it makes a call to the token endpoint (this is the call that is failing, according to the logs) 
* the other instance where the token endpoint is used is during token refresh. In this situation, pyfa already has information it needs cached to refresh it's access token, to be able to fetch new skills.

I'm going to assume you're trying to initially login rather than refresh skills. The fact that it's trying to access the token endpoint tells me that you were able to login, it was able to redirect to our site, and pyfa (either through the local server or through your copy and pasting into the input) was able to get the data it needs to make a request tot he token endpoint. It's just that that request fails for some reason.

**Comment by 1072387333** [comment]
proxy?
I think I see.

**Comment by 1072387333** [comment]
Sure enough, it seems that the VPN I use seems to cover the proxy, resulting in the failure of the link.

**Comment by 1072387333** [comment]
After I turn off VPN, it can complete the link
![image](https://user-images.githubusercontent.com/51105200/159994213-8ec7028f-1f49-4c5c-aca6-03f5bcaf6035.png)

**Comment by blitzmann** [comment]
Excellent!

Glad to hear it's working. We probably should have it catch that ProxyError exception and advise checking VPN / Proxy settings... I would assume @leoslemixv-int has the same issue.

Going to close this now :)
