### ISSUE TITLE
MJD has incorrect CPU in pyfa

### ISSUE THREAD

**Issue by WILD-SPARROW** [pyfa-org/Pyfa#2411]
## Bug Report
MJD has incorrect CPU in pyfa

### Detailed steps to reproduce:
fit MJD in PYFA

### Fits involved in EFT format (Edit > To Clipboard > EFT): 
[Vargur, Odunen's Vargur]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
Large Micro Jump Drive
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

Large Capacitor Control Circuit II
Large Capacitor Control Circuit II

Hammerhead II x5
Hobgoblin II x5

### Release or development git branch? Please note the release version or commit hash:
V2.40.0dev1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by blitzmann** [comment]
can you show where eve shows 77?

Usually these things happen because you have a skill applied in pyfa that you don't have in eve, or vise versa. Or because of an implant you have in eve. I'm not seeing anything that affects the CPU for that module, and the base value is 54 
![image](https://user-images.githubusercontent.com/3904767/159741001-b0654a19-47cd-4485-afb0-3e5b00f11018.png)

And that's what's showing in pyfa as well. I'm not sure where EVE is getting 77 from

**Comment by blitzmann** [comment]
I popped into eve and opened simulation

![image](https://user-images.githubusercontent.com/3904767/159742169-be80ff1d-41e9-42f0-832c-df5f83ce5c0c.png)

it shows as using 54CPU, just like pyfa.

**Comment by WILD-SPARROW** [comment]
I was not using the correct version of pyfa that match the game version at
the time.
