### ISSUE TITLE
Authorize button disabled

### ISSUE THREAD

**Issue by Demlar** [pyfa-org/Pyfa#2434]
## Bug Report
![image](https://user-images.githubusercontent.com/104110804/164344801-3fa2a683-10f2-45c3-907c-255df1400b32.png)
the authorize button is disabled. tested with all 3 browsers i have... chrome, brave, and edge... turned off ad blocks and all extensions. Still was unable to click the authorize button.. I then looked in the source code and the button is disabled. I removed disabled in source code  and the data that was invalid.
### Expected behavior:

button authorize should be enabled and functioning properly.
### Actual behavior:

Authorize button is disabled and data is invalid??

**Comment by blitzmann** [comment]
I don't know why that would be. This is the SSO Login screen on EVE's site, we have no control over it. It may be that they had some sort of outage or something (there's a few different reports for us surrounding EVE SSO in the last 24 hours)

> data that was invalid

I'm curious, even though I have no idea what the issue could be, what did it say exactly? 

Can you try again and see if it's still happening?

**Comment by blitzmann** [comment]
Oh! You have to click your character to "activate" it

![image](https://user-images.githubusercontent.com/3904767/164554101-201c6872-32e7-44c9-8acb-d2956c6090a1.png)


![image](https://user-images.githubusercontent.com/3904767/164554160-901f2a91-7138-45e9-a32f-18c64b5b7e60.png)

it makes it more confusing since it's only one character and you would kind of expect it to just do it for you lol

**Comment by blitzmann** [comment]
@Demlar  If that doesn't work let me know, not that I can do anything about it since we don't control that system.
