### ISSUE TITLE
How to copy module from 1 fit to another (same/different type ship)

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [pyfa-org/Pyfa#2448]
This is a question, not a bug report.

How can I copy a module I have on one fit to another fit I'm developing without going to the Market to find the item I want to copy?
The source and target ships may or may not be of the same type; e.g. I might want to copy a probe launcher from my frigate over to a cruiser fit I'm working on.

**Comment by DarkFenX** [comment]
You are right, for general case you cannot (since adding new modules is easy). The only exception to this is mutated modules because they are harder to carry over.

If you want to move majority of old fit to another ship, you could export old fit to EFT format, and then change ship name manually and import it.

And I am unsure if copying modules one by one (switching between tabs as well) is a good way to move modules. It's probably more efficient to use market search or "recently used" modules.
