### ISSUE TITLE
multispectrum shield hardner increase shield regen

### ISSUE THREAD

**Issue by paulogabbi** [pyfa-org/Pyfa#2454]
by adding a the multispectum hardner and activating it pyfa displays a increase of shield regeneration
![image](https://user-images.githubusercontent.com/21028542/177657693-5983a8f1-cf30-4dc6-ac4f-26ec87ba22d0.png)
![image](https://user-images.githubusercontent.com/21028542/177657737-379a2b7e-2640-4626-8170-47dd3278572c.png)

**Comment by lunedis** [comment]
That is correct and expected behaviour.

Note how the Shield Recharge measurement says **E**HP/s.
This means it deals with _effective_ hitpoints, which are the normal hitpoints but with resists taken into account.

Example: a ship with 500 HP, but with uniform resists of 50% has 1,000 effective hitpoints, as all damage gets reduced by 50%, thus it can take double the damage until it is dead.

As a multispectrum shield hardener increases the (shield) resists of a ship, it thus also increases the effective shield recharge.

Note: You can press the button called "EHP" near the top right of the resist pane in order to switch to raw HP. This is seldom useful, but you will note that there the multispectrum shield hardener does not increase regeneration.
