### ISSUE TITLE
Feature Request: Custom Target Profile Directories

### ISSUE THREAD

**Issue by HyperSaRogue** [pyfa-org/Pyfa#2583]
Could we have an option in the "create target profile" dialog that lets us create custom directories and sort new profiles into them?  

Most of my theorycrafting is for PvE, especially abyss, and I like to have a large number of target profiles stored to simulate against.  Custom target profiles currently sit at the top level, though, which turns the profile collection into a merry hunt any time I want a specific one. 

When I upload profiles it's usually in bulk from here: https://gist.github.com/jdtech3/6bd0a06626467cc4a3c0ddc4ede300ff
A way to upload a group of profiles from my clipboard directly into a directory, instead of at the top level, would be some much-appreciated QoL.

**Comment by DarkFenX** [comment]
Use `[Folder1][Folder2]profile` naming, it would put them into subfolders

**Comment by ehawman** [comment]
WHOA. That's such a cool feature. Not the original submitter, but I'll be sharing this with my corp. Thanks!

If I were to recreate/reconfirm the info in the linked gist into the bracketed format, would you be interested in adding that to Pyfa by default?

My initial thought is that what is now "NPC" would become "NPC Faction", and then I'd do [NPC Entity][*Entity Group*]*Entity Name*,*Stats etc*, where the *Entity Group* is collapsed. So instead of Deadspace Overseer Battleship, Deadspace Overseer Cruiser, Deadspace Overseer Frigate, Deadspace Overseer's Belongings, Deadspace Overseer's Sentry, and Deadspace Overseer's Structure, there would just be Deadspace Overseer with all those entities underneath.

Example:

`[NPC Entity][Abyssal Spaceship]Anchoring Damavik,45.805970149253724,40.910447761194035,47.17910447761194,37.50746268656716,3000.0,192.0,192.0`

**Comment by DarkFenX** [comment]
Yes I can add it to defaults. However I'd look at how usable it is first (sometimes too much details isn't good, can't say how good is it until I get to use it).

**Comment by HyperSaRogue** [comment]
That's exactly what I was looking for, thank you!  Issue closed
