### ISSUE TITLE
Launched Drones sometimes doesn't export with the fit

### ISSUE THREAD

**Issue by resinneublem** [pyfa-org/Pyfa#367]
When you select drones to "launch" and then export the fit either to clipboard or via HTML+IGB link, the launched drones aren't part of the fitting in EVE.

**Comment by resinneublem** [comment]
This is different than ammo/charge behavior which get exported

**Comment by blitzmann** [comment]
Well, the drones are exported correctly at the very least. The problem is probably the EVE client itself. If you have a ship that has enough room for 5 Hobs, and you export a fit that has 5 hobs and 5 warriors, then the eve client is probably going to truncate the extra drones because they don't fit.

Same goes for exporting fits with cargo. The saved eve fittings in the client only saves charges, not other items.

My account is inactive, so I cannot test this thoroughly in game.

**Comment by resinneublem** [comment]
> My account is inactive, so I cannot test this thoroughly in game.

Right on. Just posting an update I found. It looks like it's a problem with the HTML export. I'm seeing different results Edit > To Clipboard and manually importing it in the game vs Exporting HTML and opening it via the IGB.

It seems like the HTML version drops the first drone stack, whether it's "launched" or not.

I verified that the fits aren't going over their drone bay size.

**Comment by blitzmann** [comment]
If you open the HTML file in your browser instead of in EVE and click on the fit, it opens at NULLSEC.com, and shows all the drones there. So it isn't a problem with the export, but probably a problem with how EVE itself handles the import

The HTML export is done via EVE's DNA format. When you click on it in the in-game browser, it loads that DNA string and displays the fitting window. Where as, if you copy and paste the fit, EVE parses the EFT format. There might be differences in how these two formats are parsed on the EVE client, hence the discrepancy.

It COULD be the way the items are ordered in the DNA format. This is something that we dealt with a while ago with Subsystems: if they weren't ordered just right, it would break the DNA import. Again, I don't have a working account right now, so i can't fiddle with the order. if you want to mess with it, simply open the HTML export page in an edit and find the fit. You should see the DNA format like this:

`shipID:typeID1;qty1:typeID2;qty2::`

**Comment by resinneublem** [comment]
Ah I think I know what it is. The fits I've seen this with is when I use the same drone, but I have a more in the drone hold than can be launched. So two stacks of the same type in the drone hold. A Dramiel is a good example.

Opening the html source I'm seeing this: `2456;3:2456;1` (Hobgoblin II) so EVE must only be respecting the 2nd type. I think I have seen this with loaded ammo + the same ammo in the cargo hold.

A (hopefully) simple fix would be for Pyfa to uniq the typeids and combine the quantities in the DNA format.

**Comment by blitzmann** [comment]
If you could edit the HTML to combine them and see if that works better, that would be great. Otherwise, this will have to wait until I get subbed again, which will be a couple of months
