### ISSUE TITLE
Market doesn't load micro shield boosters

### ISSUE THREAD

**Issue by thorr18** [pyfa-org/Pyfa#475]
Category 'Remote Shield Boosters / Micro' doesn't load any market items. 
Empty list, but no debug messages. 

1.17.1

**Comment by blitzmann** [comment]
Seems to be fixed with latest data dump, not sure why it doesn't work now. i'll leave this open until the next release

**Comment by blitzmann** [comment]
Checked with the January release data, it seems to have reverted again. I have no idea why, but I'll look into it later for a 1.18 point release.

**Comment by BlckKnght** [comment]
The "Micro" size category of remote shield boosters is obsolete. There haven't been any modules in that group craftable or dropped by rats for a long time.

The recent tiericide merged all the remaining legacy items from the category into the single 'Micro' Small Remote Shield Booster module (which is correctly shown on the "faction" tab of the small boosters, like the 'Basic' and storyline mods of other module types).

So, I think the only real bug to be fixed is that the empty group shows up on the market list. I notice that it shows up with a `+` initially, as if the program thinks it has sub-groups within it, perhaps that is related to it showing up when it should not (e.g. the subgroups don't show because they're empty, but the parent group does show because it contains subgroups).

**Comment by blitzmann** [comment]
@BlckKnght I thought that's what happened to the modules in this group, but I wasn't sure. Thanks for giving some insight.

As to the reason, I'd have to check on the logic. IIRC, we display the market group if it has children, but those children don't actually load until the group is expanded. I'll take a look when time permits. =/

**Comment by blitzmann** [comment]
We were missing some info in the database, see #546. This should be fixed with the upcoming point release.
