### ISSUE TITLE
Conflict with Copy/Paste shortcuts

### ISSUE THREAD

**Issue by paxswill** [pyfa-org/Pyfa#490]
When I'm trying to add an API key to Pyfa, I copy the info from CCP's Api key site, but I'm unable to use ⌘V (command-V) to paste in the key ID or vCode as that is in use by the "From Clipboard" command. Could those commands either have their shortcuts disabled while the API editing window is focused (probably hacky and leaves other corner cases unsolved) or possibly change the "To Clipboard" and "From Clipboard" to ⇧⌘V/⇧⌘C (shift-command-V/C). I am still able to right-click the text field and paste from there, so adding help text to tell people to do that might be a quick fix as well.

**Comment by blitzmann** [comment]
Are you using the basic `-mac` version or the `-mac-wx3` version, and what is your OSX version? This is the first I'm hearing of the shortcut completely being overridden rather than the intended added functionality. I'll have to look into this more

**Comment by paxswill** [comment]
-mac-wx3, 10.10.5

**Comment by resinneublem** [comment]
Yeah I can reproduce too. Will do some googling to see about a work around.

**Comment by resinneublem** [comment]
As a short term work around you can right click and choose "Paste" on the text field.

There may be a way to disable the menu items but I don't know you'd be able to deterministically tell when to disable/enable.

**Comment by RealSalmon** [comment]
This is also an issue with the -mac version in v1.18.0 (OS X 10.10.5)

**Comment by blitzmann** [comment]
I still have not had a change to check, but this may be related to the fix for the menu as stated here: https://github.com/pyfa-org/Pyfa/issues/456#issuecomment-161885962

**Comment by blitzmann** [comment]
I can confirm this is present in current release. With the current master it works, but probably due to a recent switch from Frame to Dialog that may or may not be sticking around. Anyway, this issue here is event propagation - need to find a way to stop paste events from being handled by the main window if they are happening in a text ctrl.

**Comment by resinneublem** [comment]
I did some digging into this, and it looks like the problem is https://github.com/pyfa-org/Pyfa/commit/0a10f2d72ad82a383667ebe2a1f15491c48c6f87

Specifically the override https://github.com/pyfa-org/Pyfa/blob/master/gui/mainMenuBar.py#L54-L56

If I comment that out, copy/paste works just fine. When you're using a text control, it behaves as normal (even though the Edit menu highlights). And when you're not in a text control, it will import/export the fit.

I re-read https://github.com/pyfa-org/Pyfa/issues/456 and I'm not 100% sure why that commit should fix that problem. I'm running wxpython 3.0.2.0 installed from homebrew.

For what it's worth, I did some research and it looks like this has been a common problem. So I think wxWidgets is doing some hacking under the covers to allow the focused text control to accept the key command instead of letting the accelerator take it:

* http://trac.wxwidgets.org/ticket/11320
* http://trac.wxwidgets.org/ticket/14953

---

So one simple solution is to rip out https://github.com/pyfa-org/Pyfa/blob/master/gui/mainMenuBar.py#L54-L56 but I can't reproduce https://github.com/pyfa-org/Pyfa/issues/456 - perhaps the 2nd half of https://github.com/pyfa-org/Pyfa/commit/0a10f2d72ad82a383667ebe2a1f15491c48c6f87#diff-bd60c14d60292b0c9010baa9dbaf4bc8R52 fixes it. (The part that dropped the `if 'wxMSW' in wx.PlatformInfo else ""` bits)

**Comment by blitzmann** [comment]
So glad you're looking into this. If you can, please submit a PR and I will test both 2.8 and 3.0.2.0 for OS X (unless you want to attempt to build it yourself :P)

**Comment by resinneublem** [comment]
@blitzmann how do you go about testing 2.8? Is that something that I can use virtualenv for?

**Comment by blitzmann** [comment]
>how do you go about testing 2.8? Is that something that I can use virtualenv for?

ehh... I mean, you can install 2.8 and 3.0 side by side, however on OS X it's pretty janky IIRC. virtualenv may be of limited help (whoeevr, it would only handle the wxPython side, no wxWidget binaries), but I'm not knowledgeable enough about virtualenv to be of any use.

My thought for testing in 2.8 would be to use the dist.py script to create the mac-deprecated build (which is 2.8)

**Comment by DarkFenX** [comment]
Is it still actual?

**Comment by DarkFenX** [comment]
I removed offending bits (assigning custom IDs to copy-paste) and tested tested scenarios listed in #915. Had no issues on my Mac. So let's consider this as fixed, hopefully it doesn't cause any issues on Macs.
