### ISSUE TITLE
[feat req] reactive armor hardener manual control

### ISSUE THREAD

**Issue by msoltyspl** [pyfa-org/Pyfa#502]
Any chance for such kind of feature to be added at some point ?

**Comment by blitzmann** [comment]
Not likely. Reactive armor hardener is a strange and unique module, with mechanics that are quite apart from anything else in the game. I would be interested in hearing ideas about how this might work, but there are currently no plans for even researching into it, especially since it's such niche item.

In the meantime, you can sort of simulate different resists if you change the attributes with the attribute editor. Not really a great alternative, but it's there...

**Comment by msoltyspl** [comment]
Tried attribute editor - but the changes that I set there (e.g. setting resists to 0/0/30/30) are not picked up in actual fitting (which remains at its default 15/15/15/15).

(other then that I'm perfectly fine with this method)

**Comment by Ebag333** [comment]
@blitzmann do you want to tie this to: https://github.com/pyfa-org/Pyfa/pull/634

**Comment by blitzmann** [comment]
Done #634
