### ISSUE TITLE
Mac wx3 release not taking skill levels into account

### ISSUE THREAD

**Issue by matthewpennell** [pyfa-org/Pyfa#509]
Clean install on Mac OSX 10.11.2.

Changing between "All 0" and "All 5" makes no difference to the available CPU for a fitting. Confirmed with another user using Windows Pyfa that the same fit shows different numbers for available CPU.

For reference this is the fit I was using:
```
[Venture, Venture fit]

Warp Core Stabilizer I

5MN Microwarpdrive I
Adaptive Invulnerability Field I
EM Ward Amplifier I

Miner I
Miner I
[Empty High slot]

Small Low Friction Nozzle Joints I
Small Low Friction Nozzle Joints I
Small Anti-Thermal Screen Reinforcer I


Warrior I x2
```
My Pyfa with "All 5" skills selected shows 240 CPU available. The Windows user's Pyfa shows 280 CPU available.

**Comment by thorr18** [comment]
For me, that fit (on OSX) is 240/240 on 'All-0' & 240/300 on 'All-5'

**Comment by blitzmann** [comment]
And for me, that fit on Windows 10 also shows 240/240 for All 0 and 240/300 for All 5

Switch to All 5, go to the ship stats, go to affected By tab, and hit the "Toggle View" button. Find the CPU Output attribute and expand the tree. Do you see anything there? Send screenshot.

Also, check the All 5 character in character editor (CPU Management skill) and make sure it's at 5 (I guess it's possible that a bug may have caused it to drop a level).

Also make sure that you are not using modified character skills (it will have an `*` next to character name). It's possible to temporarily modify All 5 character to check stats, but this cannot (should not, rather) be saved to the database.

**Comment by matthewpennell** [comment]
> go to the ship stats, go to affected By tab, and hit the "Toggle View" button

I can't find any of those areas in the app. By "ship stats" do you mean the data on the right? I can't see anywhere it says anything like "Affected by", or any views I can toggle.

http://i.imgur.com/yJOed42.png

**Comment by blitzmann** [comment]
Right click the fitting window -> ship stats. 
![capture](https://cloud.githubusercontent.com/assets/3904767/12591924/2426a950-c438-11e5-85db-0ac020e09254.PNG)

**Comment by matthewpennell** [comment]
I get "CPU Management * 1.25":

http://i.imgur.com/GL6sYyo.png

**Comment by blitzmann** [comment]
Nope, nothing has changed since the issue was opened, unless you are keeping up with recent repository development though git. pyfa does not automatically update (unfortunately!). Also, CREST has nothing to do with this issue (pyfa only uses CREST to push/pull fits from your personal fittings on the EVE servers)

This might have been caused by some edge case bug that presented to you. Usually these type of bugs are hard to reliably reproduce, and the calculations fix themselves when you recalculate the fit or restart pyfa. There are one or two known bugs like this with relation to projected fits and fleet boosters where if you apply them in a specific order it does not work until you recalculate the fit (usually by changing tabs). But CPU output is a very straightforward local calculation that should calculate fine unless there is an effect that is implemented incorrectly.

It is unlikely that only one particular skill would not evaluate but all other skills would from the character profile. If the All V character did not load correctly, I would expect other values to be off as well such as resists and cap. I can only speculate what happened, but the thing that makes the most sense is that you changed the All 5 skill for CPU Management (via context menu -> change affecting skill) and forgot about it. This would normally be denoted by an asterisk besides the character name. But then you mention that a Windows user seems to have had the same issue? Very odd.

For future reference though, screenshots of bug in action is extremely helpful in confirming a bug. Make sure that once you see a possible discrepancy to immediately get a pic before shutting pyfa down. Also, if you ever thing an attribute is not being calculated properly, the Affected By tab in the items  stats dialog should show you everything that is currently affected that item and by what amount. Helpful for trying to pinpoint what is off about a calculation.

I'm gonna close this issue for now. If you experience it again, please reopen and reproduction steps if possible. Also, if the Windows user still experiences this issue, have them comment here. Thx!
