### ISSUE TITLE
Information in Rows does not always refresh until UI is clicked.

### ISSUE THREAD

**Issue by bvelasquez** [pyfa-org/Pyfa#519]
Seems that information from previous groups of modules will remain in the listing until I click within the listing.  Once I click within the listing, the display will refresh and the correct data will display.

Mac OS version.  Did not happen in previous version.  Happens within Drone data grid also.

Screen shot attached.  Notice that The first two rows in the data from the "Extra Large" blasters, but displayed after selecting "Large" blasters.

![pyfa_1_19_1_-_python_fitting_assistant_and_ship_stats__myrmidon_and_mainstoryboard_ipad_storyboard](https://cloud.githubusercontent.com/assets/2302210/12996511/6a695c78-d0e5-11e5-8e66-a6986ce3de02.png)

**Comment by blitzmann** [comment]
Duplicate #453. As of right now I don't really have a good idea on why this happens, other than it seems to only happen on OS X 10.11 (please confirm this)

It did not happen for you before because you probably did not use the -mac-wx3 build. That build is now the default, as noted in the release notes.
