### ISSUE TITLE
Phantasm issue

### ISSUE THREAD

**Issue by ANDEN10** [pyfa-org/Pyfa#526]
I'm going to COPY and PASTE what was in my previous post that was closed.

i've found that the Fall-off is not changing on medium sized laser's

Please READ before closing next time. I'm clearly stating FALL OFF not TRACKING SPEED. 

FALL OFF ingame with Scorch loaded is 22km, in pyfa falloff with ANY crystal loaded stays stagnant at 7.5km..

**Comment by lunedis** [comment]
pyfa shows the "raw" optimal and falloff values,  as also seen by rightclick show info ingame.

The value you see ingame while hovering over the module icon is actually Optimal+Falloff (the distance where you do half DPS).

As laser crystals only affect optimal, and never falloff, the ingame view changes because it adds optimal and falloff together.

**Comment by ANDEN10** [comment]
What I'm looking at is not the case, if I was at my computer I'd show you. But I'm not. The falloff shows 22km and the optimal is 26km

Sent from Yahoo Mail on Android 
 
  On Sun, Mar 6, 2016 at 7:27 AM, Karl Werner<notifications@github.com> wrote:   
pyfa shows the "raw" optimal and falloff values, as also seen by rightclick show info ingame.

The value you see ingame while hovering over the module icon is actually Optimal+Falloff (the distance where you do half DPS).

As laser crystals only affect optimal, and never falloff, the ingame view changes because it adds optimal and falloff together.

**Comment by blitzmann** [comment]
I acknowledge that I misread your original ticket, and got caught up thinking it was tracking speed (since the Phantasm doesn't have a Falloff bonus). That being said, please keep the tone appropriate; your responses have an aggressive/frustrated undertone to them. Secondly, for future reference, this discussion could have continued in the previous issue, since I can easily re-open it if required (I believe you're able to do so as well, could be wrong). 

As to the issue, I still cannot reproduce with the information given. Scorch, as stated by @lunedis, does not affect falloff for the turret, nor does any crystal. So again, as I stated in response to the previous issue, if you are still experiencing problems, please post more information including exact fit. Look at the turret stats and "Affected By" tab to determine what is currently affecting the turret. Screenshots help, both pyfa and in-game. Additionally, make sure skills are up to date, and of course pyfa itself. I cannot act on "falloff doesn't update" when neither the ship hull nor the crystals affect falloff. I need more information please.

**Comment by ANDEN10** [comment]
My apologies, when I get home I'll include pictures, I'm new to this whole pyfa forum thing so idk what I can and can't do :P

Sent from Yahoo Mail on Android 
 
  On Sun, Mar 6, 2016 at 7:53 AM, blitzmann<notifications@github.com> wrote:   
I acknowledge that I misread your original ticket, and got caught up thinking it was tracking speed (since the Phantasm doesn't have a Falloff bonus). That being said, please keep the tone appropriate; your responses have an aggressive/frustrated undertone to them. Secondly, for future reference, this discussion could have continued in the previous issue, since I can easily re-open it if required (I believe you're able to do so as well, could be wrong). 

As to the issue, I still cannot reproduce with the information given. Scorch, as stated by @lunedis, does not affect falloff for the turret, nor does any crystal. So again, as I stated in response to the previous issue, if you are still experiencing problems, please post more information including exact fit. Look at the turret stats and "Affected By" tab to determine what is currently affecting the turret. Screenshots help, both pyfa and in-game. Additionally, make sure skills are up to date, and of course pyfa itself. I cannot act on "falloff doesn't update" when neither the ship hull nor the crystals affect falloff. I need more information please.

**Comment by blitzmann** [comment]
Fair enough. Next official pyfa release will hopefully be Tuesday / Wednesday, so if there is something funky going on with the calculations there's some time to fix it. Let me know =)

**Comment by blitzmann** [comment]
Any update on this issue? I will be trying to release the March changes tomorrow with the EVE patch, so I would be interested to know if there's anything about this that needs to be pursued.

**Comment by ANDEN10** [comment]
Yah, verified that I was wrong. The falloff is calculated with falloff plus optimal and it confused me

Sent from Yahoo Mail on Android 
 
  On Tue, Mar 8, 2016 at 3:50 AM, blitzmann<notifications@github.com> wrote:   
Any update on this issue? I will be trying to release the March changes tomorrow with the EVE patch, so I would be interested to know if there's anything about this that needs to be pursued.

**Comment by blitzmann** [comment]
k, thanks for verifying. =)
