### ISSUE TITLE
Damage control shows as 'on' in existing fits, even though passive module

### ISSUE THREAD

**Issue by Will-W** [pyfa-org/Pyfa#529]
Steps to repeat:
In V1.19.1, Have a fit with a Damage Control fitted and activated.
Run the version "singularity-1015913: March 2016 Pre-Release"

Expected:
Damage Control shows as 'o' symbol for online.

Actual:
Damage control shows as 'tick' for activated, even though it's now a  passive module for which this isn't an active state.

If you then turn it off, you can then (correctly) not turn it back on.

**Comment by blitzmann** [comment]
Nice catch. It's because the state the module is in is saved in the database and not checked when loaded, nor is it converted during the update procedure. I'll look into possibly doing one of these. However, it seems to be more of a graphical glitch and does not affect statistics, so if I don't get to it before release, it's not too bad. We'll see what happens =)

**Comment by blitzmann** [comment]
Went with the option of simply checking for a valid state when loading the modules from the database. 2 reasons: so that this works in all cases (in case CCP decides to mess with other modules this way), and I was lazy and didn't want to write the sql query for all items under the DC group =D

**Comment by Will-W** [comment]
Excellent!
