### ISSUE TITLE
Broken EWAR support for DPS graph

### ISSUE THREAD

**Issue by Wozbo** [pyfa-org/Pyfa#532]
WYSIWYG; Try to toggle a web and the DPS graphs to do not update for tracking/ missile explosion speed.

**Comment by blitzmann** [comment]
As stated in the release notes, I did not update graphing support for ewar modules. There wasn't enough time to look into it / I did not have the motivation to do so, and still don't at the moment due to time constraints. It may very well be a fairly simple fix, but I just did not dive into it. I will leave this issue open however so that there is something around to update with progress

**Comment by Wozbo** [comment]
I've sourced the cause of the issue; it looks like some attributes (decreaseTargetSpeed for webifiers, ewTargetPaint for target painters) did not get propagated to the new ewar,  Additionally, the new non-grappler webifiers have the attribute remoteWebifierFalloff, which I'm sure is incorrect.

This would be my first time committing to the pyfa project, do you have any resources on submitting updated data models?  I may also include heavy grappler data while I'm there.

**Comment by blitzmann** [comment]
`decreaseTargetSpeed` and `ewTargetPaint` were the old effect names. While the new effects are applied differently in the client IIRC, for the purposes of pyfa, I simply carried over the code to them (`remoteWebifierFalloff` and `remoteTargetPaintFalloff` respectively).

I'm assuming you found in `fitDps.py` where the ewar modules are applied in the graph. The code looks for modules with those specific effects and manually adds support for them in a shitty and hackish way. I'm assuming you can simply change out the old effect names with the new effect names and have it working again, although I haven't tested this, and I didn't do this myself due to the new falloff mechanics not being implemented.

Speaking of which, note that these modules now have a new attribute: `falloffEffectiveness`. You should use this if you plan to include the new effectiveness calculations for things like the stasis grappler and target painter - I believe it's the same formula as turret falloff, but again, haven't tested this. This is a bigger change, one that might be a PITA

The easiest way of submitting a patch would be to fork the repo and make the changes on a separate branch of your repo. Then you can do a pull request through github. I'll review the changes and merge if everything looks good.

**Comment by Wozbo** [comment]
#534 Submitted.  I added the falloff to TP as well, even though it's a completely miniscule affect for consistency's sake.

Do let me know what you think.

**Comment by Wozbo** [comment]
As a side note, should we add something for bounds checking 0 falloff?  This would fix any div/0 issues that may crop up in the future as the module data changes.

**Comment by blitzmann** [comment]
> As a side note, should there be something added for bounds checking 0 falloff? This would fix any div/0 issues that may crop up in the future as the module data changes.

Where specifically would that be in the code? It seems you already account for it with `elif mod.getModifiedItemAttr("falloffEffectiveness") > 0` ?

**Comment by blitzmann** [comment]
Also, I'm wanting to merge this, but I really want to test this out on SISI first to check if the falloff really is just the turret falloff. Bear with me in merging it

**Comment by Wozbo** [comment]
The issue is that there are possibly things with 0 falloff in the future.  I could move all effectiveness to check for 0 falloff in the actual effectiveness function itself instead of in the one ewar block; its *safer* that way.

This might also come into play if there is *ever* turrets with 0 falloff.

Just me doing some forward thinking there.

**Comment by blitzmann** [comment]
You can change `mod.getModifiedItemAttr("falloffEffectiveness") > 0` to just simply `mod.falloff > 0` - the `falloff` property is simply just checking to see if the module has one of various falloff attributes:

```
    @property
    def falloff(self):
        attrs = ("falloffEffectiveness", "falloff", "shipScanFalloff")
        for attr in attrs:
            falloff = self.getModifiedItemAttr(attr)
            if falloff is not None: return falloff
```

So, if you change that, then you'll never get to the point where you are dividing by a 0 falloff. =)

**Comment by Wozbo** [comment]
Ah my concern was at line 125 (in my version) of fitDps.py.  I might end up doing that anyways and just having a falloff and a tracking function that gets called when I start hitting the graphs some more.

**Comment by blitzmann** [comment]
Since I merged your PR, I'm going to go ahead and close this issue. =)
