### ISSUE TITLE
Both affecting racial skills not appearing in "change ship skills" for pirate ships

### ISSUE THREAD

**Issue by mkemnetz** [pyfa-org/Pyfa#544]
On the mac pyfa:

For example looking at a Rattlesnake only the Caldari Battleship skill appears in change ships skills but the Gallant Battleship skill does not.

**Comment by blitzmann** [comment]
1) The Gallente skill technically modifies missile damage, which is not an attribute of the ship. Instead, it should be under the Charge's affecting skills (and even then only under Kinetic or Thermal missiles, per the bonus description). Ideally it would be under the ship hull since that's where most people thing it would be, but that's not how the engine works and honestly it would be way too complicated to fix it at the moment

2) That being said, you may notice that the Gal BS skill still isn't in the charges Change Affecting Skills menu. A bug was recently reported and patched for this (#535), so this will make it out with the next release.

Hope that helps =)

**Comment by mkemnetz** [comment]
I just wanted to add that I greatly appreciate your work.  Thank you so much for the explanation on the issue.

**Comment by blitzmann** [comment]
Hey, no problem! Glad to help =)
