### ISSUE TITLE
Feature Request: Tag Fits, View Ship Listing Grouped By Tag, Search By Tag

### ISSUE THREAD

**Issue by kristinclemens** [pyfa-org/Pyfa#554]
## Summary
1. Tag fits with a key word or phrase chosen by the user, such as "WIP", "Fleet X", "New Doctrine?", etc.
2. View all fits that are Tagged, grouped by Tag, possibly including a section with all "Untagged Fits" and grouped by ship type.
3. Search for all fits with a certain Tag.

## Purpose
Pyfa can be used to organize and create fleet doctrines. This feature would enhance the functionality of that use case by adding the option to Tag a fit and view multiple fits across multiple types of ships all having the same Tag.

## Reasoning
Currently it is possible to search for fits having names which contain a certain key word or phrase. This has the drawback that searching for a certain fleet doctrine (e.g. "Home Defense Fleet") requires having that fleet doctrine in the name of the fitting. This means that unique ship fits used in multiple fleets must be duplicated within Pyfa and renamed to include the search terms / fleet name. Some examples of this include but are not limited to "AB Guardian" or "Fleet Sabre".

## Looking Forward
Ship Tagging could be utilized in the future if fleet doctrine creation and organization were to become a core feature of Pyfa rather than a happy side effect.

**Comment by blitzmann** [comment]
Duplicate #18. It's a very old feature request - not that it's difficult to accomplish, but simply that it's always been low on the priority list. I had a half-way working version of it at one time, and then other things happened that led me to basically abandon it. 

I can take another look at this within the next few months, but probably not sooner due to all the other changes going on with the april release.

**Comment by kristinclemens** [comment]
No wonder I didn't find it. :) Thanks.
