### ISSUE TITLE
Import character from evemon is not working. 

### ISSUE THREAD

**Issue by Henge9** [pyfa-org/Pyfa#557]
Hi,

I try to make a skill plan with the help of evemon and PYFA. When I make a character in evemon and export it to xml to import in pyfa it works sometime. But never for the chracters with skills added. 

This do not work. 
[Gallen (after plan Talltrash).zip](https://github.com/pyfa-org/Pyfa/files/217414/Gallen.after.plan.Talltrash.zip)

This works.
[bcal.zip](https://github.com/pyfa-org/Pyfa/files/217434/bcal.zip)

Can I check the error log or something somewhere? It just seem to say CBA FU when I try to import it... no message, not anything to start with.

Is there an expanation on how the xml should be or a program to debug it with?

Best regards,
Henge

**Comment by blitzmann** [comment]
Hi,

Sorry for not getting back sooner. I have yet to test this particular issue, but it may be related to #563. I'll look into it for the upcoming release

**Comment by blitzmann** [comment]
The reason of this is because we check for `SerializableCCPCharacter` as the first element of the document, but Gallen starts with `SerializableUriCharacter`.

I don't see much difference other than that. I will add `SerializableUriCharacter` to the check. Would you mind telling me how both these were exported? When I developed this, it was tested by exporting and after plan character.

**Comment by Henge9** [comment]
Hi,

I created a blank character, added a skillplan and exported after plan.

Thank you for your help.


[image: Inline images 1]
