### ISSUE TITLE
Citadel Pre-Release: Character API Import not working

### ISSUE THREAD

**Issue by ToshiroHasegawa** [pyfa-org/Pyfa#564]
first time trying PYFA (or any third party fitting tool - been too old school to try) I downloaded 1.20.2 cause it was the latest...  when loading char API i get the following error

http://i.imgur.com/fUMAxX3.png

tested with Char Sheet only API and Full API - same error .. 

if i type any text in i get that.

If i leave it blank i get 

http://i.imgur.com/npeppYJ.png

tested with 1.20.1 with same API and it worked right away.

**Comment by blitzmann** [comment]
This is a known issue, and was fixed locally. Also, the 1.20.2 you have (which isn't really x.x.2 perse) is a pre-release as the release description states, so it's not considered stable. It's also running off a SISI dump for the upcoming Citadel changes, so you're gonna want to use 1.20.1. If you want to stick with the beta release, a workaround for the issue is to export an EVEMon character plan and import that from File -> Import Character. I will also post the proper fix here when I get home for those others that run into the issue. =)

**Comment by ToshiroHasegawa** [comment]
im happy with 1.20.1  - just wanted to post my findings - didnt see it mentioned so thought i would try and help ..  was the known issue posted somewhere so i could have found it myself and not bothered you with what is essentially now spam? :P

**Comment by blitzmann** [comment]
Two people notified me on Tweetfleet slack; I just hadn't gotten around to creating an issue here for it yet. =P
