### ISSUE TITLE
Leviathan, Ragnarok and Erebus  Gang Boosts broken

### ISSUE THREAD

**Issue by lunedis** [pyfa-org/Pyfa#577]
Levi and Erebus boost do not work:

![image](https://cloud.githubusercontent.com/assets/9085102/14939550/1c8bccac-0f4c-11e6-9077-b2e30801daa0.png)

![image](https://cloud.githubusercontent.com/assets/9085102/14939574/b7c4c296-0f4c-11e6-8c03-0015b947c149.png)

Ragnarok boost gets overwritten by Loki even though it's stronger:
![image](https://cloud.githubusercontent.com/assets/9085102/14939568/90e6c26e-0f4c-11e6-9d71-7b3aa6029019.png)
![image](https://cloud.githubusercontent.com/assets/9085102/14939571/9e5a7ea4-0f4c-11e6-8bcd-ce54b9c7178a.png)

**Comment by blitzmann** [comment]
These are most likely caused by the skill not being taken into account. See:

https://github.com/pyfa-org/Pyfa/blob/master/eos/saveddata/fleet.py#L201

```
            for boostedAttr, boostInfoList in dict.iteritems():
                for boostInfo in boostInfoList:
                    effect, thing = boostInfo
                    # Get current boost value for given attribute, use 0 as fallback if
                    # no boosts applied yet
                    currBoostAmount = boosts.get(boostedAttr, (0,))[0]
                    # Attribute name which is used to get boost value
                    newBoostAttr = effect.getattr("gangBonus") or "commandBonus"
                    # Get boost amount for current boost
                    newBoostAmount = thing.getModifiedItemAttr(newBoostAttr) or 0
                    # If skill takes part in gang boosting, multiply by skill level
                    if type(thing) == Skill:
                        newBoostAmount *= thing.level
                    # If new boost is more powerful, replace older one with it
                    if abs(newBoostAmount) > abs(currBoostAmount):
                        boosts[boostedAttr] = (newBoostAmount, boostInfo)
```

It basically says we get a boost, get the attributes that the boost modifies, and then see if we already have a modifier affecting that attribute. If our new boost is greater than the other, then use the new one and discard the other.

The problem here is that we don't consider the skill modifier for ship role fleet boosts, so it is usually overridden by a skill boost (for the Leviathan, it uses the Siege Wrfare bonus (which is 10% due to level 5) instead of the Levi bonus (which is 7.5% as we don't consider the titan skill)).

@lunedis you mind pulling from master (specifically 941c57b4a87eb5b1616b2575d0) and checking them out?
