### ISSUE TITLE
Issue with heat on Dreadnoughts

### ISSUE THREAD

**Issue by SkylerHawk** [pyfa-org/Pyfa#583]
Toggling heat on turret dreadnoughts doesn't seem to affect their calculated dps. I'm having this issue with the Naglfar when fitted with either 2x Quad 800mm Repeating Cannon IIs or 2x Hexa 2500mm Repeating Cannon II, a Moros fitted with 3x Ion Siege Blaster II, and a Revelation with 3x Quad Mega Pulse Laser II.

**Comment by blitzmann** [comment]
This seems to be an issue on CCPs side. The overload effect (found here: https://github.com/pyfa-org/Pyfa/blob/master/eos/effects/overloadselfdamagebonus.py) is taking the `overloadDamageModifier` of the turret and boosting the `damageModifier`. The problem is that the `overloadDamageModifier` is set to `0`, which wipes out the `damageModifier`.

Confirm via data from CREST as well: https://crest-tq.eveonline.com/types/20444/

The gun also has a `overloadRofBonus` which has a value of `-15%`, but that doesn't seem to be used.

Please check in game the effects of overloading on capital guns, and I'll try to get in touch with some devs about this issue.

**Comment by blitzmann** [comment]
CCP Larrikin confirmed issue on EVE side, they are working on a fix.
