### ISSUE TITLE
Pyfa is not using a normal GUI toolkit

### ISSUE THREAD

**Issue by minlexx** [pyfa-org/Pyfa#613]
wxWidgets can hardly be called a GUI library, and problem is not only in python bindings - it is full of bugs itself, causes random crashes, etc.

If you want pyfa to continue its life, and not die in hundreds of mysterious issues, you should consider to use a different GUI, let it PyQt or maybe even pyGtk.

P.S. someone had to say this, let it be me :)

**Comment by blitzmann** [comment]
Noted. I have been wanting to play around with QT / GTK. pyfa actually started with GTK,; I am not sure what motivated the original devs to migrate to wxWidgets. I do like wxWidgets since it utilized native GUI controls. In all honestly, I thing QT controls always look a little to... bubbly. This is with zero experience in developing with it though.

If someone wants to start re-writing the GUI for Qt/GTK, it would be interesting to see a proof-of-concept as to how they look (both visually and in the code).

Regardless, this isn't going to happen until pyfa needs to be re-written, and even then it's a big if. =)
