### ISSUE TITLE
Bug: Attribute Editor does not apply effects

### ISSUE THREAD

**Issue by Aelonius** [pyfa-org/Pyfa#647]
Hi,

I have tried to use the attribute modifier but I am not seeing any values change on the ship even after reloading the fit or closing the ship down. For some reason I can not discern it does not apply the effect to the ship in Pyfa, with as result that the functionality is not working at all.

**Comment by Ebag333** [comment]
Did you try turning it off and on again?

Seriously though, there's a separate setting to turn overrides off and on, and they're not located next to each other.  The setting probably should be moved so they're found in the same menu.

**Comment by blitzmann** [comment]
Yeah, take a loot at the Edit menu, where you will see the option to turn attribute overrides on.

This is a deliberate additional step - The idea is that folks are changing attributes for a specific reason (test out changes on SISI, for example), but don't want to go back in and change them to go back to TQ. So you have a toggle. Also, this toggle does not persist - when you close pyfa, it will revert back to the Off setting - this is also deliberate so that people don't complain about off values when they forget they have overrides for the item.

Closing this issue as invalid - feel free to reopen if you're still experiencing problems =)

**Comment by Aelonius** [comment]
@blitzmann What might be useful is to put a small notification in the attribute browser that explains the process, so that it's less confusing. Got it to work now :)
