### ISSUE TITLE
Vehement role bonus isn't applying

### ISSUE THREAD

**Issue by ftsartek** [pyfa-org/Pyfa#668]
When attempting to see the DPS difference between the Moros and Vehement, the 37.5% damage role bonus doesn't appear to apply:

_**3x Damage mods, 3x T2 HAW w/ Void XL, T2 Siege**_
Vehement: http://puu.sh/pNrrF/ea91ef49d6.png 
Moros: http://puu.sh/pNrsh/b75a2dd8e1.png

_**0 Damage mods, 1x T2 HAW w/ Void XL, No Siege**_
Vehement: http://puu.sh/pNvPm/23cdaeab75.png
Moros: http://puu.sh/pNvQh/48643be3fd.png

_**Moros on left, Vehement on right (Ebag took these screenshots)**_
http://puu.sh/pNtTQ/3ce13d675b.png
http://puu.sh/pNtMV/8318735686.png

This is seemingly reproducable.

**Comment by Ebag333** [comment]
With 0 skills, and a very simple fit (T1 blaster with iron, no DPS mods), I would expect Vehement to have more DPS due to the role bonus. Instead they both have the exact same DPS. 

I took a quick peek at it, the ship shows that the role is applied, and the role gets run (with the correct damage modifier), but it doesn't show up as an applied modifier on the gun itself.

**Comment by Ebag333** [comment]
#669 

Pull request submitted to fix issue.
