### ISSUE TITLE
Shield Hardeners Affect Boost Rate

### ISSUE THREAD

**Issue by colcrunch** [pyfa-org/Pyfa#675]
For some reason the hardners on my Rattlesnake fit are changing the shield boost rate that the tool is reporting. I have double and triple checked that this does not occur in game.

**Comment by blitzmann** [comment]
Can you please post a minimal fee which describes this issue? As well as noting exactly the values that you're getting vs the values that you expect. I'll take a look at this later this week thanks

**Comment by colcrunch** [comment]
Minimal fit: 
```
[Rattlesnake, Rattlesnake fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

Pith X-Type Large Shield Booster
Caldari Navy Shield Boost Amplifier
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]
```

The Boost per second is  listed as 105.9HP/s. When I add an Adaptive Invuln II (for the purpose of the example I am using an Adaptive Invuln II, but I have confirmed that all shield hardeners change the number) it goes up to 123.4HP/s. I am expecting to see 159HP/s (508.8HP over 3.2s).

**Comment by blitzmann** [comment]
Unfortunately I don't have Deadspace and faction gear available to me on SISI to test in game. If you want to, post a fit with expected vs actual values with t1 or t2 items.

However I suspect that this is not a pyfa issue. The number you are referring to (hp/s) is calculated based on the Effective HP of this ship. That is, it is taking resistances into account. The problem here is that pyfa calculates EHP differently than EVE does in respect to it's fitting window (I believe EVE uses the lowest resist while pyfa uses an average). Because of this, the EHP is different between pyfa and EVE, and thus the effective HP/S rep is different.

It's worth mentioning that pyfa is giving the same values as O.smium, and is also fairly close to the values given by EFT.

The important thing: right click the boost module in space and go to show info. Under the attributes find boost amount - this should be the modified boost amount that you receive every cycle after skills and other bonuses have been applied. Now go to pyfa and right click the shield booster -> item stas and check the Shield boost amount in the attributes. It should match, telling you that the calculations are working and you're getting the same boost in EVE as expressed in pyfa.

Please reply if you have any questions or want to iterate on anything :)

**Comment by colcrunch** [comment]
Shield boost rate is not based on EHP though. After testing it (The HUD reports raw HP which helps a lot in proving this) I have confirmed that it is in fact not based on EHP at all. To avoid any ambiguity between EHP and HP, when talking about raw HP, I will use RHP.

As we all know hardeners only affect EHP when turned on, so if boost rate was affected by EHP then turning them on or off should change the amount that the game reports for rep rate. This however is not the case, the game reports the same number whether or not any mods are affecting the resists (and thus the EHP). 

However the previous paragraph assumes that the fitting tool in game is reporting the stats accurately and up-to-date. So lets do a real test. I undocked, turned on reps, and had a corpie shoot me, I got down to 16350 RHP (r for raw) and boosted as close to 16400 RHP as possible, the result was a jump from ~16400 to ~16900 RHP. Ok, so that is with the EHP being affected. What about with out, so I let the shield get back to 100, and turned off the hardeners. Again I was shot at and at about 15500 RHP I turned on the boost ant jumped to ~16000 RHP. 

I think this is about as concrete proof that can be obtained that boost rate is compared to RHP and not EHP.

**Comment by blitzmann** [comment]
You're correct, the shield boost rate is not affected by the EHP. I should have said that the effective boost rate is, and this is the value that is seen in pyfa. Sorry, I got confused a bit while explaining it :P

That being said, I still do not believe there is a problem with pyfa. You mentioned that you switched to raw HP (which indeed is much more straight forward), but then you listed the values of the shield boost with EHP. This is what I currently get for an ALL V character:

**EHP, Hardener off:**
![1](https://cloud.githubusercontent.com/assets/3904767/16641425/7aa504aa-43ce-11e6-8a99-74154cacee67.PNG)

**EHP, Hardener on:**
![2](https://cloud.githubusercontent.com/assets/3904767/16641426/7aa895f2-43ce-11e6-8289-c725e40d79dd.PNG)

These are the values you provided (103.5 hp/s and 86.8hp/s)

**Raw HP, Hardener off:**
![3](https://cloud.githubusercontent.com/assets/3904767/16641427/7aa9aa82-43ce-11e6-87df-e5aa5da4a59c.PNG)

**Raw HP, Hardener on:**
![4](https://cloud.githubusercontent.com/assets/3904767/16641428/7aab7eac-43ce-11e6-9974-e924b66cc822.PNG)

These are the values when switched to raw HP mode. The raw shield boost matches what you expect at 93.8hp/s (within reason - CCP and pyfa do not use the [same rounding](http://cdn1.eveonline.com/www/newssystem/media/66437/1/rounding.png) =P). 

Let me know if there are still issues. =)

**Comment by colcrunch** [comment]
Ok, now it makse sense to me, it was not clear that the HP button changed ALL mentions of HP. I assumed that the HP/s in recharge rates were, as they are in the game, in HP versus EHP..

 Maybe it would be a good idea to add to the recharge rates section some indication of which number you are receiving, since it would be logical for someone to assume that the default would be to mirror the in game setup and default stats displays as close as possible.

**Comment by blitzmann** [comment]
Perhaps I will rename the section to `Effective Recharge Rates` or something to the effect. However, this is the way pretty much all other fitting programs do it - EVE is special in that it shows you reps based on a straight boost / duration. I've always been of the opinion that the in game fitting window is kind of meh, and so pyfa doesn't strive to mirror that data by default.

Glad it was cleared up though. Cheers! :)
