### ISSUE TITLE
All 5 character not working properly

### ISSUE THREAD

**Issue by darsain** [pyfa-org/Pyfa#676]
Haven't played for 3 years, so I might be noobing out and not be doing something obvious :) but when I use All 5 character it actually underperformes to my old 37M skill points character.

<details>
<summary>All 5:</summary>![pyfa_5](https://cloud.githubusercontent.com/assets/538801/16650563/2454103e-443f-11e6-9489-98d73fedfa31.png)
</details>

<details>
<summary>Normal char:</summary>![pyfa_dar](https://cloud.githubusercontent.com/assets/538801/16650570/2d56f3c2-443f-11e6-84d9-f25ce5573f08.png)
</details>

**Comment by blitzmann** [comment]
First of all, what is this details / summary html voodoo? I've never seen this, that's awesome!

Secondly... you haven't played for 3 years. If this is the same database from three years ago, I am almost positive that it's a desync of the all 5 character due to missing skills. WHile this shouldn't happen (it should be refreshed with any new data every time pyfa launches), it's possible given the stale data.

If it's a completely new character, I dunno what could be the problem. 

Regardless, could you send over your `%userprofile%\.pyfa\saveddata.db` to sable.blitzmann@gmail.com? I can take a look and hopefully diagnose exactly what's going on. =)

**Comment by darsain** [comment]
`saveddata.db` sent.

Thx for pointers. My old fittings weren't loading anyway, so I've just renamed the  `~/.pyfa` folder and let it refresh with new one, and the new stuff seems to work properly now.

> First of all, what is this details / summary html voodoo? I've never seen this, that's awesome!

Just HTML `<details>` tag :) There is push for Github to implement some better support for it, or some alternative. Unfortunately raw `<details>` works only in Chrome atm.

**Comment by blitzmann** [comment]
Yeah, your all 5 character only has 60 skills in the database, while mine has 420. Definitely some corruption there, which is to be expected considering the age of the database. There was a point about 1.5 years ago I think where we broke support for older upgrade migrations, so if you had a very old database and ran a new update process on it, it wouldn't work right.

@Ebag333 recently implemented a sort of DB refresh feature that I'd like to tap into to fix All 0/5 character corruption in case things like this happens in the future. :)
