### ISSUE TITLE
Targeting System Stabilizer rigs do not disable effect when disabled

### ISSUE THREAD

**Issue by Cribbit** [pyfa-org/Pyfa#696]
Clicking the yellow circle to turn it to the red x of disabled does not change the stated cloak delay, but does change the shield amount. 

Appears to happen on all sizes & tech levels of the rig, and with any profile. 

Fit:

[Cruor, test]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Improved Cloaking Device II
[Empty High slot]
[Empty High slot]
[Empty High slot]

Small Targeting Systems Stabilizer II /OFFLINE
Small Targeting Systems Stabilizer I /OFFLINE
[Empty Rig slot]

This will still show 7.65s cloak delay, as if the rigs were enabled. However, shield EHP will be 828, correct for the disabled rigs.

**Comment by blitzmann** [comment]
is this how it works in the game?

The effect is currently set to run even when the module is offline. This is probably an error (espcially since the last tweak to this effect was by Kadesh in '13, and offlining rigs in pyfa wasn't a thing until '15), so I'm going to fix it now. But if you could confirm that everything works as expected in the EVE client that would be great :)

**Comment by Cribbit** [comment]
I'm not on right now so I can't test but I don't think rigs have the concept of 'offline', only fit or not. However, every other rig in Pyfa can be 'offlined' to stop showing the effect, without fully unfitting. This makes sense from a user perspective to show how much rigs are helping you without the effort of unfitting and refitting constantly.

**Comment by blitzmann** [comment]
Wow, yeah, you're correct. I was getting the client and pyfa confused haha. Thanks for the bug report
