### ISSUE TITLE
Warp time calculation for variative length

### ISSUE THREAD

**Issue by evrial** [pyfa-org/Pyfa#703]
Would be cool to have such instrument of comparing time and distance from warp start to warp complete including all parameters: align time, warp acceleration, cruise speed and deceleration in comparison with implant sets Ascendancy or Nomad.
Warp equation curve here is an excellent example https://community.eveonline.com/news/dev-blogs/warp-drive-active

**Comment by blitzmann** [comment]
I've thought of this before, but I think this would be better suited to being a graph for the ship since it's variable. The problem with that is that I, nor anyone else, wants to touch the graphing code (needs a complete overhaul).

Another idea would be to create a simple window that you spawn from a right click menu that opens a window that simply contains a text box and a calculated value. This would be the ghetto, janky way, but relatively easy.

**Comment by DarkFenX** [comment]
Was implemented few releases ago
