### ISSUE TITLE
'Save as' greyed out on new character?

### ISSUE THREAD

**Issue by amkoc** [pyfa-org/Pyfa#715]
Won't let me hit 'save as' if I make a character and manually add skills, not sure how to save the character and send it to people otherwise...

**Comment by blitzmann** [comment]
The save and save as buttons are only useful if you modify the skills outside of the character editor. So, for example, if you are fitting a Retribution, and right click the ship -> Change affecting skills, and change some skills there to see how that affects the fitting as a whole. Those skill changes are temporary. in order to save those changes, you go to the character editor and hit "save" or "save as". 

However, if you change skills within the character editor itself, then it's assumed that you want to permanently change them, and so they are saved automatically. Thus, those buttons are greyed out as there is nothing to save.

Hope that clears it up. Let me know if you have any other questions :)

**Comment by amkoc** [comment]
Ah I assumed they were export buttons to save them to a file to be used in other people's installations of Pyfa.
