### ISSUE TITLE
Feature request: flag setups by skills

### ISSUE THREAD

**Issue by muaddib78** [pyfa-org/Pyfa#719]
using api imported character highlight all items that that character cannot currently fit due to missing skills or online due to inadequate CPU/grid

**Comment by blitzmann** [comment]
Can you go into a little more detail with what you are requesting? Do you mean highlight the items in the fitting window or highlight them in the market window?

**Comment by muaddib78** [comment]
if i import a fit into pyfa and it has module i cannot currently fit to ship mark it with a red dot and when you hover over it it states "module requires Skill A/B/C to fit." skills being the primary secondary and soforth needed to fit the module.

example: i want to fit a stasis webifier II and dont have the skills, it will tell me i need navigation II CPU management III and propulsion jamming IV to fit it

if i can fit it but lack CPU/grid to online it mark it yellow and hover text states " requires x% more CPU/Grid to online train skill X or fit implant Y" skill X being either a skill that will increase CPU/grid of the character or decrease the CPU/grid requirements of the module.

example: im 3 tf CPU short of turning on that webber II, i can either implant a EE-605 for a 5% bonus to CPU or train CPU management to IV to gain 5% more CPU

**Comment by blitzmann** [comment]
Looking through older issues here, want to address this one.

@muaddib78 So, there's two requests here: Flag an item that you don't have skills for, and also give suggestions about what you should do in order to get that item working.

I immediately think of this comic: https://xkcd.com/1425/

the first one is easy, and something pyfa already does. If you don't have the skills for something, the skillbook in the top right turns red. Hovering over it shows you the skills that are required. You can even get a breakdown of which item needs which skills by going to Settings > General and deselecting "Compact skills needed tooltip". The tooltip will then show you what skills you need for each item. Additionally, there is a new feature in v1.29 that allows you to right click the skill icon and choose the option to raise skills of the character to the minimum required for the fit.

As to the second thing, this is much, much harder, and probably way too complicated for our current structure (at least, I can't think of anyway to address it). The problem lies in the fact that there is no easy way to say "these items give a 3% boost to CPU". I mean, we can look at items that have a list of known attributes that modify cpu and pwrgrid, but that would be a hardcoded list, extremely difficult to maintain, and not scalable. Not only that, but it's the effects themselves that dictate which attributes modify other attributes. A `cpuBonus` attribute on one item may give this ship more CPU, or it may decrease the CPU needed for other certain items. There's no way to know without the effect, and there's no way that I can see to implement pyfa effects in that way. And if those issues were to be solved, I worry what the performance would be like trying to analyze the fit and determine what kind of changes need to be done to ink out more CPU/PWR. :/

Giving suggestions is a very cool concept, unfortunately it falls more towards the bottom half of that comic. Not saying it's impossible, but I at least don't see a way forward in regards to that feature. :)

**Comment by blitzmann** [comment]
I'm going to go ahead and close this issue. I've revisited it every now and then to try to figure out how to solve for the issue of calculating things against the fit to give a suggestion on what to fit... and haven't really come up with anything in my ponderings. Unfortunately I don't think that will ever really be feasible, at least with pyfa's current codebase wiithout doing some major work to the engine behind it.

As stated, the other issue should already be a thing - just hover over the skillbook to see what skills you don't have access to. :)
