### ISSUE TITLE
Pyfa hangs and does not load fit for specific fits (Windows+Mac)

### ISSUE THREAD

**Issue by mkemnetz** [pyfa-org/Pyfa#724]
Pyfa will not load any fit for the ishtar.  I can also create a new Ishtar fit, but I cannot add any modules to the fit.  This also occurs for the VNI, but no other ship as far as I can tell.

**Comment by blitzmann** [comment]
I can do it just fine... The module you are trying to add wouldn't happen to be the omnidirectional tracking enhancer would it? There's a known issue with that, which is fixed with the v1.23.2 release (should be out in the next 15 minutes)

If you're still having issues with the newest release, please provide any more details that you can. :)

**Comment by mkemnetz** [comment]
That's it!  All the fits that have trouble are fits with an omnidirectional tracking enhancer fit!  Sorry I missed that issue if it is in the notes.
