### ISSUE TITLE
Wrong calculations for HP and capacitor

### ISSUE THREAD

**Issue by haggen** [pyfa-org/Pyfa#730]
In the screenshots below pay attention to:

1. ~~The hitpoints being reported and~~ 
2. Capacitor regeneration vs capacitor being used and at which % it's stable.

![pyfa](https://cloud.githubusercontent.com/assets/270076/18424148/119e4464-7883-11e6-83c7-6e60287826cc.jpg)

![eve](https://cloud.githubusercontent.com/assets/270076/18424151/1753a7be-7883-11e6-813f-85de1c73b01f.jpg)

The capacitor shouldn't be stable at 43% since it regenerates ~12 but uses ~11 per second. Now the HP I couldn't tell what's wrong but it's not the same value the game reports. I double checked the fit, it is the same and my skills were fetched via API.

Did I miss something? Do you need more information?

**Update.**

Sorry, there was a difference in the fit, still the EHP values seem very different: 28.9 in Pyfa and 24.3 in EVE. But I'd assume Pyfa and EVE use different formulas. The capacitor still seem odd though.

**Comment by blitzmann** [comment]
EHP in pyfa should not be compared to EHP in EVE. IIRC, EVE uses lowest resist to calculate effective HP, while pyfa uses the average (I think) of all resists. So yes, they are different formulas. :)

>The capacitor shouldn't be stable at 43% since it regenerates ~12 but uses ~11 per second

Why do you believe this is not correct? The stability value is the result of a simulation, where all active modules are put through a 24 hour simulation which also takes the capacitor recharge rate as well as any cap boosts / drains into account, and determines if the cap ever levels off at a percentage (is cap stable) or not (is cap unstable).  While it is not 100% perfect (every program seems to calculate this a bit differently, and rounded numbers may affect the output), it is usually within +/- 1% from what I've seen (edge cases aside). I doubt there is something so grievous in the cap sim code to cause issue.

It is also important to remember that cap recharge is not a linear function. Cap recharge is higher near 25-30% than it is around 90%. So it's inappropriate to use the values given for cap + and cap - to try to determine cap stability, without running the simulation and taking into consideration the cap recharge formula (http://wiki.eveuniversity.org/Capacitor_Recharge_Rate).

hope that helps. I'll close this as a non-issue. If you feel the need to reopen it or clarify, simply post a comment. =D

**Comment by haggen** [comment]
That was very helpful thanks lot! But the % at which the cap gets stable still off to me; the game reports 8% but Pyfa reports 41%.

**Comment by blitzmann** [comment]
Oh, you means it's off in the game?

Yeah, again, the client is kinda ehhh when it comes to things like this. If the client is saying 8%, I would then doubt it's taking it's own formula into account. I don't believe it's possible to have cap stability that low since the most effect recharge rate is ~25-30%. If it was going to be stable it will hover around here. After ~25% the rate starts to fail and become less effective, so if it wasn't stable at 25%, it won't be stable at 8%.

Could be wrong, but knowing how funky the ingame fitting screen is with it's values, I chalk it up to another inconsistency with the game. :)

**Comment by haggen** [comment]
So you would trust Pyfa before the game? Mas that's depressing. :( Well, it's sad that the game, which should be the reference is so clumsy. But I'm glad there're tools like Pyfa. Thanks again mate! o7

**Comment by blitzmann** [comment]
Yes, I would absolutely trust pyfa over the game. I also checked with a few other fitting programs and they all show similar cap stability values. 

Some folks wonder why we don't try to mimic exactly what the game shows. The simple answer is that the game is wrong. pyfa is a specialty program designed to specifically do things like this. The in-game fitting window doesn't try to be a fitting program, instead it's designed to be a more general overview, and so they don't put as much importance on it's accuracy (in face, I doubt much work has been done to the fitting screen's calculations since it released a few years ago).

If you have further questions, feel free o7
