### ISSUE TITLE
Capacitor stats completely wrong

### ISSUE THREAD

**Issue by TrentonAdams** [pyfa-org/Pyfa#734]
This is not even close to cap stable, for a fit, and yet it shows 80.2% cap stable.  I've got my character selected, but I'd imagine that even with all L5 skills, you'd never get it to be cap stable.  I spent a whole whack of time making the fit because it was looking so good, only to find out it's -109% cap.

[Gila, Gila C4 test]

Shield Power Relay II
Shield Power Relay II
Shield Power Relay II

Large Shield Extender II
Large Shield Extender II
Adaptive Invulnerability Field II
Adaptive Invulnerability Field II
Large Shield Extender II
10MN Monopropellant Enduring Afterburner

Corpum B-Type Medium Energy Nosferatu
Drone Link Augmentor II
Prototype 'Arbalest' Rapid Light Missile Launcher
Prototype 'Arbalest' Rapid Light Missile Launcher
Prototype 'Arbalest' Rapid Light Missile Launcher

Medium Core Defense Field Purger II
Medium Core Defense Field Purger II
Medium Core Defense Field Purger II

Medium Armor Maintenance Bot I x2
Hammerhead II x7

Scourge Light Missile x3010
Inferno Light Missile x3255
Nanite Repair Paste x135
Sisters Core Scanner Probe x8

**Comment by OISumeko** [comment]
Pyfa capacitor calculations will assume that you are in the optimal range for your Nosferatu and that the target can actually be NOS'ed. Are you using the module in optimal? NOS'ing rats or players?

**Comment by Ebag333** [comment]
What @OISumeko said.

Additionally, NOS has broken on rats.  It used to work, but hasn't at least since the neut/nos modules went through tiericide.  (Supposedly there are some NPCs out there that actually have capacitor, and those it _might_ still work on, but CCP won't tell me which NPCs those are :( ).

So without the nos and with V skills it shows you only have 6 minutes of cap running everything.

You also need to keep in mind that this is an estimate.  It takes the various modules and breaks out their X GJ over Y seconds into GJ/s.  This means that your cap will behave differently in game, because it doesn't take a little bit each second, it grabs all the cap at once (which changes how fast your regen).  So it can very much matter _when_ your modules cycle.

The in game fitting window is also quite bad at estimating how much cap you're using.  I've tested it a number of times, and it tends to be overly pessimistic.  I've had fits with only 15 mins of cap (according to in game) that ran for well over an hour running everything.

There's a reason why CCP is throwing out the in game fitting tool and starting over from scratch on it.

**Comment by TrentonAdams** [comment]
Sorry, you must be correct.  I have seen most fits report cap stability the same as eve does, so I'm guessing this must have been it.  Sorry for the wasted time.

Oddly, I just received a notification of these posts today.  Odd indeed.

**Comment by blitzmann** [comment]
No worries, it's always best to open a potential issue and get it figured out. :)
