### ISSUE TITLE
Wrong power requirement for Med. F-S9 Regolith Shield Extender

### ISSUE THREAD

**Issue by haggen** [pyfa-org/Pyfa#742]
Pyfa says a Medium F-S9 Regolith Compact Shield Extender requires `20.8` MW of power to work, but in the game it says `26`. Pretty bummed that I can't fit my fit. :(

This is odd, in the module stats window it shows the correct value 26. But when I fit it into my Prospect it only consumes `20.8`.

Oh I see now, it's something with the skills, if I change the skill profile it also changes the power requirement. See http://g.recordit.co/zMB5yUC1fN.gif

**Comment by blitzmann** [comment]
Yes, changing the skills will normally result in a change of stats for many modules. That's how EVE works. All 0 has all skills set to 0, so they do not get any bonuses. Your character has certain skills trained that reduce the power consumption of that module, hence it shows as less than the base stat (26).

You can see which skills are affecting the module by opening up the item stats and going to the affected by tab. That will show you all the modules modifications. :)

This is working as intended. If you still have questions / unsure of the calculations, feel free to continue posting in this thread. =)

**Comment by haggen** [comment]
Then why I can't fit this fitting?  Specifically the shield extender still takes 26 MW in game for me.

**Comment by blitzmann** [comment]
Is your pyfa character linked to your EVE character via API? Are the pyfa skills updated? This could be an issue of skills not being synced correctly, although that is odd because it would usually be the other way around (pyfa skills being outdated, so it would show harsher fitting requirements in pyfa).

They did just release an update last week that worked on mining ships, maybe the shield stats were changed as well? I haven't looked at the details of the update yet.

Also look at things like rigs and other modules to ensure you have everything else correct , and make sure you double check implants. 

If the skills are synced correctly, Them there is something funky going on. If that's the case, do me a favor and submit your character sheet to http://eveboard.com/. You can apply a password to it if you wish, and then email me the password and your `%userprofile\.pyfa\saveddata.db%` file to sable.blitzman@gmail.com. I'll reopen the issue and take a look.

**Comment by blitzmann** [comment]
Oh, you know what, I just realized the fit you posted is a mining ship. I bet you that this is due to those recent changes not being in pyfa yet. See #727 and #741

**Comment by haggen** [comment]
It's a Prospect but I don't see any changes to the Prospect or to Gas Harvesters in the patch notes.

Anyways, here's everything you asked:

1. Yes my character is linked to Pyfa via API. 
2. Yes my skills in Pyfa were synced.
3. Modules and rigs check, I'm using the very same fit I built in Pyfa. (Used copy+paste.)
4. My character: http://eveboard.com/pilot/Jason_Chorant password is `pyfaisthebest`.
5. Here's my saveddata.db: [saveddata.zip](https://github.com/pyfa-org/Pyfa/files/478828/saveddata.zip)

**Comment by Ebag333** [comment]
```
	Shield Upgrades / Rank 2 / Level: 4 / SP: 90,510 of 512,000
```

This is why.

At 0 skills (base) a `Medium F-S9 Regolith Compact Shield Extender` takes 26 MW.  The skill `Shield Upgrades` gives a 5% reduction per level (so we start at 1, and reduce by .05 each level).

```
Level: Base*Modified = Modified Value
0: 26*1 = 26
1: 26*.95 = 24.7
2: 26*.90 = 23.4
3: 26*.85 = 22.1
4: 26*.80 = 20.8
5: 26*.75 = 19.5
```

Your screenshots show that you're getting 20.8 MW for the MSE, which is correct.

In game the module will either show 20.8 or 26 _depending on how you look at it_.  If you look at just the module itself (from a saved fit, the market, a link, etc) then it'll show 26.  If you have everything fitted (and I believe it has to be online as well) then you can right click and show info and see the modified stats.  This can be a be problematic, I've heard of people having to undock to see the proper stats (for some reason BitB wasn't calculating properly).

For your character in Pyfa, how did you build that?  Is that an API import, a skill file import (like from EVEMon), or hand built?

**Comment by haggen** [comment]
@Ebag333 My character was imported via API.

**Comment by Ebag333** [comment]
Have you updated the API?

**Comment by haggen** [comment]
@Ebag333 Yes I did. I've answered those questions 5 comments above.

**Comment by Ebag333** [comment]
Fair enough. I'm not sure what the difference is, but it's not the shield extender.

**Comment by haggen** [comment]
Well, I'll recheck everything later today (right now I'm at work) just to make sure it's not my mistake.

**Comment by Ebag333** [comment]
Can you export the fit from EVE and post here?

**Comment by haggen** [comment]
From EVE:

```
[Prospect, Effluvia]

Warp Core Stabilizer I
Warp Core Stabilizer I
Nanofiber Internal Structure II
Damage Control II

5MN Cold-Gas Enduring Microwarpdrive
Adaptive Invulnerability Field II
Medium F-S9 Regolith Compact Shield Extender

Gas Cloud Harvester II
Gas Cloud Harvester II
Covert Ops Cloaking Device II

Small Low Friction Nozzle Joints I
Small Anti-EM Screen Reinforcer I
```

From Pyfa:

```
[Prospect, Prospect fit]

Warp Core Stabilizer I
Warp Core Stabilizer I
Nanofiber Internal Structure II
Damage Control II

5MN Cold-Gas Enduring Microwarpdrive
Adaptive Invulnerability Field II
Medium F-S9 Regolith Compact Shield Extender

Gas Cloud Harvester II
Gas Cloud Harvester II
Covert Ops Cloaking Device II

Small Low Friction Nozzle Joints I
Small Anti-EM Screen Reinforcer I
```

**Comment by Ebag333** [comment]
I looked everything over, it all looks okay.  I don't see any obvious issues.

While I haven't fit a Prospect (I don't mine), I've fit most of those modules and none of the values are jumping out at me as not matching in game.

If you're using multifit, I have run into times when it doesn't fit things properly because it thinks you're out of PG/CPU.  Usually this is because you have PG/CPU mods you're adding, and it's not adding those first, but I have seen it get triggered by skills.  Usually hand fitting fixes that.

The only thing I can really say is you can go through the modules and make sure that the in game number matches the values in Pyfa, but none of these modules have changed recently and the vast majority of them are used so often that if there was an issue with them, we'd likely be hearing a lot more reports about it.

**Comment by blitzmann** [comment]
@haggen, this is going to be a really dumb question, but I'm just covering my bases... you have, in the game, tried to literally fit the shield extender onto the ship, correct? You aren't going by just the values you see on the item's info screen from the market or something, are you?

The reason I want to make sure is because sometimes people like to check the modules stats before fitting it, and they see that they don't match with <insert fitting tool here>. The reason for this is because when you show info on a module that is not currently fit to a ship, it only shows its base values and not the modified values based on skills.

Let me know. Otherwise, I haven't had a chance to personally look into anything here yet, but will hopefully do so this weekend. :)

**Comment by haggen** [comment]
Not dumb at all, as I developer who deals with users in a daily basis I totally understand why you'd ask me that.

Yes I tried to fit the shield extender, that's actually when I found out I couldn't. At first I even thought I misclicked something since the fit was designed in Pyfa and it was okay.

Work cough up with me and I haven't had the time myself to check things again but I'll probably do it tonight around 9pm (it's 3pm here right now).

I'll reset my Pyfa installation and then try again and let you now if I find anything.

Thanks a lot for the support so far.

**Comment by blitzmann** [comment]
@haggen just following up on this, are you still having this issue?

If so, I think it's time I looked at the data directly. Please send me your user database (`%userprofile%\.pyfa\saveddata.db`) and your eve database (pyfa directory > eve.db). also, confirm with me which character you're seeing the issue with, as well as the fit (if it's changed from above)

Thanks :)

**Comment by blitzmann** [comment]
Closing this due to being unable to reproduce. If you're still experiencing this issue, please open a new issue and send me the data requested (saveddata.db, eve.db, and information pertaining to the fit such as character used, modules,  used, etc).

Thanks!
