### ISSUE TITLE
Mac version doesn't work very well.

### ISSUE THREAD

**Issue by ReallyReallyReally** [pyfa-org/Pyfa#747]
Where to begin?
Character editing doesn't work unless using command key short cuts, save buttons don't work, drop down menus don't work. This application is incomplete, why is this half assed crap linked as a stable build?  Thanks for wasting 50 megs of my data plan.

**Comment by Kyria** [comment]
Maybe you can just start by giving your OSX version, where you downloaded it (github release / homebrew), how you started it, with more precise details on your issues (steps) _and being a little more gentle_ ? So maybe people who work on Pyfa may be able to help you...

**Comment by blitzmann** [comment]
>Where to begin?
Character editing doesn't work unless using command key short cuts, save buttons don't work, drop down menus don't work. This application is incomplete, why is this half assed crap linked as a stable build? Thanks for wasting 50 megs of my data plan.

@ReallyReallyReally Ignoring the trolling, let me respond with an actual response in case someone is ever unfortunate enough to stumble upon this issue with a google search...

OS X does indeed have a lot of issues. Most of these issues stem from us upgrading from wxWidgets 2.8 to 3.0.2. OS X 10.11 also seemed to change something that makes the application slower when it comes to animations as well as some user controls being broken. The actual reasons for these are way above my head for two reasons: the issues seem to stem from the low-level integration of wxWidgets with OS X, and I am not a wx developer. Additionally, I'm not a Mac developer, or even user, and it's difficult for me to actually get into OS X to do and run tests. 

https://github.com/pyfa-org/Pyfa/issues?q=is%3Aopen+is%3Aissue+label%3Aosx

I've done my due diligence in trying to address these issues (see [here](http://stackoverflow.com/questions/35370836/animation-slowdown-on-os-x-10-11), [here](http://stackoverflow.com/questions/31823885/osx-dialog-destroy-hangs-program-in-wxpython-3-0), and various google groups postings), but there's only so much I can do. pyfa needs a developer who primarily works on a Mac so that they can catch and address 

That being said, the last I checked pyfa is completely usable, even if it is a little sluggish. Gauge animation lag was addressed with an option to disable animations in the preferences, which helps in that regard. I haven't actually tested pyfa in a Mac in a while due to complications on my end (my hackintosh partition blew up, and it's a PITA to get it working again). There may be changes recently that have been implemented that further break pyfa in OS X, but as far as I'm aware there haven't, and there haven't been any recent issues reported.

Trolling aside, if you are having breaking issues, it would be wonderful if you actually broke them down for me so that I can assess where I need prioritize. For example, if I know that the character editor is totally trashed in OS X, that's a reason for me to take the time to get OS X up and running and figure out what's going on.  Which drop down menus are broken? What features don't work as expected? Feel free to open up new issues to do this, or add them to existing issues, or just list them here.

I am very willing to work with users to try to figure out what is happening when something is broken, but I need users to be detailed, specific, and include reproduction steps. Otherwise, you're bitching just to bitch without actually contributing, and I'm left in the dark without any actionable information.

Additionally, if it's completely unusable for you, try the deprecated version. It does not have CREST integration nor an attribute editor, but it's using the old wxWidgets 2.8 and seems to have less issues across the various OS X versions. 

Finally, I'll end with this disclaimer, which is noted throughout the source code, and is the gist of the LICENSE file included with pyfa.

```
# pyfa is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with pyfa.  If not, see <http://www.gnu.org/licenses/>.
```
