### ISSUE TITLE
Citadel import fails

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#749]
Looks like when we hit like 312 of `port.py` we end up getting `None` for `fit.ship`

```
        try:
            ship = sMkt.getItem(shipType)
            fit.ship = Ship(ship)
            fit.name = fitName
        except:
            return
```

Playing around a little with this in #744

**Comment by blitzmann** [comment]
Yeah, it's because we used to assume everything is a ship. You can fix this with a try / catch, like how we do when creating a new ship:

https://github.com/pyfa-org/Pyfa/blob/master/service/fit.py#L161

Also, for pull requests, try to limit one request per issue if possible. Lumping multiple things together gets hairy ;)
