### ISSUE TITLE
UNLIMITED POWAAAAAAAAAR!!!!! missing calculations

### ISSUE THREAD

**Issue by Rylleyryelle** [pyfa-org/Pyfa#755]
ebag helped me get pyfa running because hes trying to get me off of eft for some reason.. but so far im going to have to stick to that because this just isnt working. it opens now, but its not calculating basic things.

**1-** Fighters
**1. A** Fighter DPS Not Calculated:
i put in my fighters in my carrier and it still says 0.0 DPS. i click the fighters tab and it says 3/3 light fighters, they all 3 have checkmarks, but nothing. 0 dps.
**1.B** Fighter Abilities Missing:
on top of the fighters just not applying dps at all to the display, their abilities are missing. it just says "Active Abilities -- None" for every single fighter
**1.C** Fighter Control Range:
when using fighters, pyfa seems to think the standard 60km base range is correct, this should be corrected to 400km when using fighters
**2-** Pyfa still lets you fit subcap drones into carriers (example Warrior II into an Archon)

**Comment by blitzmann** [comment]
Hey there. Let me try to clear a few of these up for you :)

> 1. A Fighter DPS Not Calculated:
i put in my fighters in my carrier and it still says 0.0 DPS. i click the fighters tab and it says 3/3 light fighters, they all 3 have checkmarks, but nothing. 0 dps.

>1.B Fighter Abilities Missing:
on top of the fighters just not applying dps at all to the display, their abilities are missing. it just says "Active Abilities -- None" for every single fighter

There isn't any DPS because you probably didn't set any abilities. To do so, right click the fighter group and select the abilities to apply. Unlike other drones and module, pyfa doesn't activate anything by default for fighters, since there are multiple things to choose from. I could put a note stating `(right click for abilities)` to help with the confusion, that should be easy enough. :)

> 1.C Fighter Control Range:
when using fighters, pyfa seems to think the standard 60km base range is correct, this should be corrected to 400km when using fighters

This is a valid concern. The 60km range is dictated directly from one of the drone skills IIRC. I must have missed that fighters have their own (is it always 400?). Will check. 

> 2- Pyfa still lets you fit subcap drones into carriers (example Warrior II into an Archon)

This is true for any fit, and it's a design thing. We don't restrict any ship from fitting regular drones. You can put 30 Warrior IIs in a Retribution is you like. However, you will notice that the drone bay is over capacity for any ship that doesn't allow for it. 

the reason for this: We never really had the mechanism in place to disable the Additional panes at the bottom before the Citadel release. But additionally, I'm not sure I want to mess with this. If CCP ever releases an update that removes the drone bay for a ship, we then need to make sure the drones are removed as well, but this (automatic removal of modules from fits) goes against design of pyfa (we try not to touch user data if at all possible. I certainly would not want my data erased just because the fit no longer supports a bay or a slot. This is why we have a red background for fits that have too many modules). This problem is worsened if the drone bay is simply reduced since we won't know *which* drones to remove. So we leave the option open to add them to any fit and show the user in a prominent location (resources heading) that those drones are not supported.

> it opens now

Were you having difficulty in installing it? What was the installation method?)

Anyway, hope this clears a few things up. I will definitely try to get the fighter drone control range in there. Feel free to ask any more questions.

**Comment by Rylleyryelle** [comment]
> There isn't any DPS because you probably didn't set any abilities. To do so, right click the fighter group and select the abilities to apply. Unlike other drones and module, pyfa doesn't activate anything by default for fighters, since there are multiple things to choose from. I could put a note stating (right click for abilities) to help with the confusion, that should be easy enough. :)

fighters deal auto attack damage regardless of if youre using their abilities or not. just consider them pewpewdrones until you hit the button to make them engage their special ability. yes you have to hit a button BESIDES F to make them engage, but they have 2-3 "abilities".
1- Engage target (turn on turrets) <-- should be counted by default in dps as it's always active when engaging target. Consider this one "pressing f"
2- Use Special 1 (example pewpew rocket salvo/torpedohell)
3- Use Special 2 (example zoomzoom MWD)

> This is a valid concern. The 60km range is dictated directly from one of the drone skills IIRC. I must have missed that fighters have their own (is it always 400?). Will check. 

fighters dont have "control ranges" .. they work at whatever range you can lock at, and they never go out of range, so you can technically throw drones to attack something within whatever you can lock at, then they can kite your fighters 8,000km away to grid edge and theyll still be chasing them (easiest way to get them back is to just warp, the fighters will follow you)
if you dont have a target because it got out of your range, theyll still chase what you sent them after, you just wont be able to tell your drones to use their abilities (except speed ones like Locus II > Evasive Maneuvers as it just tells them to enable mwd, doesnt require a target)

> This is true for any fit, and it's a design thing. We don't restrict any ship from fitting regular drones. You can put 30 Warrior IIs in a Retribution is you like. However, you will notice that the drone bay is over capacity for any ship that doesn't allow for it. 

couldnt you just use the "Drone Capacity 0 m3" attribute to go hey you double clicked warrior IIs, check for drone capacity, 0? hahaha nope. kinda light trying to add an extra high slot, it just doesnt do it.
dont need to hide the pane or anything, just dooooooooont add it.

**Comment by Ebag333** [comment]
>fighters deal auto attack damage regardless of if youre using their abilities or not. just consider them pewpewdrones until you hit the button to make them engage their special ability. yes you have to hit a button BESIDES F to make them engage, but they have 2-3 "abilities".
>1- Engage target (turn on turrets) <-- should be counted by default in dps as it's always active when engaging target. Consider this one "pressing f"
>2- Use Special 1 (example pewpew rocket salvo/torpedohell)
>3- Use Special 2 (example zoomzoom MWD)

Maybe @blitzmann has a better idea, but to me in the backend it's not necessarily clear what's the primary attack and the special attack.

I find the number of clicks you need to make annoying, but as a carrier pilot you should be used to that. :rimshot:

A better solution would be to allow multiselect on fighters, like we do on modules.

>fighters dont have "control ranges" .. they work at whatever range you can lock at, and they never go out of range

This is true, carriers don't care about drone control range at all.  I don't think we need to worry too much about it, since you can already see lock range and most carrier pilots are aware of that mechanic.

>couldnt you just use the "Drone Capacity 0 m3" attribute to go hey you double clicked warrior IIs, check for drone capacity, 0? hahaha nope. kinda light trying to add an extra high slot, it just doesnt do it. dont need to hide the pane or anything, just dooooooooont add it.

There's legitimate reasons for allowing you to add drones to ships when you're over the limit, or couldn't normally add it.

We allow people to add Large guns to frigates, for example.  So there's other areas where we have precedence for it.

There's also times when I'll be very badly over my drone bay, because I want to compare different drones against each other without having to drop the existing ones and add new ones.

There's also cases where CCP might be adding additional bandwidth/drone bay, so by allowing people to go over the current limit they can see what it looks like (without needing change on our part).  Yes, they could use overrides, but those are confusing to end users.

(Almost) nothing in Pyfa prevents you from going over the limit.  In fact, I think the only limits we actually enforce are:
A) Modules (can't fit 8 mods on a 3 mod ship)
B) Number of turrets/missiles

Should we start cracking open the door of enforcing limits?  If so, where do we stop?

I think that opens a massive can of worms, and I don't see any actual benefit to it.  Part of the advantage of Pyfa is you can play around with it and see what _might_ work, like adding a large cap battery to a frigate, and never mind the fitting.

We do a good job of warning the user that they're over, and I think that's where we should stop.

**Comment by Rylleyryelle** [comment]
>  @blitzmann has a better idea, but to me in the backend it's not necessarily clear what's the primary attack and the special attack.
I find the number of clicks you need to make annoying, but as a carrier pilot you should be used to that. 

couldnt you just have all the abilities enabled by default? to enable the fighters on an archon is:
click, rclick click, rclick click, rclick click
click, rclick click, rclick click, rclick click
click, rclick click, rclick click, rclick click
just to turn the stupid things on.
i as a user, would much prefer to have to DISABLE what i dont want running on them, rather than having to enable every stupid bleepity bleeping thing every time i change out a fighter to tinker.

> There's legitimate reasons for allowing you to add drones to ships when you're over the limit, or couldn't normally add it.

well thats what i mean. if a ship has 0 drone bay, i shouldnt be able to add drones. if my ship has 0 turret slots i cant add turrets, so why if i has 0 drones, can i add drones.
i understand letting people go over cap on ones that CAN use them, easier tinkering etcetera, but for ships that literally have zero capability to launch drones it makes no sense why they can even add them.
i cant fit Fiirbolgs to an Avatar, but i can add Geckos to it. see what i mean? Avatar titans dont even HAVE a drone bay, yet in pyfa i can add 40 geckos to it and turn them all on. for 8400 dps from drones it cant launch

**Comment by Ebag333** [comment]
>i as a user, would much prefer to have to DISABLE what i dont want running on them

This isn't a bad idea...until you realize that you can fit more fighters than you have tubes for, then you'd have to disable the damage from the fighters in the bay.

There's no magic bullet solution here, multiselect would be the best way to handle it, but doing _anything_ with the GUI in wxPython makes me want to cry.  I keep thinking of things "oh we should do this as a nice QoL thing for users" and then remember it's wxPython so that super easy feature is insanely hard to implement.

>i cant fit Fiirbolgs to an Avatar, but i can add Geckos to it. see what i mean? Avatar titans dont even HAVE a drone bay, yet in pyfa i can add 40 geckos to it and turn them all on. for 8400 dps from drones it cant launch

Made up numbers are still just made up numbers.

In `future Pyfa` (whatever that ends up looking like) we'll probably have some sort of toggle/setting that does strict/loose enforcement.  Strict meaning that you can't go over limits (there are still probably some soft limits we'll allow under strict, like PG/CPU) and loose meaning more like current Pyfa.

Current Pyfa is a mess because many things are loose, some things are strict, and there's not much rhyme or reason to it.  It gets really complicated when hulls change too, like losing a slot, because then something that was strict is now loose.

This isn't something to solve in the current environment as each of these functions are setup separately and would require hand coding a solution for each.  So...it is what it is for now, just be sure that there are plans to address this for the future.

**Comment by Ebag333** [comment]
@blitzmann There's a lot of good conversation in here, but I don't see any actionable items that aren't already on the road map.  We can probably close this issue unless @Rylleyryelle has something else to add.

**Comment by blitzmann** [comment]
Closing this and marking it as discussion. If there is any desire to see more changes implemented, feel free to open another ticket :)
