### ISSUE TITLE
Laser with T2 fitted crystal multi-buys incorrectly

### ISSUE THREAD

**Issue by erocs** [pyfa-org/Pyfa#760]
https://github.com/pyfa-org/Pyfa/commit/e2434619b5f209ec6c4a2ac17b646cd9101113be#diff-b217acffc2e6d4267dfd7ddabc544921R903

Create a fitting which has a laser with a T2 crystal. In the fit it will report that the fitted crystal has, for example, 1000 charges. Export the multi-buy of the fit. The quantity for the crystal will be set to the charge count and not one.

Importing this fit:
   [Executioner, Bug]

   [Empty Low slot]
   [Empty Low slot]
   [Empty Low slot]

   [Empty Med slot]
   [Empty Med slot]
   [Empty Med slot]

   Dual Light Beam Laser II, Aurora S
   [Empty High slot]
   [Empty High slot]
   [Empty High slot]

   [Empty Rig slot]
   [Empty Rig slot]
   [Empty Rig slot]

Will export this multi-buy:
   Executioner
   Dual Light Beam Laser II
   Aurora S x1000

**Comment by blitzmann** [comment]
@petosorus, you mind tackling this one? =)

I totally forgot to mention that the `numShots` property for lasers defaults to a large amount (since crystals are multi-use). Instead of `numShots`, you want to use how many can fit in the module. I don't remember if there is a property for that specifically, but it's easy to derive.

If you can't get to it, let me know and I'll work on it. :)

**Comment by petosorus** [comment]
Funny thing, using numShots return 0 for T1 non-faction crystals, usually 4000 for faction crystals and 1000 for T2 crystals (for small at least).

Using `numCharges` fixes this, and also impacts scripts in Sebos and remote Sebos or nanite paste in ancillary and remote ancillary
