### ISSUE TITLE
Integrated Analyzer hull's virus strength bonus is counted twice

### ISSUE THREAD

**Issue by MechaLynx** [pyfa-org/Pyfa#767]
http://imgur.com/a/dLx4r

**Comment by Ebag333** [comment]
In game you can only use one module at a time, but unfortunately it's not flagged that way, it's just the game mechanic (you can only use one per can).

We could do something custom to prevent you from onlining two at once but.....ehhh.....more custom hacks to prevent you from doing something you should be smart enough not to do in the first place. 

Now that I think about it, in the few rare places where there are multiple cans I bet you _can_ get the same effect.

1. Activate module 1 on can 1
2. Activate module 2 on can 2
3. Get the bonus from both modules on can 2

Bet dollars to doughnuts that happens, unless CCP has something hard coded to prevent you from running both at once (which I bet they don't).  If this is true, then it's working exactly as it should.

Let me know if I misunderstood the issue.  I'm making some assumptions here, since, you know, you just posted a pic with no information.


Oh, and hi Mecha. o/

**Comment by MechaLynx** [comment]
Sorry I thought the issue was clear :P and I think you misunderstood me. The problem is simple, pyfa counts the hull bonus for the integrated analyzers twice: while they get the bonus once in-game (so if it had 20 virus strength, it goes to 30 on an Astero), pyfa counts it twice (so you get 40 strength displayed instead). The screenshots are of the same Astero and Probe hulls with both analyzers fitted to compare cleanly - it's evidence that it is, in fact, double-counting the hull bonus (otherwise the math doesn't work out).

I think the problem arises because the integrated analyzers get bonuses from both arch and hacking skills, so (while I haven't dug into the code to see if this is the case yet), I think pyfa counts all the bonuses as if it were 2 analyzers in one, hence double-counting the hull bonus.

A hardcoded solution would be to remove the hull bonus once at the end for them, otherwise just treat it as a separate module that gets coherence from the skills and the hull bonus for strength.

**Comment by Ebag333** [comment]
>pyfa counts the hull bonus for the integrated analyzers twice: while they get the bonus once in-game

So it does.

FYI, Pyfa has this nifty little tab called `Affected By`.  If you change the view, you see exactly where the bonuses are coming from.  That would have shown the issue quite a bit more clearly. :)

https://puu.sh/rLb2L/17cf1a0aee.png

Or, you know, a few lines of text.

I'll take a look at the `doHacking` effect and see if I can figure out why.

**Comment by MechaLynx** [comment]
I think I found it in `minigamevirusstrengthbonus.py` - it looks for modules that need Hacking and Archaeology and adds the virus strength bonus once for each, except for integrated ones which need both, it adds it twice. I'm thinking of a fix and will make a pull request if I come up with something elegant.

**Comment by Ebag333** [comment]
Yup.

PR already submitted. ;)
#769

**Comment by MechaLynx** [comment]
Nice fix and props for speed :D

**Comment by blitzmann** [comment]
Thanks for the bug report @MechaLynx, and thanks for the quick fix @Ebag333
