### ISSUE TITLE
Problems finding part of code I need to work with in order to implement a feature.

### ISSUE THREAD

**Issue by vectorman1** [pyfa-org/Pyfa#782]
Hello,

I am trying to work on a feature I want implemented, however I am having difficulties finding where exactly I need to work on it.

The feature in question is the ability to middle-click fits in the fit browsing window in order to open them in a new window, as opposed to rewriting the current one.

Help would be appreciated, thanks.

**Comment by Ebag333** [comment]
Middle click is depreciated and not supported in wxPython. 

Better option would be shift lefr click, since that matches EVE. Not sure off hand how to do that though.

**Comment by vectorman1** [comment]
My guess would be that it's supported, since there is already a middle-click operation implemented and it's for closing tabs.

**Comment by Ebag333** [comment]
It's there but every time middle mouse button is clicked you get warnings that it's depreciated. 

While we hopefully won't be using wxPython too much longer, I'd rather not use functionality that is depreciated, even if it technically works. Especially when we can have the same functionality without using something that is depreciated. 

Also, Mac support is something to think about. Shift click would be natively supported there while third mouse button click isn't. 

Third mouse button is also useless on 99% of laptops using a touchpad (for all OSes). 

 You may not care about all those reasons, but for long term support it is a serious concern,so those of us maintaining Pyfa care very much. :)

**Comment by vectorman1** [comment]
The thing I am looking for with the Middle Mouse Click is consistency considering it's a Chrome-esque inspired interface - seeing the tabs, closing of tabs. I can make the key-combination/middle mouse click platform specific, I don't mind about that.

But my question was where do I go about that since I can't seem to find it myself so I'd like to stay on topic.

**Comment by Ebag333** [comment]
I briefly looked for the middle mouse button functionality, with the intent to remove it (or at least look at what would be involved with disabling it).  I didn't find it, so I'm not sure where it's called.

Middle mouse button is registered, but not sure where. vOv

**Comment by vectorman1** [comment]
I find it more interesting where the clicks on the fitting sidebar registered, since I think I found where the middleclicks are registered.

**Comment by blitzmann** [comment]
> Middle click is depreciated and not supported in wxPython.

This is not true. It works. and is supported. The current implemented is deprecated, yes, but there is a newer implementation that is not IIRC. but IIRC, the new implementation doesn't work in wx2.8, which the mac-deprecated build still uses,. This is why I stuck with what is currently there. And since we aren't upgrading wxPython any further, any feature, deprecated or not, should work going forward.

I agree that there also needs to be a key modifier as well (which, if you're trying to open the fit in a new tab, is already supported via ctrl+click), so those that don't have easy middle click can still utilize. 

As for where it is in the code: https://github.com/pyfa-org/Pyfa/blob/master/gui/builtinViews/fittingView.py#L60

You may also need to look at the ship browser and modify the binding on the fit item. I think it's bound to left click, thus it won't register the middle click. So you may need to bind on middle click as well. Play around with it and see what works. :)

**Comment by blitzmann** [comment]
Actually, it's probably best to use the middle up event:

`self.Bind(wx.EVT_MIDDLE_UP, func)`

This is not deprecated, so it shouldn't cause any warnings.

**Comment by blitzmann** [comment]
@vectorman1 I'm going to close this issue as it's not really an issue and more of a discussion. Feel free to continue to ask any questions here.
