### ISSUE TITLE
Ship bonuses for Command Bursts don't work

### ISSUE THREAD

**Issue by SeijiOeda** [pyfa-org/Pyfa#847]
(in pyfa 1.24.1, Ascension pre-release ver)
Command ships, Command destroyers and etc...'s bonuses to Command Bursts (e.g. 3% bonus to Armored and Skirmish Command Bursts strength and duration) don't work.
At least,

- Eos(Command Ship)
- Magus(Command Destroyer) 

their bonuses don't work.

**Comment by Ebag333** [comment]
Oy vey, where to even start with this one.

1. All the effects point to the `XXXXXX Command Specialist` requirement, while T1 bursts only need `XXXXX Command`.
2. The command bursts try to apply a boost to `commandBonus`.  Only problem?  `commandBonus` is now 0.  `Ten percent of nothin' is, let me do the math here... nothin' and a nothin', carry the nothin'... `

@blitzmann do we even still use the `commandBonus` attribute? It's in the code, but seems there's a _lot_ of fleet stuff left in the code and I have no idea what's used and what's not.

The simple solution would be to modify the effects to point to the individual attributes, but that's going to be 5 attributes per effect.....

**Comment by blitzmann** [comment]
@Ebag333, `commandBonus` is no longer used to my knowledge. And you're correct, all of the old fleet stuff still exists, mostly because I couldn't be fucked to remove it (no pressing need to do so), and it also gave us the option to switch back in case these new command bursts didn't work for whatever reason.

As for the issue at hand - this is another example of an old effect being reused, but changing in how it works. We don't currently have a way to detect changing modifiers, so these sometimes slip through the cracks. I'm going through now and trying to fix what I can see, will have it pushed to master shortly. :)

**Comment by blitzmann** [comment]
Should be fixed with 019b8e93b4abe916df9d2070f38b560b237ce905
