### ISSUE TITLE
Industrial Command Ship is set to 0, causes effects to seem to not to run.

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#856]
See: https://puu.sh/svWjm/9270ae111e.png

In `industrialCommandShipSkillLevelMultiplierICS4` verified that the `skillLevel` is indeed 0.

This effect only exists for 3, 4, and 5, which explains why it doesn't happen for 1 and 2.  Basically this makes it look like effects are missing or not running.

1 and 2 works correctly.

Is there a reason why you added these, @blitzmann ?  Git blame puts it on 11/20/2016.

**Comment by Ebag333** [comment]
Porpoise might have this too.

**Comment by Ebag333** [comment]
Porpoise doesn't seem to have it, but Rorq does.

#858

**Comment by blitzmann** [comment]
Thanks for the fix! 

> Is there a reason why you added these, @blitzmann 

Simple oversight. Spaceship Command skill bonuses (where a ship receives a bonus per skill level of a skill) are actually handled via the ship bonus effect files themselves and not through the skill effects (due to crazy legacy shit). This seems like me just having a brain fart with respect to this particular skill. Good catch!
