### ISSUE TITLE
Alpha Clones

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#863]
Need to do alpha clones. Simplest way would be to have a toggle for a character in their character sheet to mark them as an alpha clone. If the character is alpha'd (lol), then set skill level caps (when retrieving the level of the skill, perform lookup on alpha clone table and take the `min(skillLevel, alphaSkillLevel)`). We also need a way of marking the character as a certain race, or simply give the user the ability to select from a drop down:

* Omega Clone (default)
* Minmatar Alpha
* Amarr Alpha

...etc... Also look into and see if this information is exposed in the API.

**Comment by blitzmann** [comment]
https://github.com/ccpgames/esi-issues/issues/95

Looks like CCP might be adding "active" vs "potential" skill levels to ESI instead of providing a direct omega/alpha status, which is a bummer. Then we have the issue of ESI, which itself can be problematic since it uses SSO sign on (not very friendly for desktop applications), but we'll have to solve for this eventually as XML API is nearing EoL. 

If this happens, there's two ways to do this: 

1) Get and set the characters skills directly through the "active" skill level from ESI. I don't like this as it modifies the characters real skill level. 
2) Infer the clone state and go with the previously discussed method, by which we cap the skill level depending on the status. This is preferred, and will allow us to switch between the two clones.

Thinking about it some more, we may be able to edit the character table and add Active and Potential columns, and then just take from whichever we need. This might be the preferred solution as it allows us to consume information in the API and switch between the states relatively easily.

**Comment by Ebag333** [comment]
The issue, I think, on that particular thread was that the user asked for it on the _*public*_ node.

Too much intel for PvPers and whatnot.

I wonder if it was reopened asking for it on the _authed_ node, if they'd be okay with that. I'd like to think so.

For a stopgap measure, what about just a toggle?  Or rather probably a drop down since you have to choose which race.  It'd be pretty simple to implement, though we still have the issue of the alpha skill list (which I know we can scrape).

**Comment by blitzmann** [comment]
> For a stopgap measure, what about just a toggle? Or rather probably a drop down since you have to choose which race. It'd be pretty simple to implement, though we still have the issue of the alpha skill list (which I know we can scrape).

Exactly what was proposed in the OP. ;)

**Comment by Ebag333** [comment]
You know you don't read my posts and I don't read yours.  :)

I actually thought that this was the original post on it, and didn't realize you closed and reopened that one.  Hence the skipping to the end.

**Comment by aquarhead** [comment]
> Get and set the characters skills directly through the "active" skill level from ESI. I don't like this as it modifies the characters real skill level.

You can keep both the active levels and the trained levels, but only calculate with active levels, plus maybe a switch to use omega levels.

(Just like you said at the end of that comment)

**Comment by MaxGriswald** [comment]
Not sure if it has been mentioned in here because everyone is just talking about toggles and stuff (So I assume they are talking about using API to connect their character and then toggling whether it is an Alpha Clone or not) but what about just a very simple "Alpha - Amarr", "Alpha - Caldari", "Alpha - Gallente", and "Alpha - Minmatar" generic character on the drop-down?  I went through on my copy and added these characters, but good god it takes a long time to go through the list of skills and add them for all four races.  Currently you have "All 0" and "All 5" as defaults, just add four new generic characters?

**Comment by blitzmann** [comment]
> but what about just a very simple "Alpha - Amarr", "Alpha - Caldari", "Alpha - Gallente", and "Alpha - Minmatar" generic character on the drop-down? 

That's somewhat my current thinking on it. But rather than make default characters, this would be a flag on the character itself. So above the skill editor there would be a drop down with Omega and the values you suggested provided (for the reasons you give in the other issue - it's a good idea to give the user the option to select which clone they are in). This would implement the corresponding cap to the players skill levels.

I don't agree with having default characters like this out the gate, so this flag seems to be reasonable. As of right now, for the first iteration, it will be a manual thing to switch toggle the clone state. Eventually though, once we get  ESI figured out and this information is exposed, it will be automatic with API skill updates.

**Comment by blitzmann** [comment]
This feature is in a working state on a development branch. Still need to tweak a few things, but it's definitely coming. :)

**Comment by blitzmann** [comment]
Merged into development branch. There's still a few concerns with how to handle changing skill levels (you can change level to 5 even if it's capped at 4). Perhaps just disable the levels... Not sure yet, but it's kind of an edge case so we can cross that road if it becomes an issue.
