### ISSUE TITLE
Orca industrialBonusDroneDamage Has Stacking penality in pyfa but it should not

### ISSUE THREAD

**Issue by SpeedProg** [pyfa-org/Pyfa#866]
the role drone damage bonus on the orca should not be stacking penalized, at least that creates the values ingame simulations puts out

**Comment by Ebag333** [comment]
I wouldn't necessarily assume in game simulation is correct.  CCP has long been known to have issues with drone DPS on fits in game, I've seen Domi fits that claim to put out over 1600 DPS (actual was about 600).

Can you test the actual damage in most ideal scenario (lots of TPs, target not moving, sig bloomed with MWD running, etc)?  Damage will swing because of RNG, but we should be able to get an average and then compare to skills/fit.

**Comment by SpeedProg** [comment]
Well I can try that later, but I don't see why Rattlesnake Role Bonus is not penalized (in pyfa) but the Orca one is xD  (EFT doesn't penalize it either btw) but yeah I can try on sisi in a bit (only have a char with Industrial Command Ship III through)

**Comment by Ebag333** [comment]
Stacking penalties are a PITA because we don't actually have any information on what's penalized and what's not, other than trial and error.

It might even be CCPs error that one is penalized and not the other (if that's the case), but we have to mimic what CCP does, not what they intended to do. :)

**Comment by SpeedProg** [comment]
so I did shoot at a Dread on Sisi now (20% thermal resists) I used Hammerhead II
Did 352623 dmg in 838s  (from logs) so ~ 420 dps/s

(I added the dmg profile and used it also used my chars skills and checked that the ones on sisi that influence Drone dmg are the same lvl)
Accoding to pyfa it should have done 383 (penalized role bonus)
and when i modified industrialbonusdronedamage effect file with stackingPenalties = False
pyfa said 413 (vs those resists the dread had 20% thermal) (516 vs 0% resists ingame is 515.9)

**Comment by blitzmann** [comment]
@SpeedProg haven't had a chance to look yet, but from what you've provided this definitely seems to be a bug. Will fix tonight.

@Ebag333 for future reference, regardless of what the underlying data says about an attributes stacking penalty, ship hull and role bonuses are never stacking penalized. They are immune. :)

**Comment by blitzmann** [comment]
Should be fixed in latest master. Gonna try to make a release tomorrow with all these fixes. :)
