### ISSUE TITLE
Recursive Booster Issue / Corrupted Database

### ISSUE THREAD

**Issue by resinneublem** [pyfa-org/Pyfa#931]
You'll want to start with a fresh database for this one.

1. Add an empty Guardian fit
2. Add an empty Hurricane fit in a new tab
3. Click back to the Guardian tab and add itself as a Projected fit
4. Click back to the Hurricane tab and add the Guardian as a Command fit
5. Pyfa shits the bed with a `RuntimeError: maximum recursion depth exceeded while calling a Python object` every time you open the Hurricane fit now and the right hand metrics can't be trusted anymore.

A buddy came across this as he was tinkering with projected and command fits.

**Comment by Ebag333** [comment]
Nice find.  

Ugh.  I don't know a good solution, you *HAVE* to project effects otherwise stats can be wrong.  Probably the only halfway decent solution is to disallow projecting one ship back on another ship (so check if it's already projected one way).

**Comment by blitzmann** [comment]
Thanks for the report. This seems like an oversight more than anything. We've handled infinite recursions before, but I'll have to dig deeper into the logic to figure out the best way to handle this. :)

**Comment by Ebag333** [comment]
Reading it over again I think it's a case of projecting a fit onto itself.  I do this all the time, but it's probably something we shouldn't allow.....

**Comment by blitzmann** [comment]
Self projection? It's absolutely something we should allow - it's one of those features that was very much requested a while back (hell, before, if you did self projection, you would crash the fit just like this issue. Was known about for years lol)

**Comment by blitzmann** [comment]
So I think I have a quick fix on this. I really have to fix up the calculation function - we have old variable names in there that are no longer descriptive, and even variables that aren't used anymore.

The, to determine if we are calculating a projected fit, we need to meet two criteria: we pass in a target fit (otherwise we assume the target is self, ie local fit calculation), and `withBoosters = False`. This is because boosters (or command ships now) also utilize `targetFit` to determine where to sent their modifications. But command fits aren't projected. Anyway, this is handled here: 

https://github.com/pyfa-org/Pyfa/blob/master/eos/saveddata/fit.py#L706

The problem lies here:

https://github.com/pyfa-org/Pyfa/blob/master/eos/saveddata/fit.py#L788

When we are trying to calculate the projected fit of the Guardian, we pass in the `withBoosters` value that we already have (which in this case is true). So `projected` ends up as being False. This is a problem for two reasons: It is a projected fit (duh), and this is the method we use to stop projection recursions (we only have to calculate 1 degree of projections, as projected effects never affect other projected affects).

The fix is simply sending `withBoosters=False` instead of what we currently have. Simple oversight during the implementation of the command boosts.

This does lead to the question though - if we are calculating a command fit, do we need to calculate that command fits projected fits? I don't think so for the reasons that follow, but I want you guys to give some input and a sanity check. If we are calculating a command fit, then we are generally only interested in that fit's local calculation (so that the command effects get their bonuses). There does not exist any projected effect that modifies a command bonus. For example, a Guardian has a ship that projects a remote sebo onto it. That will modify the command Guardians sig radius, but that does fuck all for the actual target fit (the Hurricane). So my initial reaction is to not calculate command ship's projected fits.

That's the route I'm going to take I think, but I would like some thoughts on it. Please let me know if I need to explain it better - it takes a fair amount of mental gymnastics to get what I'm getting at. :)

**Comment by resinneublem** [comment]
> This does lead to the question though - if we are calculating a command fit, do we need to calculate that command fits projected fits? I don't think so for the reasons that follow...

Yeah that makes sense to me. AFAIK there's no boost that makes boosting more effective, so it's unnecessary to follow the trail.

**Comment by Ebag333** [comment]
Makes sense to me.

**Comment by blitzmann** [comment]
I'll keep it as is then, thanks all :)
