### ISSUE TITLE
Stack trace when cloning modules

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#932]
This is against the dev branch. Getting this stack trace:

```
Traceback (most recent call last):
  File ".\gui\builtinViews\fittingView.py", line 104, in OnData
    self.dropFn(x, y, data)
  File ".\gui\builtinViews\fittingView.py", line 190, in handleListDrag
    self.swapItems(x, y, int(data[1]))
  File ".\gui\builtinViews\fittingView.py", line 400, in swapItems
    sFit.cloneModule(self.mainFrame.getActiveFit(), mod1.position, mod2.position)
  File ".\service\fit.py", line 616, in cloneModule
    if new.fits(fit):
  File ".\eos\saveddata\module.py", line 401, in fits
    for attr in self.itemModifiedAttributes.keys():
  File "C:\Python27\lib\_abcoll.py", line 410, in keys
    return list(self)
  File ".\eos\modifiedAttributeDict.py", line 131, in __iter__
    all = dict(self.__original, **self.__modified)
TypeError: 'NoneType' object is not iterable
```

Fit is:
```
[Loki, Instalock Blapper]

Damage Control II
Gyrostabilizer II
Gyrostabilizer II

True Sansha Warp Disruptor
50MN Quad LiF Restrained Microwarpdrive
Sensor Booster II, Scan Resolution Script
Sensor Booster II, Scan Resolution Script
Sensor Booster II, Scan Resolution Script

Information Command Burst II, Sensor Optimization Charge
Information Command Burst II, Sensor Optimization Charge
720mm Howitzer Artillery II, Republic Fleet EMP M
[Empty High slot]
720mm Howitzer Artillery II, Republic Fleet EMP M
720mm Howitzer Artillery II, Republic Fleet EMP M
720mm Howitzer Artillery II, Republic Fleet EMP M

[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]

Loki Propulsion - Interdiction Nullifier
Loki Engineering - Power Core Multiplier
Loki Electronics - Tactical Targeting Network
Loki Offensive - Turret Concurrence Registry
Loki Defensive - Warfare Processor
```

Some items clone successfully, some don't.  Cloned the burst fine, can't clone the Arty.  This fit was cloned from another fit, so _shouldn't_ be a DB corruption issue.

In `module\saveddata.py`, line 401:
`        for attr in self.itemModifiedAttributes.keys():`

`self` is an empty module.  Ergo, no attributes, and thus the traceback is thrown.

@blitzmann any ideas why we'd be trying to loop through attributes for an empty module here?

**Comment by Ebag333** [comment]
Gyrostabs also don't clone. No traceback on those. :(

**Comment by Ebag333** [comment]
Uhhh, @blitzmann isn't the position in table the slot where items go?

https://puu.sh/t9zjW/a7b721ca61.png

How do I have more than one? :/

Also, what's a `dummySlot`?

**Comment by Ebag333** [comment]
Query I'm using to find these (in case we want to do some database cleanup later)
```
SELECT m1.*, m2.count FROM modules m1
JOIN (SELECT count(*) as count, fitID, position from modules GROUP BY fitID, position) m2 ON m1.fitID = m2.fitID and m1.position = m2.position
WHERE m2.count > 1
```

If this is more DB corruption....which I suspect it is....then I'm not sure how we should handle this.  If it's a duplicate and the itemID is null we can drop that line easy enough.  But if it's a duplicate and 2 (or more) are all unique IDs....how do we pick which out of the 2+ items is the legit one for that slot?

I'm tempted to just say to purge the conflicting data.  In my DB I have 49 records that meets the criteria above (out of 39727), so it's not a common occurrence.  Amounts to 10 fits out of the 967 I have currently.

**Comment by blitzmann** [comment]
Haven't had a chance to look at this yet, but `itemID` being `NULL` is expected. pyfa pre-populates all the slots, not just the ones with modules (ever seen the `EmptyModule` class? That's the empty module). This helps with the GUI and also simplifies the logic with ordering with the position.

`dummySlot` is basically the same thing. It seems redundant, but I believe it's used as a flag for something. Can't recall what atm.

As for having modules in the same `position`... not sure.

Can you describe in detail which module you're cloning and which slot you're trying to clone it to? Include pictures :)

But indeed, this may be some sort of corruption - whether it's from normal usage or simply a byproduct from fucking around with code, I'm not sure. Could you send me your saveddata.db so that I have something in case I can't reproduce?

**Comment by Ebag333** [comment]
>Haven't had a chance to look at this yet, but itemID being NULL is expected. pyfa pre-populates all the slots, not just the ones with modules (ever seen the EmptyModule class? That's the empty module). This helps with the GUI and also simplifies the logic with ordering with the position.

Yeah, I'm familiar with empty modules.  We might need a simple `.isEmpty` check to avoid that particular stacktrace. I'm not even sure why we'd be checking attributes on empty modules since there are none.

I haven't figured out how to replicate on demand, so that's the challenge.  As I've been fiddling with it, it sometimes fixes itself.  Fortunately, there's one that's still broken. :)

https://puu.sh/t9Mm3/a9e8a79793.gif

I shared a Google Drive folder with you with a copy of the DB in it.

I'm pretty sure that this is just bad data where we somehow got multiple modules in the same position.  The question is...how do we clean it up.

**Comment by blitzmann** [comment]
So, I was able to reproduce consistently. Take the fit that you have, and add the Amplification node (without taking the Warfare Processor off). The following query returns `4`

```SELECT count(*) AS num FROM modules m1 
JOIN (SELECT count(*) as count, fitID, position from modules 
GROUP BY fitID, position) as m2 
ON m1.fitID = m2.fitID and m1.position = m2.position 
WHERE m2.count > 1```

This will be a good start to figuring out why it happens in the first place. But I'm still of the belief that it shouldn't really matter as `position` is a sorting value

**Comment by blitzmann** [comment]
I've pushed a couple of fixes to master (forgot to make a separate branch, ah well). Please pull and test if you're still receiving that error.

I fixed the issue with the subsystem getting a new position, although this was more of a nice to have than a critical fix. Unfortunately, this situation happens in other places as well. For example, CCP gives a ship a new mid slot - all existing fits for that ship will assign the position of len(modules) to that new slot when it finds out about it. pyfa does not attempt to reorganize the positions.

We have always assumed `position` would also be the index in the modules list, and we have used it under such assumption in the code. So this causes problems when we try to swap modules around, because we need to use the index of the modules in the list, and we're sending the wrong data as the index.
We just cannot rely on `position` being sequential or unique. It's only good for sorting the modules in an ORDER BY, which is what SQLAlchemy does.

To fix this, there is a new property on Module called `modPosition` (for lack of a better name). This returns the actual index of the module within it's container. We can use this going forward anytime we need the modules position, and leave `position` to internal use only

**Comment by Ebag333** [comment]
I'll test when I get a chance.

**Comment by Ebag333** [comment]
So it seems to work, but where are the duplicate modules going?

For example my fit 941 has this before I open it with your commit.
```
"38122"	"941"	"30050"			"0"	"0"	"1"
"38123"	"941"	"30143"			"0"	"0"	"2"
"38124"	"941"	"30122"			"0"	"0"	"3"
"38125"	"941"	"30090"			"0"	"0"	"4"
"38126"	"941"	"1248"			"0"	"0"	"5"
"38127"	"941"	"2048"			"0"	"0"	"6"
"38128"	"941"	"1541"			"0"	"0"	"7"
"38129"	"941"	"1541"			"0"	"0"	"8"
"38130"	"941"	"1541"			"0"	"0"	"9"
"38131"	"941"	"6005"			"1"	"0"	"10"
"38133"	"941"	"19279"			"1"	"0"	"11"
"38134"	"941"	"2050"			"1"	"0"	"12"
"38135"	"941"	"19208"			"1"	"0"	"13"
"38136"	"941"	"41218"			"0"	"0"	"14"
"38137"	"941"	"1877"		"27361"	"1"	"0"	"15"
"38138"	"941"	"1877"		"27361"	"1"	"0"	"16"
"38139"	"941"	"1877"		"27361"	"1"	"0"	"17"
"38140"	"941"	"1877"		"27361"	"1"	"0"	"18"
"38141"	"941"	"1877"		"27361"	"1"	"0"	"19"
"38142"	"941"	"31372"			"0"	"0"	"20"
"38143"	"941"	"31378"			"0"	"0"	"21"
"38144"	"941"	"31378"			"0"	"0"	"22"
"38145"	"941"	"29972"			"0"	"0"	"22"
"38147"	"941"	"43555"		"42695"	"1"	"0"	"23"
```

Post commit (and opening it in pyfa) it looks like this:
```
"38122"	"941"	"30050"			"0"	"0"	"0"
"38123"	"941"	"30143"			"0"	"0"	"1"
"38124"	"941"	"30122"			"0"	"0"	"2"
"38125"	"941"	"30090"			"0"	"0"	"3"
"38126"	"941"	"1248"			"0"	"0"	"4"
"38127"	"941"	"2048"			"0"	"0"	"5"
"38128"	"941"	"1541"			"0"	"0"	"6"
"38129"	"941"	"1541"			"0"	"0"	"7"
"38130"	"941"	"1541"			"0"	"0"	"8"
"38131"	"941"	"6005"			"1"	"0"	"9"
"38133"	"941"	"19279"			"1"	"0"	"10"
"38134"	"941"	"2050"			"1"	"0"	"11"
"38135"	"941"	"19208"			"1"	"0"	"12"
"38136"	"941"	"41218"			"0"	"0"	"13"
"38137"	"941"	"1877"		"27361"	"1"	"0"	"14"
"38138"	"941"	"1877"		"27361"	"1"	"0"	"15"
"38139"	"941"	"1877"		"27361"	"1"	"0"	"16"
"38140"	"941"	"1877"		"27361"	"1"	"0"	"17"
"38141"	"941"	"1877"		"27361"	"1"	"0"	"18"
"38142"	"941"	"31372"			"0"	"0"	"19"
"38143"	"941"	"31378"			"0"	"0"	"20"
"38144"	"941"	"31378"			"0"	"0"	"21"
"38145"	"941"	"29972"			"0"	"0"	"22"
"38147"	"941"	"43555"		"42695"	"1"	"0"	"23"
```

You vanished off item `31378` (Medium Cap Control Circuit II) and kept `29972` (Tengu Defensive - Warfare Processor), but how did you decide which of those two to keep?  Okay for that one it's fairly easy, but not all of them are like that.

Anyway, this looks really good, so I'm going to close that PR.

**Comment by blitzmann** [comment]
I am not sure what you mean... none of the modules have been deleted (and shouldn't' be deleted). In the before and after, there are two 31378 modules. The only thing that has changed is the position (which is expected given), and the only thing my commit does is fix the issue with swapping / cloning / dragging modules...

**Comment by Ebag333** [comment]
Ahh, I see, starts from 0, that's the bit I missed.

I'll see if I find any other ones that look odd and report them in to you.  Can't be any worse than what it was though! :)
