### ISSUE TITLE
Damage Pattern Editor will not open

### ISSUE THREAD

**Issue by Cold-FuzZ** [pyfa-org/Pyfa#949]
Attempting to open the Damage Pattern Editor is Unsuccessful when using using Ctrl-D or clicking on it manually, as well as this I cannot use any Damage pattern profiles by right clicking on the incoming damage pattern - there is no drop down menu like there previously was.

**Comment by Cold-FuzZ** [comment]
Just found other posts with the same issue, sounds like a  DB corruption, will send %userprofile%\.pyfa\saveddata.db file to sable.blitzmann@gmail.com, as reccomended previously.

**Comment by blitzmann** [comment]
Thanks for the database, very helpful. The root cause of this is that you had a `NULL` value for the name of one of your profiles, and pyfa just freaked out not knowing how to handle that. 

This is what we should do to fix it:
* `NOT NULL` the name field
* Check to make sure the other fields can be NULL without breaking anything. If not, ensure that these are also `NOT NULL`
* We will have to make a migration script that modifies current user database to add the `NOT NULL`s required, and removes any offending records

This should fix that source of corruption

**Comment by Ebag333** [comment]
The GUI already doesn't allow you to use nulls for names.  I'm guessing this is an artifact of something we're doing in code when manipulating these (adding/deleting/copying).

**Comment by blitzmann** [comment]
> The GUI already doesn't allow you to use nulls for names. I'm guessing this is an artifact of something we're doing in code when manipulating these (adding/deleting/copying).

I know, this is something that may have slipped through the cracks. Not only that, I vaguely remember that there was the possibility of saving something without a name, and this might be a left over from that.

Regardless the cause, having the constraint on the database will ensure we don't have this happen again.

**Comment by Cold-FuzZ** [comment]
Appreciate the response and the fix, it's now working as intended. Cheers !
