### ISSUE TITLE
Fleet bonuses does not calculated implants

### ISSUE THREAD

**Issue by earthwormjim123** [pyfa-org/Pyfa#969]
Hello.
 Its ok that when i simulate fleet bonuses with mindlink and without it - effect same one in both cases ?

**Comment by Ebag333** [comment]
Can you post the fit you're using here?  What attributes do you expect to see changed?

Remember  that mindlinks changed with bursts, they do not have the same effect that they used to.

**Comment by earthwormjim123** [comment]
Just chek - problem not only with midlink imp> all implants dont make effect on fit =\
pyfa 1.26.0

**Comment by blitzmann** [comment]
It would help to have a bit more detail and information on how you have it set up please. Makes it easier to troubleshoot.

Post the fit that is being used as a command booster, and the fit that the booster is applying to. Post the mindlink that is being used. I can toake a look this weekend :)

**Comment by earthwormjim123** [comment]
Ok. Its problem with **ALL** implants, not only fleet.
Example: i take 2 characters
1) all 5 lvl skill without any imps
http://clip2net.com/s/3HaDMYa
2) 5 lvl skill with 6,7,8 imps spot with capacitor implants
http://clip2net.com/s/3HaE036

And check it on the feet: and the result the same:
1) http://clip2net.com/s/3HaEgaD
2) http://clip2net.com/s/3HaEhYX  - with imps it must be 9670 capacitor and balance: -196/+144

and this problem with ALL IMPLANTS. The dont add effect

I check it on another pc. dwnl 1.26.0 pyfa on pc who never have it. and problem was there too

**Comment by blitzmann** [comment]
This is better information, thank you for providing it. I'll take a look today; hopefully it's an easy fix.

**Comment by blitzmann** [comment]
@earthwormjim123 do me a favor and ensure that you have selected to use Character implants for the fit rather than fit implants:

![image](https://cloud.githubusercontent.com/assets/3904767/22630445/2410ef4e-ebc8-11e6-80bf-7b7bc97c7a5f.png)

pyfa supports both fit-specific implants or character implants. This is useful if you have a character with a set of implants, but you're creating a theoretical fit that is based around a different set of implants. You don't have to create a new character in that case - just apply those implants to the fit. However, if you're unaware of this mechanism, you can easily miss the fact that you can toggle character implants on and off.

It seems to work for me fine, want to verify it works for you too. :) Thanks!

**Comment by earthwormjim123** [comment]
omg. Sry i dont know about it =D. thx a lot
BUT i noticed that pyfa give more resist from bonuses that ingame fiting window

**Comment by Ebag333** [comment]
>BUT i noticed that pyfa give more resist from bonuses that ingame fiting window

Do you have an example of this?

If it's just a percent or so, that's "normal".  There's some rounding that happens, and it seems that in game the values are rounded differently than Pyfa.

If it's a more extreme example, then I'd like to know about it. :)

**Comment by blitzmann** [comment]
Yeah, if you can provide screenshots of eve values vs pyfa values, and provide the fit in question, we can look into it.

**Comment by earthwormjim123** [comment]
Somewhere it's like 3% or so. If this ok?
Fit for resist on widow (how i can use <spoiler> in thread ?)
[Widow, 's copy]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
Gistum C-Type Adaptive Invulnerability Field
[Empty Med slot]
[Empty Med slot]
Adaptive Invulnerability Field II
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot] 

pyfa screen with bonus + shield midlink
http://clip2net.com/s/3He95jQ
eve screen with bonus + shield midlink
http://clip2net.com/s/3He8gqo

pyfa screen with bonus without mindlink
http://clip2net.com/s/3He92lf
eve screen with bonus without mindlink
http://clip2net.com/s/3He8Llr

**Comment by blitzmann** [comment]
@earthwormjim123 are the values correct when not using a fleet boosts?

Can you post the command fit that is used with the fitting in the screenshots you linked? I'm having trouble replicating your issue.

**Comment by earthwormjim123** [comment]
Yes, correct without bonuses
Character has skills:
5lvl shield command
5lvl shield command specialist
5lvl caldari defensive system
fit: 
[Tengu, shield bo midlink]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Shield Command Burst II, Active Shielding Charge
Shield Command Burst II, Shield Extension Charge
Shield Command Burst II, Shield Harmonizing Charge
[Empty High slot]
[Empty High slot]
[Empty High slot]

Medium Command Processor I
Medium Command Processor I
[Empty Rig slot]

Tengu Defensive - Warfare Processor
Tengu Electronics - CPU Efficiency Gate
Tengu Engineering - Capacitor Regeneration Matrix
Tengu Offensive - Covert Reconfiguration
Tengu Propulsion - Interdiction Nullifier

**Comment by blitzmann** [comment]
thanks bud, will take a look

**Comment by earthwormjim123** [comment]
thx a lot for yours working 0/

**Comment by blitzmann** [comment]
Not sure where we left off on this - I remember taking a look into it, but not sure what I found, and of course I forgot to document here. The screenshot links are dead now. Gonna close this due to inactivity and the fact that I'm a bit fuzzy now on what this was about lol. :)

@earthwormjim123 if you are still experiencing this problem, please open a new issue with the fit that you're using and detailed information on what the values are and what they should be. Screenshots always help (you can drag them directly into the github issue and they will upload to the issue itself, no worries about other image hosting deleting the file). We haven't had many reports of bonuses being wildly off, so hopefully whatever was causing the issue was fixed elsewhere. :P
