### ISSUE TITLE
Dont match capstability in pyfa and IG

### ISSUE THREAD

**Issue by Eiden2004** [pyfa-org/Pyfa#979]
Hi there!
Have a problem with capacitor stability in pyfa and ingame.
Pyfa shows one, ingame i see another. What it can bee?
![astero pyfa](https://cloud.githubusercontent.com/assets/25662179/22782752/4367163c-eed1-11e6-987a-d199ca6cb253.jpg)
![nvi pyfa](https://cloud.githubusercontent.com/assets/25662179/22782753/436d6a46-eed1-11e6-835c-04d505e2b5ae.jpg)
![2017 02 07 22 55 36](https://cloud.githubusercontent.com/assets/25662179/22782759/5003435c-eed1-11e6-8c24-cd5b85ab4065.png)
![2017 02 09 12 04 03](https://cloud.githubusercontent.com/assets/25662179/22782768/58ec9e28-eed1-11e6-9078-b78a4a1a2b92.png)

**Comment by Ebag333** [comment]
Cap stability is something being worked on, actually.

Can you post the fits here, I'd like to try something....

**Comment by Eiden2004** [comment]
[Astero, My Asterko]

Small Armor Repairer II
Energized Adaptive Nano Membrane II
Energized Adaptive Nano Membrane II
Capacitor Power Relay II

5MN Quad LiF Restrained Microwarpdrive
Data Analyzer I
Cap Recharger II
Small Cap Battery II

Covert Ops Cloaking Device II
Core Probe Launcher I, Sisters Core Scanner Probe

Small Memetic Algorithm Bank II
[Empty Rig slot]
[Empty Rig slot]

**Comment by Eiden2004** [comment]
[Vexor Navy Issue, Vexor test]

'Greaves' Medium Armor Repairer I
'Greaves' Medium Armor Repairer I
Drone Damage Amplifier II
Capacitor Power Relay II
Energized Adaptive Nano Membrane II
Energized Adaptive Nano Membrane II

Republic Fleet Large Cap Battery
Republic Fleet Large Cap Battery
10MN Monopropellant Enduring Afterburner
Languid Enduring Ladar ECM

Drone Link Augmentor II
[Empty High slot]
[Empty High slot]
[Empty High slot]

Medium Anti-Explosive Pump II
Medium Auxiliary Nano Pump I
Medium Nanobot Accelerator I

**Comment by blitzmann** [comment]
> Can you post the fits here, I'd like to try something....

It's not like we have an issue template asking for this information from the get go... :P

EVE in-game cap stability values (and a lot of other in-game fitting window stats) are notoriously bad. I don't know exactly how it is different but the calculations aren't the same that pyfa uses (for example, we take into consideration "staggering" the module, while I don't think EVE does.) From what I've heard from folks, pyfa's is a much better representation of real-world cap stability. So I dunno if this is really a bug or not.

**Comment by Ebag333** [comment]
Thanks.

Obviously I don't have your skill set, so the numbers won't be exact, but I can get them pretty close.

One big difference is in Pyfa you don't have the Data Analyzer on, but in game you will.  You should switch to the Ghost fitting window, then you can toggle things on/off properly.  So that explains a big chunk of the difference.

@blitzmann the new Gnosis engine is much closer to in game than the current.  I agree that the in game engine tends to be overly pessimistic, and a lot of it depends on _what_ and _when_ you choose  to set your minimum stability (which we no doubt handle differently than in game.

**Comment by Eiden2004** [comment]
In the GF mode i have the same 5.3% capstab with all modules on, and only 19% with modules the same with pyfa-window on (MWD+Repair+Probe launcher). But 19% still not 47%
![2017 02 09 18 07 20](https://cloud.githubusercontent.com/assets/25662179/22796636/c3665ae6-ef03-11e6-86ff-2bd6a1537fb0.png)
![2017 02 09 18 07 07](https://cloud.githubusercontent.com/assets/25662179/22796637/c366a424-ef03-11e6-9c7f-3bfbb7caa8e4.png)

**Comment by Ebag333** [comment]
Remember that a *tiny* difference can cause big number swings.  Literally .1 GJ/s will make a huge difference, especially when you're talking about small ships like a frigate.  While 28% seems like a lot, very small differences can make that swing, because of how cap is calculated (basically on a very steep curve).

19% is an odd number for the in game one, as well.  Your peak cap will be somewhere around 25%.  It's relatively easy to get that number _higher_ (up to about 28-29%), but getting it _lower_ is very hard (I haven't managed to get below 23%).  19% would mean that fit is not cap stable, and would eventually (given enough time) fall to 0%, which likely means CCP cut off the capsim calcs before that happened.

Choosing _when_ you cut the calcs off is a tricky point.

Once the new capsim engine is in place, the numbers will be much closer to in game (though still not exact).  Until then, keep the in game numbers in mind, but as @blitzmann said the numbers in Pyfa are fairly reliable.

(Unless you have a ASB/AAR fit.  But that's specific to those modules, because we assume it has a 10s reload.)

**Comment by Eiden2004** [comment]
Lol! Problem resolved and seem like im looking not there :)
In shadow mode capstab even higher than in pyfa...
![2017 02 09 18 19 40](https://cloud.githubusercontent.com/assets/25662179/22796998/5cebba84-ef05-11e6-80fa-8fe3125f8705.png)

**Comment by Ebag333** [comment]
I don't know why CCP hides that as a tooltip. :(

The % on there doesn't match the image of the capacitor either.  I mean, it's close to 51%, but it's clearly below 50% filled.

CCP things. vOv

**Comment by Eiden2004** [comment]
But anyway, with 2 modules up, capa didnt fall lower than +-half in real tests (47% was the lowest percentage that i see for 15 mins of active modules, 58 highest. Average 51-52).
![2017 02 09 18 31 15](https://cloud.githubusercontent.com/assets/25662179/22797453/f309e4c2-ef06-11e6-8fb8-c0ff26f2ac86.png)

**Comment by blitzmann** [comment]
I never realized the % shown there is not the cap stability. Mind = blown.

So this issue is resolved then?

**Comment by Ebag333** [comment]
>I never realized the % shown there is not the cap stability.

I suspect it's a sort of minimum cap stability.  I was thinking of doing the same, once I figured out that Pyfa already supports handling two cap stability numbers....

**Comment by Eiden2004** [comment]
Y, i think problem resolved.  At least Astero really dont drop down less than 47% of capasitor, that correspond with 47.5 in pyfa parametre.

**Comment by blitzmann** [comment]
k, I'm gonna close this issue then. Feel free to post results of tomorrows test and we'll see if we need to address then  :)

**Comment by Eiden2004** [comment]
Test is succsess! Dont make screens, but NVI also capstab ~50% with 3 modules on: 2reps+AB :)
