### ISSUE TITLE
Bug Catching: Wrap all @property attributes in a Try/Except

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#989]
See https://github.com/pyfa-org/Pyfa/issues/988#issuecomment-279486966 for a bit of history on this.

Long story short is we can throw exceptions on a number of properties. This is very likely part of the reason why we have to run recalcs multiple times, because the first time we run them, something is missing and the calc doesn't work.  The big issue we have is that there is no stacktrace output, so these are completely hidden unless you go hunting deep in the object.

In addition to the example linked above, another one that will crop up fairly often is `def cycleTime(self):` in `saveddatta.module`.  We have this bit of code:
```
@property
def cycleTime(self):
    reactivation = (self.getModifiedItemAttr("moduleReactivationDelay") or 0)
    # Reactivation time starts counting after end of module cycle
    speed = self.rawCycleTime + reactivation
```
The stacktrace gets thrown most likely because `rawCycleTime` doesn't exist or is set to `None`, since we don't have any handling of it and simply assume it exist it'll stacktrace.

This isn't a _solution_, mind you, but it should let us identify when and where these are stacktracing, instead of it getting swallowed up and never seen.

**Comment by blitzmann** [comment]
>  This is very likely part of the reason why we have to run recalcs multiple times, because the first time we run them, something is missing and the calc doesn't work.

I see a lot of "very likely" and "most likely" in these... I would like to see concrete reasoning as to why these are happening. As stated in the other issue, when halting execution and inspecting objects with pyCharm, it's going to take that object and evaluate all properties, even properties that don't make sense to run within the current point of execution (hence the errors).

So, the reason you see a stacktrace in `cycleTime` is because it doesn't have the data required yet, since the fit is not calculated. Which is fine, since we should never be calling this property until the fit is calculated anyway. If we ever do, we will get a stacktrace and know about it. They aren't just swallowed up as you say.

Throwing trys and catches in all properties is a solution to a problem that doesn't exist within normal execution of the code. :)
